esp8266/Arduino

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.cpp
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_si2c.c
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring_digital.c
hardware/esp8266com/esp8266/cores/esp8266/esp8266_peri.h
hardware/esp8266com/esp8266/cores/esp8266/twi.h
hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.cpp
hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.h
hardware/esp8266com/esp8266/libraries/Wire/Wire.cpp
hardware/esp8266com/esp8266/platform.txt
hardware/tools/esp8266/sdk/ld/eagle.app.v6.ld

increase irom0 from 0x3C000 to 0x6B000 (+192KB) space

increase irom0 from 0x3C000 to 0x6B000 (+192KB) space

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring_digital.c

disabling pulls on pinMode is not needed, since they are cleared 2
lines above.

add OUTPUT_OPEN_DRAIN

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/debug.cpp
hardware/esp8266com/esp8266/libraries/SPI/SPI.cpp

add some notes to the SPI functions (aligned to 32Bit)

---

docs/exception_causes.md
hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.cpp
hardware/esp8266com/esp8266/cores/esp8266/abi.cpp
hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c
hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/examples/WiFiMulti/WiFiMulti.ino
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.h
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/include/wl_definitions.h
hardware/esp8266com/esp8266/libraries/SPI/SPI.cpp
hardware/esp8266com/esp8266/libraries/SPI/SPI.h
hardware/esp8266com/esp8266/platform.txt
hardware/tools/esp8266/sdk/include/ets_sys.h
hardware/tools/esp8266/sdk/include/osapi.h

fix SPI speed calculation @160Mhz Clock
fix a bug by extensive use of os_printf

fix SPI speed calculation @160Mhz and many other stuff

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h

Disable DHCP if using static IP
With dhcp disabled, I noticed about 50% less conncection time

Add function overload to config to include DNS

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/Esp.h

rsil doesn't require a sync,
isync  needed for processor state register
esync needed to get special register

correct sync use

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFiMesh/examples/HelloMesh/HelloMesh.ino
hardware/esp8266com/esp8266/libraries/ESP8266WiFiMesh/keywords.txt
hardware/esp8266com/esp8266/libraries/ESP8266WiFiMesh/library.properties
hardware/esp8266com/esp8266/libraries/ESP8266WiFiMesh/src/ESP8266WiFiMesh.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFiMesh/src/ESP8266WiFiMesh.h

I wrote this library for a university project and thought it might be useful for someone else. I tried to put it in the same format as ESP8266WebServer.

add ESP8266WiFiMesh library

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h

a trivial edit. to make ESP8266Wifi support hidden ssid in the function SoftAP

Add Network Masking support

---

README.md

Add reference on how to enable printf function

---

hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_si2c.c

This makes the BNO055 MOSTLY work on the ESP8266.  See #526 for some pictures.

adjust clock stretch

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino

Best to stick to standard port numbers
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

Changed Telnet Port to port 23

---

README.md
hardware/esp8266com/esp8266/cores/esp8266/WString.h
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.h

This allows for the content of server response to be stored in flash
memory.
see https://github.com/esp8266/Arduino/issues/596#issuecomment-124151609 for some background.

send_P, sendContent_P, and FPSTR

---

hardware/esp8266com/esp8266/doc/reference.md

Also, update dht library version to 1.1.1

Mention DHT22 in addition to DHT11

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp

#754 fix _useClientMode & _useApMode in SDK auto connect mode

#754 fix _useClientMode & _useApMode in SDK auto connect mode

---

hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp

adding resetInfo.reason 6

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp

Update status code reason phrases

---

doc/boards.md

fix img links

---

cores/esp8266/Esp.cpp

I've received new ESPs with Flashes identified with BergMicro and those are the IDs.

add BergMicro Flash IDs

---

libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino

I made the progress line print over itself.

Make progress print on the same line.

---

doc/ota_updates/ota_updates.md

improve docs

---

boards.txt

change Adafruit Huzzah upload method to nodemcu

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h
cores/esp8266/Updater.cpp
cores/esp8266/Updater.h
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h
libraries/ESP8266httpUpdate/examples/httpUpdate/httpUpdate.ino
libraries/ESP8266httpUpdate/examples/httpUpdateSPIFFS/httpUpdateSPIFFS.ino
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

HTTPupdate add flash size check + better error output

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h
libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClient.h
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.h
libraries/ESP8266WiFi/src/include/ClientContext.h
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

check bin magic, add peekBytes

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

#define'ing DEBUG_HTTPCLIENT in ESP8266HTTPClient.h will show this compilation problem

fix debug build

---

boards.txt
variants/d1_mini/pins_arduino.h

change wemos d1 mini board to wemos d1 r2 & mini board

fix d1_mini board.

---

boards.txt
doc/filesystem.md
package/package_esp8266com_index.template.json
variants/ESPDuino/pins_arduino.h

ESPDuino boards from doit.am (arduino uno look like board for esp8266)

Add espduino board

---

boards.txt
cores/esp8266/Updater.h
cores/esp8266/core_esp8266_main.cpp
cores/esp8266/debug.h
libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h
libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/Parsing.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiMulti.h
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
platform.txt

allow control of  debug and debug level from IDE

allow control of enabling debug and debug level from IDE

---

tools/espota.py

my firewall wouldnt allow for the esp to talk to my pc.  I added support for maually selecting host ip and port for espota.py code.

add support for manually selecting ip and port for host side

---

boards.txt
libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp

correct default return value for softAP
fix eclipse debug level handling

correct default return value for softAP + fix eclipse debug level handling 

---

package/build_boards_manager_package.sh

This version contains some significant improvements and bug fixes

Use SoftwareSerial version 2.2

---

libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp

fix unused warning #1407

---

cores/esp8266/IPAddress.cpp
cores/esp8266/IPAddress.h

manual merge of IPAddress from Arduino.cc https://github.com/arduino/Arduino/commit/e3909b4e2c050213e836f2ca9c132f906bc832b9

manual merge of IPAddress from Arduino.cc 

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp
libraries/ESP8266mDNS/ESP8266mDNS.h

Make the OTA port appear in the IDE (without having to restart it) and make it show up in `avahi-browse -a`. Thanks to @me-no-dev for writing this patch.

advertise all hosted services

---

libraries/EEPROM/EEPROM.cpp

_dirty set only if the value being written is different from the existing value in the cache.

Optimised _dirty flag.

---

boards.txt

- Added new option for Core + SSL + TLS Mem
- Added TLS Mem debuging when debugging All

Add TLS Mem debug level option

---

cores/esp8266/cbuf.cpp
cores/esp8266/cbuf.h

add peek for multiple bytes
add remove
add resizeAdd
add resize

move function code of cbuf to cbuf.cpp

---

doc/libraries.md

Updated esp8266 specific branches for NeoPixelBus
Added reference to Task library

Updated library docs

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h
doc/changes.md
doc/libraries.md
tools/sdk/include/user_interface.h

Added function to return reset reason in human readable format

---

libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp

fix #1499 - ESPhttpUpdate.updateSpiffs

---

cores/esp8266/HardwareSerial.cpp
cores/esp8266/cbuf.cpp
cores/esp8266/cbuf.h
platform.txt

update version in platform.txt

rename cbuf getSize to available, and add size function

---

doc/libraries.md

I tested Encoder library on my ESP8266-12 and everythings works well. We can add this one to the list of compatible libraries.

Updated docs

---

doc/ota_updates/ota_updates.md

this way the script should work after copy & paste

fix demo OTA php script

---

README.md

Just a short mention of the makefile which can be used for building project based on this git

Reference to the esp8266/Arduino makefile added

---

boards.txt
tools/sdk/ld/eagle.flash.512k128.ld

Added 128K SPIFFS for 512KB modules

---

cores/esp8266/FS.h
cores/esp8266/Print.cpp
cores/esp8266/Stream.cpp
cores/esp8266/WString.cpp
cores/esp8266/core_esp8266_noniso.c
cores/esp8266/spiffs/spiffs_config.h
cores/esp8266/spiffs_api.cpp
cores/esp8266/spiffs_api.h

- remove ICACHE_FLASH_ATTR
- remove unneeded SDK includes
- split spiffs_api into .h and .cpp

Clean up core files

---

libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h

As per http://stackoverflow.com/a/10864297

Add font MIME types, fix #1601

---

libraries/ESP8266WebServer/examples/SDWebServer/SdRoot/edit/index.htm

Add correct handling for *.json *.h *.html and *.ico

Add more file types handling

---

tests/common.sh

Arduino-builder doesn't "rebuild all" automatically any more: 
https://github.com/arduino/arduino-builder/pull/129.

Clean build directory after each sketch

---

variants/ESPDuino/pins_arduino.h
variants/adafruit/pins_arduino.h
variants/d1/pins_arduino.h
variants/d1_mini/pins_arduino.h
variants/espino/pins_arduino.h
variants/espinotee/pins_arduino.h
variants/espresso_lite_v1/pins_arduino.h
variants/espresso_lite_v2/pins_arduino.h
variants/generic/common.h
variants/generic/pins_arduino.h
variants/nodemcu/pins_arduino.h
variants/thing/pins_arduino.h
variants/wifinfo/pins_arduino.h

Clean up variants, fix digitalPinHasPWM definition

---

libraries/ESP8266WebServer/src/Parsing.cpp

Complete read POST/GET request.

Web server request read fix

---

libraries/SPI/SPI.cpp

There's no need to fill the whole fifo if size * repeat doesn't actually use more than 64 bytes, so this change speeds up those cases somewhat.
I don't think I can squeeze any more speed out of writePattern() after this.

Speed up writePattern() a bit more

---

libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp

added .c_str() to currentVersion

---

libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ArduinoOTA/ArduinoOTA.h

I want to use ```ArduinoOTA::getHostname()``` interface.

Add ArduinoOTA::getHostname() interface

---

doc/faq/a01-espcomm_sync-failed.md
doc/faq/a02-my-esp-crashes.md
doc/faq/a03-library-does-not-work.md
doc/faq/readme.md

New FAQ item: ESP.restart() doesn't work
Review of all FAQ items to do typo fixes

New FAQ item: ESP.restart() doesn't work, typo fixes

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp

fix link list bug in ESP8266mDNS

fix link list bug in ESP8266mDNS

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp

unrefing the _conn object in destructor

fixed crash in mDNS destructor

---

cores/esp8266/WMath.cpp

fixes https://github.com/esp8266/Arduino/commit/fb00e64a6f65dede8d897d07a28d7d02f74ae742 error

out_min should not be in divisor

---

cores/esp8266/FS.h

https://github.com/esp8266/Arduino/issues/2553

Add Arduino File standard seek call

---

libraries/ESP8266HTTPUpdateServer/examples/SecureWebUpdater/SecureWebUpdater.ino

This PR fixes the `curl` command.

Update curl command for SecureWebUpdater

---

boards.txt
doc/boards.md
package/package_esp8266com_index.template.json

4D Systems Addition of gen4-IoD Range

Addition of gen4-IoD Range

---

cores/esp8266/Updater.cpp
cores/esp8266/Updater.h
libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ArduinoOTA/ArduinoOTA.h
tools/espota.py

- place all strings into PROGMEM
- when low on heap, reduce the size of write buffer to 256 bytes
- check if boot mode is correct, otherwise bail out from `Updater.begin`
- if `Updater.begin` returns an error, forward it from ArduinoOTA to espota.py for display

Minor improvements to Updater

---

cores/esp8266/core_esp8266_postmortem.c
libraries/ESP8266mDNS/ESP8266mDNS.cpp
libraries/GDBStub/README.rst
libraries/GDBStub/src/GDBStub.h
libraries/GDBStub/src/internal/gdbstub.c
libraries/Wire/Wire.cpp

less warnings + automate gdb trigger when using GDBStub

small goodies

---

cores/esp8266/Schedule.cpp

See: https://github.com/esp8266/Arduino/pull/2881/files/d55efd3e144256afe043d251a0f6c778c5139f7c#diff-67390c99ad4faa2080719586ebf73b9e and https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/213822247#L1248

Fixed unused-function warning

---

libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer.cpp

- Removed minor typo in HTML of ESP8266HTTPUpdateServer.cpp (This DOES show up in browsers).

Removed random '\n' character in HTML

---

README.md

an 'easyfix', and I think uncontroversial

patch for #3462

---

cores/esp8266/interrupts.h

Just fixes the apparently incorrect comment

Fixed comment InterruptLock "disable interrupts"

---

package.json

Just a small change in order to stay in sync with  the version numbering on PlatformIO

Increase version for PlatformIO

---

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp

bail if ret is false, do not enablesta when wifioff set, do not overwrite return value!

fixes #3795

---

libraries/EEPROM/EEPROM.cpp
libraries/EEPROM/EEPROM.h

Added length and operator[] methods, added some constness, missed dirty clear (#2066)

---

cores/esp8266/Esp.cpp
cores/esp8266/spiffs/spiffs_hydrogen.c

cleanup warnings

---

cores/esp8266/umm_malloc/umm_malloc.c

realloc bug: fix #3953

---

libraries/ESP8266WiFi/examples/HTTPSRequestCACert/HTTPSRequestCACert.ino

in example properly wait for NTP to be set

---

libraries/Ethernet/library.properties
libraries/SD/library.properties

Fixes https://github.com/esp8266/Arduino/issues/3868.

Set architecture=esp8266 for bundled SD and Ethernet libraries

---

doc/conf.py
tests/device/libraries/BSTest/runner.py
tests/device/test_WiFiServer/test_WiFiServer.py
tests/device/test_http_client/test_http_client.py

Probably not quite enough to get the code running with Python 3, but it's a start and doesn't hurt with Python 2.

Python 3 fixes

---

libraries/ESP8266WiFi/src/include/UdpContext.h

changed last line of the file to
#endif//UDPCONTEXT_H

Fix issue with UdpContext.h comment

---

tools/sdk/ld/eagle.app.v6.common.ld

Add support for @PlatformIO Core 3.5.0

---

libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino

WiFiTelnetToSerial Example - Minor Issues #2435

---

libraries/esp8266/examples/RTCUserMemory/RTCUserMemory.ino

Fix RTCmem example buffer access past end

---

libraries/GDBStub/library.json

Revert "Remove @PlatformIO library.json from GDBStub; fix pattern in LD"

---

libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp

ESP8266WiFi: zero-initialise scan_config structure

---

tools/platformio-build.py
tools/sdk/ld/eagle.app.v6.common.ld

* https://github.com/esp8266/Arduino/pull/4355
* https://github.com/esp8266/Arduino/pull/4356

Drop PlatformIO lines from LD script; append object suffix to the end of target name // Resolve #4355

---

doc/esp8266wifi/udp-examples.rst

fixed replyPakcet to replyPacket

---

doc/esp8266wifi/readme.rst

`Adruino` and a verb conjugation.

Two More Typos

---

cores/esp8266/HardwareSerial.h

HardwareSerial: one more duplicate test removed

---

libraries/SPI/SPI.cpp
libraries/SPI/SPI.h

minor fix, useful for some libs using it

spi: use const for output buffers

---

tools/platformio-build.py

Keep custom user flags passed via `build_flags`, such as a custom LD script

---

cores/esp8266/core_esp8266_wiring_digital.c

(this is #4873 proposed as three PR instead of a combined one)

fix scheduled interrupt #4609 by @shimarin

---

libraries/ESP8266httpUpdate/examples/httpUpdate/httpUpdate.ino

Adding a clue on the https part that you will definitely need the fingerprint. 
(My first commit, sry if it is noob)

https fingerprint clue

---

cores/esp8266/core_esp8266_wiring_pwm.c

allow analogWrite to pin 16

---

libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino

read all lines from slow servers

---

tools/platformio-build.py

See https://github.com/platformio/platform-espressif8266/issues/83#issuecomment-435051325

Use "PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY" as default lwIP profile for @PlatformIO

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

Set authmode in ESP8266WiFiSTAClass::begin if passphrase is provided.

Set authmode

---

tests/device/test_ping/test_ping.ino

Fix accidental horrible formatting in test_ping identified [here #5455](https://github.com/esp8266/Arduino/pull/5455#discussion_r240022457)

fix formatting for test_ping

---

platform.txt

Reverts #5433 until we figure out what's going on.

disable hard reset after flashing (reverts #5433)

---

package/package_esp8266com_index.template.json

Add Linux i686 (32bit) architecture toolchain

---

tests/device/.gitignore
tests/device/Makefile

also add test_BearSSL/data to .gitignore

fix lwip choice in tests/device Makefile

---

cores/esp8266/HardwareSerial.h

hardwareSerial: add missing include

---

tests/host/Makefile

use core's Schedule.cpp
fix list of core examples

host emulation fix

---

variants/inventone/pins_arduino.h

boards: Invent One: fix analog pin

---

tools/sdk/lwip/include/arch/cc.h

fix lwip-v1.4 compilation

---

libraries/esp8266/examples/SerialStress/SerialStress.ino

(Includes half-duplex patch for SerialStress.ino)

Update EspSoftwareSerial to release 5.0.0.

---

cores/esp8266/WString.cpp
cores/esp8266/WString.h

Add String::toDouble from upstream Arduino core

---

tests/host/core/test_string.cpp

Added the test for the SSO StreamString bug (#6035)

Test for StreamString SSO bug (#6035)

---

tools/makecorever.py

Fix default GIT_VER in makecorever.py

---

package/drop_versions.py

hide dropping message in json package file

---

tools/sdk/ld/eagle.app.v6.common.ld.h

Allow *.cc files to be linked into flash by default

---

tools/elf2bin.py

Fixes #6115 as found by @micjoc

Fix typo in elf2bin for QOUT binary generation

---

README.md
platform.txt

2.5.2 release completed, time for 2.6.0 work

Back to 2.6.0-dev

---

cores/esp8266/Schedule.cpp

per @dok-net review https://github.com/esp8266/Arduino/pull/6137#discussion_r287544074

schedule: fix linked-list 

---

cores/esp8266/Schedule.h

per https://github.com/esp8266/Arduino/pull/6182#issuecomment-505413580

recurrent scheduled functions: fix comment

---

libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer-impl.h

Fix trivial extra "\n" on web update success

---

libraries/ArduinoOTA/ArduinoOTA.cpp

Fixes: https://github.com/esp8266/Arduino/issues/6348

libraries: fixed no "OK" ACK for Signed Update

---

libraries/GDBStub/src/GDBStub.h

ensure consistency for gdb hooks signatures

---

libraries/SPI/SPI.h

Set SPI_HAS_TRANSACTION to 1

---

libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino

fix because of SoftwareSerial API change

minor fix in WiFiTelnetToSerial example

---

tests/device/Makefile

Remove typo in device test "make clean"

---

cores/esp8266/avr/dtostrf.h

increase include file compatibility with other architectures

---

README.md
platform.txt

Update platform to 2.7.0-dev, bump Readme to 2.6.0

---

package/build_boards_manager_package.sh

(fix) remove makecorever.py call in released version

---

boards.txt
tools/boards.txt.py

board nodeMCUv1: +led menu (2, 16)

---

libraries/ESP8266WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino
libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino

This is harmless for arduino, but it helps with emulation on host or PIO
[ref](https://gitter.im/esp8266/Arduino?at=5dcbecd9ea7d147cb36faee1)

minor: examples: reorder functions for declarations prior to call

---

README.md
platform.txt

Update platform to 2.7.0-dev, bump Readme to 2.6.1

---

libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h

per https://github.com/esp8266/Arduino/issues/6718#issuecomment-557804038
@jandrassy this a fix for 2.6.2
The API [change fix](https://github.com/esp8266/Arduino/issues/6701#issuecomment-549236044) is stil under consideration and will be discussed or addressed for core-2.7

fix api bug

---

boards.txt
platform.txt
tools/boards.txt.py
tools/platformio-build.py

- per https://github.com/esp8266/Arduino/pull/6724#issuecomment-556243781
- per https://github.com/esp8266/Arduino/issues/5784#issuecomment-557500450

switch to firmware 2.2.x-190703 by default

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

Per @AdrianEddy
Actually advance position to write at while looping

Fix pointer arithmetic

---

README.md
package.json
platform.txt

back to 2.7.0-dev

---

libraries/Servo/src/Servo.h

Define MAX_SERVOS to 12, like original Servo.h

---

cores/esp8266/core_esp8266_postmortem.cpp

Changed ets_putc to ets_uart_putc1 to better newline handling.

Updated stack offsets for postmortem stack dump.

---

cores/esp8266/core_esp8266_wiring_digital.cpp

per https://github.com/esp8266/Arduino/issues/7041#issuecomment-602249112 following #7044 @dok-net

esp8285: properly initialize available gpio as inputs

---

libraries/ESP8266WiFi/src/ESP8266WiFiGratuitous.cpp

fix memleak

---

cores/esp8266/core_esp8266_si2c.cpp
tests/ci/style_check.sh

- (some) core files are astyled
- ci was only checking `libraries/`
=> now everything is checked

CI: fix style checking

---

README.md
package.json
platform.txt

Back to dev

---

libraries/ESP8266mDNS/src/LEAmDNS_Helpers.cpp

Revert "Changing listen to listen the current iface only instead of 0 (#7217)"

---

README.md

Add FTP client/server lib link

---

libraries/ESP8266WiFi/src/CertStoreBearSSL.h

Add namespace to FS references in CertStore

---

README.md
package.json
platform.txt

back to core-3.0 dev

---

cores/esp8266/Updater.cpp

Updater MD5 cleanup on begin

---

tests/platformio.sh

This PR updates PlatformIO CI script according to the changes in the upcoming PlatformIO 5.0
cc @ivankravets

Update PlatformIO CI script

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

Sorry, I know it's little.  But it eats at me...

Fix message typo

---

doc/esp8266wifi/readme.rst

Add `WiFi Multi` documentation to `readme.rst`.

Add WiFi Multi to readme.rst

---

cores/esp8266/Schedule.cpp
cores/esp8266/Schedule.h

Add Copyright notice to Schedule.h

---

cores/esp8266/WString.cpp

Changed contructor to use strlen_P
Changed copy to use memcpy_P instead of memmove_P

PROGMEM compatibility changes to String

---

cores/esp8266/LwipIntf.cpp
cores/esp8266/LwipIntf.h

Added ESP32 compatible methods for setting/getting hostname

---

libraries/EEPROM/EEPROM.cpp

Fix typo in EEPROM debug message

---

libraries/ESP8266WiFi/src/include/ClientContext.h

ref: https://github.com/esp8266/Arduino/pull/7207#issuecomment-813104491

comments in `ClientContext::connect()`

---

doc/reference.rst

resolves https://github.com/esp8266/Arduino/issues/1634#issuecomment-819552760

doc: analogRead must not be called to frequently when WiFi is on

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

Fix a warning in libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

---

cores/esp8266/core_esp8266_waveform_pwm.cpp

Added IRAM_ATTR to _stopPWM() so that digitalWrite() would work inside ISR. Fixes #8043

---

cores/esp8266/WMath.cpp

ref: https://github.com/esp8266/Arduino/issues/8089#issuecomment-851404232

makeword: sync header and implementation

---

libraries/LittleFS/library.properties
libraries/Servo/library.properties

Ref: https://github.com/esp8266/Arduino/pull/8088#issuecomment-853711167
per @per1234 's suggestion

more of Use optimal bundled library name

---

platform.txt
tools/platformio-build.py

gnu source: honoring libc requirements

---

.github/workflows/release-to-publish.yml

Apply #8178 to the publish action, too.

Release 3.0.1

---

README.md
package.json
platform.txt

That was fun :]
Sorry for the noise on the mailboxes.
The release process should be stabilized for now.
(*edit*: there's no other way to debug a release process that to run it)
closes #8241

back to 3.1.0-dev after 3.0.2

---

libraries/ESP8266WebServer/examples/WebServer/secrets.h

Forgot to remove these (invalid now) in the example.

Update secrets.h to network and credentials

---

cores/esp8266/HardwareSerial.h
cores/esp8266/Print.h
libraries/ESP8266WiFi/src/WiFiClient.h
libraries/ESP8266WiFi/src/WiFiUdp.h

comments on Arduino flush() method

---

cores/esp8266/StreamString.h

This PR adds the missing "include" statements for #8366

Add stream string includes

---

libraries/ArduinoOTA/ArduinoOTA.cpp

Fix for https://github.com/esp8266/Arduino/pull/8379

Fix compilation of ArduinoOTA when no global MDNS is available

---

tools/platformio-build.py

Fix a bug when preprocessor flags are passed to the GCC AS.

Improve support for hand-written asm source files

---

tools/upload.py

fixup #8603, sys.exc_info is a function

upload.py should not always fail

---

tools/platformio-build.py

Expect that (key, value) can be (key,)
See https://github.com/esp8266/Arduino/commit/93537f94a88df86455ce884073cacc3ecafae227#comments

Fix CPPDEFINES loop

---

libraries/lwIP_Ethernet/library.properties
libraries/lwIP_w5100/library.properties

fix library name in library.properties

---

libraries/ESP8266WiFi/src/WiFiClient.h
libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h

This PR will fix this issue https://github.com/esp8266/Arduino/issues/8939

Add support WiFiClientSecure TCP KeepAlive

---

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h

The fix for https://github.com/esp8266/Arduino/issues/8941

Fix for occasional timeout issues

---

cores/esp8266/core_esp8266_main.cpp

With respect to [a more general proposal which deserves another title](https://github.com/esp8266/Arduino/pull/8949/commits/79beda7e6172c7bf088a7ac8401dfe4a5d5a42c2)
fixes #8947

fix delay(0)

---

cores/esp8266/LwipIntfDev.h

Ethernet styles getters/setters and WiFi styles getters/setters for DNS and MAC
I write about the motivation for this in the other [PR](https://github.com/esp8266/Arduino/pull/9021)

LwipIntfDev - add DNS IP getters/setters and MAC getters

---

cores/esp8266/LwipIntf.cpp

LwipIntf - fix minor typo

---

tests/host/sys/pgmspace.h

(while compiling gh/arduino-home-assistant)

emulation-on-host: +memcmp_P

---

tests/common.sh

Skip onewiretest in EspSoftwareSerial

---

tests/host/Makefile

echo does not seem to have escape mode with GH actions runner
trying to fix apparently broken makefile funcs from #9117

Mock - compatibility fix for shell calls

---

doc/esp8266wifi/station-class.rst

Documentation - fix links in station-class.rst

---

.readthedocs.yaml

https://app.readthedocs.org/projects/arduino-esp8266/builds/ fails since forever

Docs - readthedocs.io latest
