esp8266/Arduino

README.md
hardware/esp8266com/esp8266/boards.txt
hardware/esp8266com/esp8266/platform.txt
hardware/esp8266com/esp8266/programmers.txt

Remove the need to set programmer, by setting upload tool.

Remove the need to set programmer

---

hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.h

As available in http://www.arduino.cc/en/Reference/EEPROM
https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/libraries/EEPROM
EEPROM.get(address, data)
Read any data type or object from the EEPROM.
EEPROM.put(address, data)
Write any data type or object to the EEPROM.
Both functions return a reference to the object passed in.

Add get and put functions to EEPROM

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp
hardware/esp8266com/esp8266/cores/esp8266/Esp.h
hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.cpp
hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c

some new functions for ESP class, add includes to Arduino.h

---

hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c

strtok_r is never prototyped and the function directly above it references it.

Fix for undefined reference to strtok_r

---

hardware/tools/esp8266/sdk/ld/eagle.app.v6.ld

saves 3544 Byte in ram
see #104

move libm to flash (.irom0.text)

---

README.md
hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.cpp
hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.h

the register configurations has been computed like this:
```
#include <stdio.h>
int main(int argc, char **argv)
{
char t[24][4]={"5N1","6N1","7N1","8N1","5N2","6N2","7N2","8N2","5E1","6E1","7E1","8E1","5E2","6E2","7E2","8E2","5O1","6O1","7O1","8O1","5O2","6O2","7O2","8O2"};
char c;
int i;
for (i=0;i<24;i++)
{
c=0;
if (t[i][0]=='5') c+=0<<2;
if (t[i][0]=='6') c+=1<<2;
if (t[i][0]=='7') c+=2<<2;
if (t[i][0]=='8') c+=3<<2;
if (t[i][1]=='E') c+=2<<0;
if (t[i][1]=='O') c+=3<<0;
if (t[i][1]=='N') c+=0<<0;
if (t[i][2]=='1') c+=1<<4;
if (t[i][2]=='2') c+=3<<4;
printf("#define SERIAL_%s 0x%x\n", t[i],c);
}
return 0;
}
```

HardwareSerial: add other configs than 8N1

---

build/build.xml
build/windows/jre-8u31.zip.sha

Fix Windows build.
According to official Arduino build process now it is required to install JDK and point JAVA_HOME to it's location

Fix Windows build

---

app/src/processing/app/AbstractMonitor.java

This would be handy for those of us who wish to see the boot loader information in the IDE.

Add boot loader compatible speed of 74880 to serial

---

hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c

since there is no ets_strnlen, provide an implementation

strnlen implementation

---

README.md

This was not immediately apparent to me. I don't think it would be apparent to anyone else just playing around with ESP8266/Arduino either. GPIO16 and RST (REST) need to be tied together or you can "never wake from .deepSleep"
It must be GPIO16 and it must be RST, no other GPIO pin will wake it from deepSleep.

Ability to wake from .deepSleep

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClient.cpp

I found an slight incompatibility with the Arduino documentation for `WiFiClient::connected()`: http://www.arduino.cc/en/Reference/WiFiClientConnected
`WiFiClient::connected()` should return true if the connection is disconnected, but there is still data available.
Before this patch `WiFiClient::connected()` returned true when the connection was still there. I found this more intuitive, but the documentation sadly said otherwise.

ESP8266WiFi: made connected() return true if data is available

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring_digital.c
hardware/esp8266com/esp8266/platform.txt
libraries/OneWire/OneWire.h

fix bug #159

---

hardware/esp8266com/esp8266/libraries/EEPROM/examples/eeprom_clear/eeprom_clear.ino

pinMode was missed in eeprom_clear example.

Mode missed

---

hardware/esp8266com/esp8266/libraries/ESP8266WebServer/examples/SDWebServer/SDWebServer.ino

working fine with the latest wifi lib

add SD Card Web Server example

---

hardware/esp8266com/esp8266/libraries/ESP8266WebServer/examples/SDWebServer/SDWebServer.ino
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.h

GET params are always added
plain POST is added to the GET arguments
Uploads are handled by separate handler

add proper POST support and more methods add proper POST support and more methods 

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiUdp.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiUdp.h
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/include/UdpContext.h

Using connect() temporarily is incorrect, because any packet arriving for the listening port from another host while inside the beginPacket()/endPacket() bracket will be discarded.
Instead, remember the IP and port used in beginPacket(), and provide those as unicast destination when endPacket() calls send().
A better option would be to change beginPacket() to not take the destination, and make endPacket() take the destination, but this would break compatibility with the Arduino WiFi library.
This change also makes the size of each buffer created for buffering data 512 bytes instead of 1024. Most UDP datagrams are < 256 bytes in size, so this is a better trade-off for using on an embedded device.

Fix UDP send to not temporarily use connect()

---

hardware/esp8266com/esp8266/cores/esp8266/Print.cpp
hardware/esp8266com/esp8266/cores/esp8266/Print.h
hardware/esp8266com/esp8266/cores/esp8266/WString.cpp
hardware/esp8266com/esp8266/cores/esp8266/WString.h
hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c
hardware/esp8266com/esp8266/cores/esp8266/pgmspace.cpp
hardware/esp8266com/esp8266/cores/esp8266/pgmspace.h

PSTR() and F() macros correctly place string into flash memory relying
on PROGMEM
PROGMEM uses ICACHE_RODATA_ATTR
Print and String classes fixed up
str* classes fixed up

PgmSpace working

---

hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_noniso.c

Fix remainder to display leading zeros

dtostrf fix for remainder leading zeros

---

hardware/esp8266com/esp8266/variants/nodemcu/pins_arduino.h

see: https://raw.githubusercontent.com/nodemcu/nodemcu-devkit/master/Documents/NODEMCU_DEVKIT_SCH.png

NodeMCU: BUILTIN_LED is on GPIO16

---

build/.gitignore
build/build_board_manager_package.sh
hardware/esp8266com/esp8266/changes.md
hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.cpp
hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.h
hardware/esp8266com/esp8266/libraries/EEPROM/examples/eeprom_write/eeprom_write.ino
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp

ESP8266WiFi extended functions
begin changes
allow setting BSSID/MAC and Channel of an AP for faster connection (#261)
now checks if ssid and passphrase to big
selecting Wifi mode in better way (fix for #28)
ESP8266WiFiMulti uses the new functions to auto select best AP even in a multi AP WiFi network (more the one AP has same SSID)
add new functions to get current Connected AP:
uint8_t * BSSID(void);
int32_t Channel(void);
add new functions to get infos from scanned networks:
uint8_t * BSSID(uint8_t networkItem);
int32_t Channel(uint8_t networkItem);
bool isHidden(uint8_t networkItem);
bool getNetworkInfo(uint8_t networkItem, const char** ssid, uint8_t * encryptionType, int32_t * RSSI, uint8_t ** BSSID, int32_t * channel, bool * isHidden);

ESP8266WiFi extended functions

---

build/build_board_manager_package.sh
hardware/esp8266com/esp8266/boards.txt
hardware/esp8266com/esp8266/variants/adafruit/pins_arduino.h

In an attempt to reduce confusion about how to install support for ESP8266 boards, I was hoping to add the Adafruit HUZZAH ESP-12 breakout to the official ESP8266 community package index. That way we can drop the ESP8266 board from the Adafruit package and point people to the official version.
Let me know if that sounds good, and we can change documentation to point to your package index and drop the ESP package from our package index once these changes are deployed.
Thanks!

Add Adafruit HUZZAH ESP8266 (ESP-12 breakout) to Board Manager Package

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/Esp.h
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_timer.c
hardware/esp8266com/esp8266/tools/sdk/include/ets_sys.h

This timer is handy for lower level support like PWM/Servo work.
I also cleanup the *sync assembly instructions, some where not needed, others were needed in other places. The *sync should be used exclusively from each other, and in order of inclusiveness they are ISync, RSync, ESync, and then DSync. ISync includes the others.

Expose Chip CCompare0 timer

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h

added these defines because (for as far as i needed) the i2c liquid-crystal library needs these to function.
after adding the defines, the display could be spoken to using gpio-0 and gpio-2 (the bit-banged i2c :) )
library in question:
https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads
sketch is:
https://github.com/Duality4Y/Sketchbook/blob/master/sketchbook/HelloWorld_i2c_esp/HelloWorld_i2c_esp.ino

added NOT_ON_TIMER and digitalPinToTimer defines

---

README.md
hardware/esp8266com/esp8266/libraries/DNSServer/examples/DNSServer/DNSServer.ino
hardware/esp8266com/esp8266/libraries/DNSServer/library.properties
hardware/esp8266com/esp8266/libraries/DNSServer/src/DNSServer.cpp
hardware/esp8266com/esp8266/libraries/DNSServer/src/DNSServer.h

Hey guys,
I wanted to be able to connect to WiFi created by ESP8266 (softAP mode), enter a domain name in my browser (e.g. www.example.com) and have it hit webserver on ESP8266. I've also considered using mDNS library, but it doesn't work in AP mode.
So I decided to write a simple DNS server library. I've been testing it today and it's working fine, so I'm creating this pull request. Let me know what do you think and if you'd like to include it in your repo.

Added a DNSServer library

---

hardware/esp8266com/esp8266/libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino
hardware/esp8266com/esp8266/libraries/DNSServer/examples/DNSServer/DNSServer.ino
hardware/esp8266com/esp8266/libraries/DNSServer/library.properties
hardware/esp8266com/esp8266/libraries/DNSServer/src/DNSServer.cpp
hardware/esp8266com/esp8266/libraries/DNSServer/src/DNSServer.h

Added new feature - DNSServer can now be configured to reply to all requests with one IP address (e.g. for captive portal).
Improved initial example and added CaptivePortal example.

DNSServer can now be configured to reply to all requests with one IP address (e.g. for captive portal)

---

README.md

We've refactored the DHT sensor library so that it can run on faster processors like the ESP8266 automatically without any need to adjust cycle counts, etc.  This pull updates the README.md to note the latest library works as is, or to add the adjusted cycle count for the older library.
And sorry I'm using a new text editor that for some reason decided to remove a trailing space elsewhere.  I guess it's technically a fix to the docs too. :)

Documentation update: Clarify DHT sensor usage for latest DHT sensor library.

---

hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring_digital.c

I rewrote digitalWrite because the existing version was breaking
functionality as compared to how it behaves on the AVR.
Specifically, I could not use digitalWrite for a library that works fine on the AVR.
Instead I had to resort to fiddling with GPOC and GPOS and bit masks,
but this rewrite made all of that unnecessary, for whatever reason it
just works better.
This version borrows a little from the AVR library in the sense that the
same logic is applied to determine whether a pin should be high or low
as the AVR version, and yes, it does appear to make a difference, at least as far as my testing on hardware has shown.

digitalWrite cleanup and more compliant with behavior on AVR

---

README.md

Support was recently added to Adafruit's NeoPixel library for the ESP8266.  This is a small doc update to mention the library in the README.md.

Doc update to mention support in Adafruit's NeoPixel library.

---

hardware/esp8266com/esp8266/libraries/ESP8266httpUpdate/library.properties
hardware/esp8266com/esp8266/libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp

On Linux (presumably Mac too), the header of the library
could not be included, caps changed to match the filename.
The line 'architectures=ESP8266' in library.properties caused:
WARNING: library ESP8266httpUpdate claims to run on [ESP8266] architecture(s) and may be incompatible with your current board which runs on [esp8266] architecture(s).

httpUpdate: fix case sensitivity issues

---

README.md
hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/HardwareSerial.cpp
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClient.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiServer.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiUdp.cpp
hardware/esp8266com/esp8266/libraries/Wire/Wire.cpp
hardware/esp8266com/esp8266/tools/sdk/include/ets_sys.h

this introduces optimistic_yield() used for when standard library
methods are normally used in tight loops waiting for something to
happen, like available().
this replaces https://github.com/esp8266/Arduino/pull/545

optimistic_yield()

---

hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_si2c.c

The TCS34725 RGB color sensor works reliably with this change. See #535 for details.

NACK last byte when read

---

hardware/esp8266com/esp8266/cores/esp8266/pgmspace.cpp

This was lost in https://github.com/esp8266/Arduino/commit/80a5f29e89ebb48d2414edd75e1847c3f47798e4
I've also changed the type of src to PGM_VOID_P to match the other changes made in @Makuna 's PR.

Re-added lost function memcpy_P

---

hardware/esp8266com/esp8266/cores/esp8266/Arduino.h
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_timer.c
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring_digital.c
hardware/esp8266com/esp8266/cores/esp8266/interrupts.h
hardware/esp8266com/esp8266/libraries/Servo/src/esp8266/Servo.cpp
hardware/esp8266com/esp8266/tools/sdk/include/ets_sys.h

(https://github.com/esp8266/Arduino/issues/615)
Fixes issue of reentrant calls to nointerrupts() 
exposed functional replacements to cli sei and SREG when dealing with
interrupts
InterruptLock class to auto stop and restore interrupt level
Fix user ISR calls to be like Arduino with interrupts disabled fully.

Interrupt cleanup

---

hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c

I've copied the `strtol()` and `strtoul()` functions from newlib, the only change is how we access `errno`.
`strtod()` will no longer cause a crash when callers don't care about `endptr`.

libc_replacements: add strtol and strtoul from newlib, fix strtod

---

hardware/esp8266com/esp8266/cores/esp8266/Tone.cpp
hardware/esp8266com/esp8266/cores/esp8266/Updater.h
hardware/esp8266com/esp8266/cores/esp8266/cbuf.h
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_postmortem.c
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_si2c.c

Changed a few source files to remove compiler warnings when compiled under the Eclipse framework.

Made changes to allow the compiler to compile without warnings.

---

hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp

Minor mods:
Now makes only one call to .c_str() and using pointer tracking, rather that recalculating offset within the sending loop, to manage data window.
Moved invariant code out of the sending loop body.

Improvements to ESP8266WebServer::sendContent

---

hardware/esp8266com/esp8266/cores/esp8266/FS.cpp
hardware/esp8266com/esp8266/cores/esp8266/FS.h
hardware/esp8266com/esp8266/cores/esp8266/FSImpl.h
hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_noniso.c
hardware/esp8266com/esp8266/cores/esp8266/spiffs_api.cpp

fix dtostrf() issue using trackerj/odometer fixes along with my own fix for string null character ending

fix dtostrf() issue using trackerj/odometer fixes along with my own fix for string null character ending

---

hardware/esp8266com/esp8266/cores/esp8266/IPAddress.cpp
hardware/esp8266com/esp8266/cores/esp8266/IPAddress.h
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClient.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClient.h

I was tired to grab/merge this personal change from one version to the other.

add toCharArray() to IPAddress class

---

hardware/esp8266com/esp8266/libraries/DNSServer/src/DNSServer.cpp

DEBUG should be defined outside the library to enable it  not enabled by
default in library itself

Remove DEBUG defined by default in library

---

hardware/esp8266com/esp8266/boards.txt
hardware/esp8266com/esp8266/tools/sdk/ld/eagle.flash.4m1m.ld

- fix bug for 4M huzzah with 1M file system
- add 1M file system for generic 4M module
- add eagle.flash.4m1m.ld

fix bug for 4M huzzah with 1M file system  and add 1M file system for generic 4M module

---

hardware/esp8266com/esp8266/boards.txt

It have to be updated because of igrr's commit [9ae85d4](https://github.com/esp8266/Arduino/commit/9ae85d4a59ee15795bfc34817fe15eb11ded9b36).
I didn't know that the rest of the flash have to be empty.

fix upload size for gerneric 4m1m

---

hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.h
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClient.cpp

- add ESP8266WebServer::sendContent_P and ESP8266WebServer::send_P with size_t contentLength argument to allow binary content to be send, such as images.
- fix in WiFiClient::write_P to use memcpy instead of memccpy allow binary content to be send, such as images.

add ESP8266WebServer::sendContent_P and ESP8266WebServer::send_P with contentLength

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/include/ssl.h

This include is not used by ssl.h but can be annoying.
If there is need for time.h it should be located in the esp8266 tree.

Remove unused include time.h from ssl.h

---

hardware/esp8266com/esp8266/libraries/Servo/src/esp8266/Servo.cpp

Fixes #839 by initializing the `_minUs` and `_maxUs` fields to the defaults in the constructor.

Fix to Servo allowing write() to be called before attach()

---

hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.h
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/Parsing.cpp

If the client connection gets closed during a form upload,
the fileUploadHandler is notified with the new
UPLOAD_FILE_ABORTED status, and the loop is ended
gracefully.

Handle form upload abortion in ESP8266WebServer to fix Issue #833

---

hardware/esp8266com/esp8266/libraries/DNSServer/examples/CaptivePortalAdvanced/handleHttp.ino
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h

I changed the return type from SSID() last day.
Is it better to use the same return type for all overloaded functions?

use String return for both SSID functions

---

hardware/esp8266com/esp8266/platform.txt
hardware/esp8266com/esp8266/tools/sdk/include/c_types.h
hardware/esp8266com/esp8266/tools/sdk/ld/eagle.app.v6.common.ld

Related to #856, #826, #803, #734.
- enable -gc-sections linker option (#734)
- enable -ffunction-sections -fdata-sections (in conjunction with the above, helps with #826)
- fix #856 by making ICACHE_RAM_ATTR place functions into `.iram.text` instead of `.text`. Place `.iram.text` into `.text` segment via linker script. This allows to (selectively) place code into RAM from .cpp files *and* moves code from .c files into `.irom.text` by default (#803).
Reduces size of the sketches somewhat.
Without this change (HelloServer sample sketch):
Sketch uses 349,510 bytes (33%) of program storage space. Maximum is 1,044,464 bytes.
Global variables use 45,674 bytes (55%) of dynamic memory, leaving 36,246 bytes for local variables. Maximum is 81,920 bytes.
With this change:
Sketch uses 225,310 bytes …

Fix placement of code into RAM, enable gc-sections

---

hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp

The memccpy_P function returns the first byte after the last character written into the destination. The current implantation of sendContent_P uses pointer arithmetic incorrectly:
```C
contentUnitLen = contentNext - content;
```
The problem is that ```contentNext``` is relative to the destination, ```contentUnit```, but ```content``` is in ROM. As a result, the number of remaining bytes is complete wrong.
Oh, and this is covered by issue 864 that I filed.

Fixing final write length for sendContent_P

---

hardware/esp8266com/esp8266/libraries/ESP8266mDNS/ESP8266mDNS.cpp

Hi,
This pull request is about ESP8266mDNS, it add in the `update` method a check that _conn is not NULL before using it.
It allows to have a loop that always call it even when ESP8266mDNS is not still initialized.
Regards,
Michel.

avoid to dereference a NULL pointer if update is called before begin

---

hardware/esp8266com/esp8266/libraries/ArduinoOTA/ArduinoOTA.cpp
hardware/esp8266com/esp8266/libraries/ArduinoOTA/ArduinoOTA.h
hardware/esp8266com/esp8266/libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino
hardware/esp8266com/esp8266/libraries/ArduinoOTA/examples/OTALeds/OTALeds.ino
hardware/esp8266com/esp8266/libraries/ArduinoOTA/keywords.txt
hardware/esp8266com/esp8266/libraries/ArduinoOTA/library.properties

This work encapsulates the basic OTA functionality to an ArduinoOTA class.
It also adds callbacks for OTA events so the application can react. SPIFFS
support to come in next patches.

OTA support encapsulated to ArduinoOTA class

---

hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h

add dnsIP() to ESP8266WiFi class

add dnsIP() to ESP8266WiFi class

---

hardware/esp8266com/esp8266/libraries/DNSServer/src/DNSServer.cpp

This seems fix the Exception (28)/ (9) that occur on Captive portal with
Soft AP

Add _buffer initialization and some sanity check

---

hardware/esp8266com/esp8266/cores/esp8266/FS.cpp
hardware/esp8266com/esp8266/cores/esp8266/FS.h
hardware/esp8266com/esp8266/cores/esp8266/FSImpl.h
hardware/esp8266com/esp8266/cores/esp8266/spiffs_api.cpp

this allow to display total space and used space on SPIFFS

Add SPIFFS wrapper for info function

---

hardware/esp8266com/esp8266/libraries/ESP8266WebServer/examples/SimpleAuthentification/SimpleAuthentification.ino
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.h
hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/Parsing.cpp

based on @brianensor PR
+sample and some sanity check

Add header access using same method as arguments 2

---

hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs.h
hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_check.c
hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_config.h
hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_gc.c
hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_hydrogen.c
hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_nucleus.c
hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_nucleus.h

In a new staging version of this, we have to use the latest mkspiffs version with SPIFFS 0.3.3 which includes the pull request https://github.com/igrr/mkspiffs/pull/10

update SPIFFS to version 0.3.3

---

LICENSE

see:
```
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
```

add missing LICENSE file (GNU Library Public License, version 2)

---

libraries/EEPROM/library.properties
libraries/ESP8266httpUpdate/library.properties
libraries/Hash/library.properties
libraries/SPI/library.properties
libraries/Ticker/library.properties
libraries/Wire/library.properties

Since Arduino 1.5.6, the `category` library metadata is implemented (see https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format).
Making the libraries 1.5 compliant removes the warnings generated for those of us who are using arduino-builder (e.g. `WARNING: Category '' in library EEPROM is not valid. Setting to 'Uncategorized'`).

Add libraries categories

---

README.md
doc/ota_updates.md

add first docu for OTA

---

doc/ota_updates.md
libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
libraries/ESP8266WiFi/src/ESP8266WiFi.h
libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

Fix FAILD typo

---

cores/esp8266/Arduino.h
cores/esp8266/time.c

Some fixes for time.c
declare timezone as long
call sntp_setservername() with server id

Updates for time.c

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp

The terminator should not be sent by sendContent_P. For example, if you
have a null-terminated string, the null itself should not be sent to the
client. This change decrements the number of bytes to send so it does
not include the termination character. This is for Issue #987

Exclude the terminator in sendContent_P

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h

Try number two: 
As discussed in https://github.com/esp8266/Arduino/issues/999
Allow serving of static SPIFFS files with a cache-control header.  Defaults to nothing, so existing sketches are not broken.  Takes a const char * but is stored as string. 
Also added the ability to serve gz files, and directories.  The handler will serve the original file first if present, then the gzipped one.  Directories can also be served statically with the same rules.  
Examples
```
// serves all SPIFFS with 24hr max-age control
HTTP.serveStatic("", SPIFFS, "","max-age=86400"); 
```
```
// serves all of server directory with no-cache
HTTP.serveStatic("/server", SPIFFS, "/server", "no-cache"); 
```

Changes to static request handler

---

boards.txt

I added the "Reset Method" for some custom esp8266 modules "nodemcu like" but has only 512K or 1M flash.

add menu "Reset Method"

---

doc/boards.md

add documentation about boot messages and mode meaning

---

cores/esp8266/core_esp8266_postmortem.c

Attempt to address #1011.  Feedback is desired, because it's not the cleanest code.
Caveats:
- Be very careful in your callback.
- Will only actually get called for Exceptions and Soft WDT resets.

Add the ability to be called back when the device is about to reset

---

libraries/ESP8266httpClient/src/ESP8266httpClient.cpp
libraries/ESP8266httpClient/src/ESP8266httpClient.h

change deconstruct call to delete

add url phasing for begin

---

cores/esp8266/core_esp8266_wiring_digital.c

current implementation can cause false readings if previous handlers
take more time than the pin holds the level

Get pin levels at point of interrupt

---

cores/esp8266/core_esp8266_features.h

add core_esp8266_features.h to be able to detect the features and librarys included in the ESP core

core_esp8266_features.h to detect the features and library

---

libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino

Since many users on the forum complained that the example was not running due to the fact that delay(10) wasn't enough for some slow servers, I'm proposing this change.

replace delay() with a while loop in WiFiClient.ino

---

cores/esp8266/pgmspace.h

The two defines used reinterpret_cast<> which is only available when
compiling with c++. Now using plain old c casts instead.

Make pgm_read_byte() and pgm_read_word() usable from c.

---

cores/esp8266/HardwareSerial.cpp
cores/esp8266/cbuf.h

This avoids a race where the interrupt handler detects an empty _tx_buffer just before we write data into it.
Note that commit d6f62943d4b511e7d5fe6147096c8979890416f5 works around this race when data is continually added to _tx_buffer in the hung state (but is not helpful when there is not new data being added).  This reverts that change here as the race should no longer occur.
Testing performed:
- set UART_CONF1.txfifo_empty_thrhd=0x70 (which exacerbates the issue)
- generate a ~240 byte burst of data, sent in back-to-back Serial1.write(, 4) calls, optionally followed by a Serial1.flush()
Test results:
- before this change, observe occasional unsent data and hang in flush() (when called).
- after this change, data is sent as expected.

Always arm the "TX FIFO Empty" interrupt after we write into _tx_buffer.

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266WiFi/src/WiFiServer.cpp
libraries/ESP8266WiFi/src/WiFiServer.h

fix #1167 WiFiServer stop / close

---

README.md

Hi @igrr,
Would be thankful to place some information about [PlatformIO](http://platformio.org) as alternative cross-platform builder to use ESP8266 core for Arduino on the popular host OS: Mac OS X, Windows, Linux 32/64, Linux ARM (like Raspberry Pi, BeagleBone, CubieBoard).
Don't hesitate to modify this PR.
Thanks in advance!

Add PlatformIO as alternative option to use ESP8266 core for Arduino

---

libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

allow control of restart on http update

---

boards.txt

The Sparkfun ESP8266 Thing Dev board currently has the "upload.resetmethod" set to "ck" which is invalid for the hardware, which uses the "nodemcu" reset circuitry.  You can compare the reset circuits here: https://cdn.sparkfun.com/datasheets/Wireless/WiFi/ESP8266-Thing-Dev-v10.pdf and https://raw.githubusercontent.com/nodemcu/nodemcu-devkit/master/Documents/NODEMCU_DEVKIT_SCH.png
Sparkfun: 
Node MCU:
Without this change, the Thing Dev board will not program correctly unless it is power cycled with GPIO0 held to ground.  After this change, the board resets, programs, and runs correctly, without any manual jumper or reset operations.

Modify boards.txt for Sparkfun Thing Dev

---

libraries/ESP8266HTTPClient/examples/ReuseConnection/ReuseConnection.ino
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h

- HTTP Client move buffer (1460 Byte) from stack to heap.
- only malloc needed ram if we know the response size and its less then 1460

HTTP client move stream buffer the heap 

---

libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
libraries/ESP8266WiFi/src/ESP8266WiFi.h

It was hard-coded to "config.show_hidden = 0;"

add show_hidden argument to scanNetworks()

---

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

Conveniently skips ':' inside copied/pasted SHA signatures from web browser and avoids "non matching" signatures...

Skip ':' inside SHA1 signatures in WiFiClientSecure.cpp . 

---

libraries/Servo/src/esp8266/Servo.cpp

detaching could leave a running timer which would cause issues.
Further, detaching could truncate the last pulse causing a invalid
movement.
This change moves detaching into the ISR so it can maintain the last
pulse and not start any more timers if not needed.

Fix detach and attach

---

cores/esp8266/Updater.cpp
cores/esp8266/Updater.h
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

- setMD5 has now returns bool
- handle setMD5 failed in HTTP update
- reset UpdaterClass when MD5 check failed
see: #1244

fix #1244 - MD5 handling

---

cores/esp8266/Updater.cpp
cores/esp8266/Updater.h

Note: only check of first 0xE9 possible.

add magic byte check for Update class

---

cores/esp8266/core_esp8266_phy.c

"init_data", when non-NULL, is on the heap, and the register_chipv6_phy call
sometimes modifies data in (at least) the offset range [128:249], suggesting
that it is a buffer larger than 128 bytes in size (the size of our
"phy_init_data" buffer).  When we use our static buffer (prior to this
change), the call could would overwrite the .rodata section and lead to
undefined behaviour.
To address this, just patch the heap-allocated buffer with our data.
Move phy_init_data to flash as it's now readonly and never modified.

Fix RAM corruption caused by our hook of register_chipv6_phy(init_data*)

---

cores/esp8266/StreamString.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

Calling HTTPClient->getString() would call writeStream and this report back a short write on success because StreamString returns 0 on success.

handle short writes

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

@alltheblinkythings brought up a good point in #1289.  Hopefully this will address it.

better bytesWritten accounting in sendRequest and writeToStream

---

boards.txt

Changed default WifInfo boards speed to 160MHz instead of 80MHz

Set default WifInfo board speed to 160MHz

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h

Added method to set TCP timeout for connect on HTTP requests. Not sure if its worth allowing this to be set at runtime though, but it was useful in one of my own projects.

Allow setting TCP timeout

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp

The character buffer protoName, created on the stack in the function MDNSResponder::_parsePacket(), is uninitialized. It can remain uninitialized all the way to the bottom of that function, where it is passed to the function MDNSResponder::_reply. 
In MDNSResponder::_reply, the pointer passed in is named 'proto'.  You will will find these lines of code near the top of that function...
//build proto name with _
char protoName[5];
os_strcpy(protoName,underscore);
os_strcat(protoName, proto);
size_t protoNameLen = 4; 
You can see there that if proto points to an uninitialized character buffer on the stack, the strcat call can blow way the stack.
I was getting random crashes when a client tried to connect to my esp8266 server using the 'server.local' host name. Those crashes have disappeared …

Fixed crash bug with mDNS

---

cores/esp8266/HardwareSerial.cpp
cores/esp8266/HardwareSerial.h
cores/esp8266/cbuf.cpp
cores/esp8266/cbuf.h
cores/esp8266/interrupts.h
libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266WiFi/src/WiFiServer.cpp

After SDK 1.5, libraries like NeoPixelBus which use the UART to generate timing signals stopped working correctly (logic analyser shows large intercharacter delays) as well as experiencing crashes in the IRQ handler.  This series of commits should up many of these issues.

Fixes for poor HardwareSerial performance/crashes exacerbated by SDK1.5

---

libraries/ESP8266WiFi/src/ESP8266WiFi.h
libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp

add more debug to WiFi and rework AP config to get DHCP in best mode if SDK config got invalid

add more debug to WiFi and rework AP config

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

Http Client isn't appropriately validating the presence of an uri scheme.

Fix typo causing crash on missing uri scheme

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp

This is needed since when the content-length header is not sent the clients will
wait for data anyways. Sending a content length of zero will tell the client not
to expect any content and it will close the connection immediately.
Since size_t is unsigned, checking if the content-length is >=0 seems redundant.

A content length of zero should also be sent

---

libraries/Ethernet/library.properties
libraries/OneWire/library.properties
libraries/SD/library.properties
libraries/Servo/library.properties

Use unique name values in library.properties for the esp8266 libraries
that are also Arduino IDE Built-In libraries. This solves the issue of
SD and Servo libraries always appearing as Type: Updatable in the
Arduino IDE 1.6.6 Library Manager when an esp8266 board is selected.

Unique Built-In libraries library.properties name

---

libraries/ESP8266WiFi/src/WiFiClient.h

Arduino.h defines min/max which are then redefined with templates in stl_algobase.h imported from memory.h.  This is the least impactful way I can find to get past this for now and unblock use of wificlient in more scenarios.
I haven't yet figured out how this is sometimes working just fine in simple scenarios, but very often any use of WifiClient.h will make it impossible to compile due to conflicting with the other definitions of min/max.
I'm using IDE 1.6.7.  This unblocks use of WifiClient and WifiSecureClient successfully for me and shouldn't have negative impacts.

Include Arduino.h AFTER memory.h

---

cores/esp8266/HardwareSerial.cpp
cores/esp8266/HardwareSerial.h

Second attempt after fixing my local branch mess

Allow setting alternate TX for UART 0, so GPIO1 is available as SPI_CS1

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h

If there is a delay before data becomes available on a new connection
then the handler function blocks for up to 1 second, and there's another
wait on connection close for up to 2 seconds.
This doesn't make the whole server process asynchronous (there is another
delay between headers/data) but it helps when there are other events
that need attention while handling web requests.

WebServer: handle initial read/close timeouts asynchronously

---

tools/espota.py

With python 3.5 (default on Arch linux) I got the following:
```
Traceback (most recent call last):
File "espota.py", line 318, in <module>
sys.exit(main(sys.argv))
File "espota.py", line 313, in main
return serve(options.esp_ip, options.host_ip, options.esp_port, options.host_port, options.auth, options.image, command)
File "espota.py", line 95, in serve
sent = sock2.sendto(message, remote_address)
TypeError: a bytes-like object is required, not 'str'
```
This patch will fix the error. Tested with python 2.7.11 and 3.5.1.

make espota compatible with python 3.5

---

libraries/Servo/src/esp8266/Servo.cpp

Values that were written and then read would be different due to using
map.
If user defined a different min/max pulse width would cause the
read/write to incorrectly calculate the pulse width.

Servo value read and write fixes

---

tools/espota.py

Sadly I didn't use authentication for ArduinoOTA so far. When I tried it turned out that it doesn't work with python 3.5...
```
Traceback (most recent call last):
File "/home/bitn/.arduino15/packages/esp8266/hardware/esp8266/2.0.0/tools/espota.py", line 318, in <module>
sys.exit(main(sys.argv))
File "/home/bitn/.arduino15/packages/esp8266/hardware/esp8266/2.0.0/tools/espota.py", line 313, in main
return serve(options.esp_ip, options.host_ip, options.esp_port, options.host_port, options.auth, options.image, command)
File "/home/bitn/.arduino15/packages/esp8266/hardware/esp8266/2.0.0/tools/espota.py", line 107, in serve
cnonce = hashlib.md5(cnonce_text).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
Fixed the error and tested with python 2.7.11 and 3.5.1 as …

espota: fixed remaining python 3.5 incompatibility

---

cores/esp8266/HardwareSerial.cpp
cores/esp8266/HardwareSerial.h
cores/esp8266/uart.c
cores/esp8266/uart.h
tests/common.sh

Based on changes proposed by @me-no-dev in #1485.
Implemented missing `peek` function.
Also did some cleanup and separated `uart_` functions into a separate file.
The only hardware-dependant thing in HardwareSerial.h is the following line in `available()` method:
```c++
optimistic_yield(USD(_uart_nr) / 128);
```
This can be rewritten via `uart_get_baudrate`, but that would incur an integer division, which is costly on the ESP8266. Another option is to add a getter in UART HAL, which would return the value of `USD`. However i have no idea how to call that method (i.e. `uart_get_WHAT(uart_t*)`?).
I have also taken liberty to reformat both affected files with `astyle --style=otbs`. Going further, this is the style I want to enforce for all source files, so please adjust your editors :)

HardwareSerial without software buffer and interrupts

---

doc/libraries.md

Add Paul Stoffregen's OneWire-library and (originally bbx10's) port of the Adafruit PCD8544 - lib to the collection of tested and compatible libraries.

More ESP8266-compatible libraries

---

boards.txt

SparkFun has two similar boards the 'Thing' and the 'Thing Dev'. The 'Thing' board settings wouldn't program my Thing Dev so I tired settings from about halfway down this tutorial: https://learn.sparkfun.com/tutorials/esp8266-thing-development-board-hookup-guide/setting-up-arduino which worked for me so I made this pull request to add a new configuration for the Thing Dev.
The thing I'm least sure about is reverting 3a16bed4c2cd88d15521474ccde0f4752e58eb31 putting the `upload.resetmethod` for the original board back to `ck`, I can't find any information on what the setting is supposed to be however the documents ([Thing Dev Schematics](https://cdn.sparkfun.com/datasheets/Wireless/WiFi/ESP8266-Thing-Dev-v10.pdf) and [NodeMCU DevKit …

Add a new board entry for the SparkFun Thing Dev

---

cores/esp8266/MD5Builder.cpp

I'm assuming that `sprintf` writes trailing `0` which is beyond buffer end.

Fix buffer overflow and formatting

---

cores/esp8266/spiffs/spiffs_nucleus.c
cores/esp8266/spiffs_api.cpp

Noticed that `ets_printf` doesn't parse %i which makes debug output useless.

Change %i to %d for ets_printf compatibility

---

cores/esp8266/core_esp8266_si2c.c
cores/esp8266/twi.h
libraries/Wire/Wire.cpp
libraries/Wire/Wire.h
libraries/Wire/keywords.txt

Use Wire.setClockStretchLimit(limit)
limit is in uSeconds

Configurable I2C clock stretching limit

---

doc/libraries.md

mDNS queries and responses on esp8266. Or to describe it another way: An mDNS Client or Bonjour Client library for the esp8266.

Add esp8266_mdns to libraries.md

---

doc/libraries.md

This library let you control electronic dimmable ballasts for fluorescent light tubes remotely as if using a wall switch.

Added DImSwith to "Other libraries (not included with the IDE)"

---

doc/libraries.md

TickerScheduler library - to simplificate Ticker usage and avoid WDT reset

TickerScheduler library link

---

cores/esp8266/Tone.cpp

I needed to use tones on the ESP so I've made an implementation of this base library. Some notes:
- it uses timer 1
- it only currently supports one pin, though it would be quite simple to support two by using timer 0 but I haven't looked at that yet. (the standard library only supports one pin)
- I've tested it with a logic analyser and the frequency looks good
Let me know if it looks OK to you.
Cheers,
Ben

Implementation of Tone library using timer1

---

cores/esp8266/abi.cpp

This pull request adds implementation of libsupc++ functions which are used by gcc to protect local static initializers.
Interrupts are disabled for the duration of static initialization. This is not ideal, but i don't see a way to implement this without disabling interrupts. Imagine the following scenario:
```c++
int first_millis() {
static int x = millis();
return x; 
}
void isr_handler() {
first_millis();
}
void setup() {
attachInterrupt(0, &isr_handler, CHANGE);
delay(10);
Serial.println(millis() - first_millis());
}
void loop() {
}
```
Let's consider the case when `first_millis` is called from `setup` first, and GPIO interrupt happens at the point when `millis` is being executed. Execution context is switched to `isr_handler`, which calls `first_millis` again. …

Static initialization guards implementation

---

.travis.yml
libraries/ESP8266WiFiMesh/examples/HelloMesh/HelloMesh.ino

Let's see if we can build all the sketches using the latest Arduino software.
Triggered by https://github.com/arduino/arduino-builder/issues/68#issuecomment-179664401.

Use hourly Arduino builds on Travis

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h

speed up WiFi.hostByName when the hostname is actually a IP.

speed up WiFi.hostByName when the hostname is actually a IP.

---

ISSUE_TEMPLATE.md

hopefully we get better Issues from this.

add ISSUE_TEMPLATE.md

---

cores/esp8266/WString.cpp

Calling `String::reserve(0)` causes a crash if String object is in invalidated state. Per the comment on the method's declaration in WString.h, `reserve(0)` would validate the string object but in fact it just causes a crash instead of recovering from invalidated strings.
This change fixes the edge case bug in `String::changeBuffer()` which is the root cause of the crash exposed from `String::reserve()`.
Following test code was used to reproduce the problem and also to validate the fix:
```c++
String result;
while(true){ // suppose this is a loop which reads data from a web page.
char c = 'A'; // suppose this is a byte read from client.
result += c; // the loop will eventually cause malloc() to fail here
if (result.c_str()==0) // even if we detect this
{
Serial.println("String …
```

Fix a crash in String::changeBuffer()

---

platform.txt
tools/sdk/include/user_interface.h

Include libwpa2 to enable WPA2-Enterprise (EAP-TLS only). Note that there are some function prototypes missing in the espressif sdk (v1.5.2), that need to be patched in order to overwrite the default identity ('espressif').
For testing, see https://github.com/joostd/esp8266-eduroam/tree/master/ansible. That project targets a specific Wifi network (eduroam), but the test setup is generic.

Enable WPA2-Enterprise

---

cores/esp8266/WString.cpp

realloc() can be a better alternative to doing malloc() followed by strcpy(). It may reduce memory footprint of concatination operation (when consecutive memory blocks are available for allocation extension).

Leverage realloc() in String::changeBuffer()

---

libraries/esp8266/examples/TestEspApi/TestEspApi.ino

Wrote a little code to exercise the C API, using the CallSDKFunctions example as a starting point. It doesn't exercise every last function, but is helpful for learning how the C API works.

Add TestEspApi example, exercising the non-RTOS C API.

---

.travis.yml
tests/common.sh
tests/host/Makefile
tests/host/common/Arduino.cpp
tests/host/common/Arduino.h
tests/host/common/WMath.cpp
tests/host/common/catch.hpp
tests/host/common/pgmspace.h
tests/host/common/pins_arduino.h
tests/host/common/spiffs_mock.cpp
tests/host/common/spiffs_mock.h
tests/host/fs/test_fs.cpp
tools/build.py

Initial batch of host testing mocks and some filesystem tests

---

cores/esp8266/umm_malloc/umm_malloc.c

(endless reboot) like:
```
Fatal exception (28):
epc1=0x402097e8, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000001, depc=0x00000000
Fatal exception (28):
epc1=0x402097e8, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000001, depc=0x00000000
Fatal exception (28):
epc1=0x402097e8, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000001, depc=0x00000000
```
```
0x402097e8: umm_info at umm_malloc/umm_malloc.c line 1000
```

fix umm_malloc null ptr.

---

boards.txt

Error during compilation on Arduino IDE require debug port and debug level.
So, set both parameter to <ิblank> to solve that problem.

Update boards.txt for ThaiEasyElec's ESPino

---

.travis.yml
tests/common.sh

This pull request adds sketch size reports at the end of CI build logs.
Intended use is to see how a given pull request affects flash/RAM usage.

Size reports for CI builds

---

cores/esp8266/Tone.cpp

Bugfix: the `duration` parameter should be optional, per [`tone()`](https://www.arduino.cc/en/Reference/Tone) docs.

Allow indefinite duration for `tone()`

---

libraries/SPI/SPI.cpp

Add CPOL setting thus supporting SPI MODE 2&3.

add CPOL setting

---

libraries/DNSServer/examples/CaptivePortalAdvanced/handleHttp.ino

fix for #1718: CaptivePortalAdvanced example doesn't call setContentLength

CaptivePortalAdvanced fix #1718

---

cores/esp8266/IPAddress.cpp
cores/esp8266/IPAddress.h

By moving the definition from the header to the source we now only use
one instance for the entire app with a little saving in space.

Avoid multiple instances of INADDR_NONE

---

cores/esp8266/core_esp8266_wiring_pulse.c

#1072 
#1149
- fix return value on timeout
- add optimistic_yield to allow WiFi/network tasks to run
- use ccount instead of micros (which causes an integer division on every call)

Fix pulseIn

---

libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino

Changed timeout to unsigned long. Using addition with millis() is not recommended. 
Source: http://www.gammon.com.au/millis

Changed timeout logic in wificlient example

---

doc/libraries.md

This library has been working well with Arduino for ESP8266 and it deserves to be added here.

Added Fast LED library to the list of supported libraries

---

doc/filesystem.md

added fopen modes for easy reference
Source:http://man7.org/linux/man-pages/man3/fopen.3.html

added descriptions for fopen modes

---

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp

An empty passphrase string should enable AUTH_OPEN mode of softAP.
This was the behaviour before commit 293e55c.
Additionally make the type of checking for empty strings consistent.
Fixes #1861

Re-enable old behaviour if passphrase string is empty

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

In WPA protocol, the maximum length of the passphrases is 64 characters in order to distinguish them from the actual PSK which is 64 ASCII characters long, so in most systems if a 64 chars string is passed, it is assumed to be a PSK, otherwise is treated as a passphrase and is used to compute the PSK.

Allow PSK instead of passphrase in WiFiSTA::begin

---

libraries/SPI/SPI.cpp

SPICWBO set means we should do LSB first.

Fix SPI.transfer16() using wrong endianness

---

libraries/ESP8266HTTPClient/library.properties
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h
libraries/ESP8266httpUpdate/library.properties
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

With this change, TLS support is linked into the final program only when certain overloads of HTTPClient::begin are used. Using an overload which does not take certificate fingerprint will save approximately 5k of DRAM.
Fixes #1855.

HTTP Client library: decouple TLS handling

---

libraries/SPI/SPI.cpp
libraries/SPI/SPI.h

The old code kept re-writing fifo's contents over and over and over every iteration, both with data from MISO and then with the supplied data -- this new version writes fifo's contents only once, disables it from being overwritten by data from MISO and as such also skips on writing its contents over and over again with supplied data.
This results in major speed-ups in anything that uses writePattern(), like e.g. with @Links2004 's ILI9341-library there's about a 54% speed-up in fill-screen and anything from 30%-50% speed-up with anything else that uses writePattern() behind-the-scenes.

Speed up SPI.writePattern()

---

tools/get.py

This is working for me on python 3.5. I couldn't quickly find the problem with the ascii encoding and stripped it. This may require a second look.

Python 3 compatibility

---

libraries/ESP8266SSDP/ESP8266SSDP.cpp

They are in the wrong order - `_ssdp_packet_template` expects `_uuid` to be before the NT/ST header.

Switch sprintf arguments in SSDPClass::_send around

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

Host: is supposed to include a port when it is not one of the standard ones (80, 443).

Include non-standard ports in HTTPClient's Host header

---

cores/esp8266/abi.cpp

I am having trouble using std::string in a library on esp8266. Following the advice here: https://github.com/esp8266/Arduino/issues/1136#issuecomment-162331360 I got most of the way but I am still getting linking issues looking for this function.

Added __throw_out_of_range

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

ESP8266HTTPClient can't process HTTP header which has no white space after `:`.
A header, `Content-Length:1234` makes `234`.
Some implementation of HTTP server returns HTTP header which has no white space.

Support HTTP header without white space.

---

cores/esp8266/core_esp8266_si2c.c
cores/esp8266/twi.h
libraries/Wire/Wire.cpp
libraries/Wire/Wire.h

I2C slave might stil have something to send when ESP826 starts I2C, thus
keeping the bus stuck. 
Happens e.g. when power failure/reset during transmission.
Thanks to work of drmpf there is a solution.
Implemented as separate method (Wire.status()) so as not to interfere with existing.
Method (status)returns one of the five statuses. 0 or I2C_OK is ok. 
Other status codes are for hanging SCL or hanging SDA 
Usage: 
```
Wire.begin();                                 //like normal
if (Wire.status() != I2C_OK) 
Serial.writeln(error_msg);                 //Something wrong with I2C bus 
//that cannot be recovered. 
//Perform power cycle 
//or search for other masters on bus;
```

I2C bus reset with status info to user, re issue 1025

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp

Ignore unknown records (AAAA) in query responses sent by avahi; this way we can extract
the IPv4 address and connect to the server.

Fix #2015 ESP8266mDNS doesn't accept queryService responses from avahi

---

libraries/Ethernet/examples/udpntpclient_pedantic/RFC1305.h
libraries/Ethernet/examples/udpntpclient_pedantic/UdpNtpClient_Pedantic.ino
libraries/Ethernet/examples/udpntpclient_pedantic/readme.txt

I have modified the classic UdpNtpCLient sketch by adding the structure of the Ntp data packet (as described in RFC1305) and referring to fields within the structure.
My objective is to encourage the writing of code easier to maintain, especially by someone other than the original author.

UdpNtpClient rewritten in a clearer, more pedantic fashion.

---

cores/esp8266/core_esp8266_main.cpp

GCC for Xtensa LX106 generates constructor sections names in inverse order. 
The link script in tools/sdk/ld/eagle.app.v6.common.ld is also designed to create an __init_array in inverse order.
So we must traverse that array starting from the end.

Fix init array order

---

boards.txt
platform.txt

- Changed WifInfo defaults settings
- Changed WeMos defined board name not to be ESP8266_NODEMCU but WEMOS_D1_MINI and WEMOS_D1
- Added board name defined symbol at compilation stage to have it available in sketch, MDNS and OTA using ARDUINO_BOARD (like in [ESP8266mDNS.h](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/ESP8266mDNS.h#L51))
This avoid board name to be "generic" in case of known board

Real board name available in Sketch/MDNS/OTA

---

cores/esp8266/Schedule.cpp
cores/esp8266/Schedule.h
cores/esp8266/core_esp8266_main.cpp
tests/device/test_schedule/test_schedule.ino

As mentioned in #1064.
This pull request adds two functions:
`bool schedule_function(std::function<void(void)> fn);`
May be used to run given function next time `loop` function returns, or `run_scheduled_functions` is called. `std::bind` may be used to pass arguments to a function, or call a class member function.
void run_scheduled_functions();
Runs all scheduled functions. This function may be used if `loop` is not being used, or it does not return on a regular basis (i.e. there an explicit loop somewhere in `setup` or in library code).
TODO:

Add mechanism for posting functions to the main loop

---

libraries/ESP8266WiFi/src/WiFiServer.h

Without this line compiler complains about :
Warning		22:9: warning: deleting object of polymorphic class type 'WiFiServer' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]		\\Mac\Home\Documents\Visual Studio 2015\Projects\BlinkESP8266_12\ActAsWiFi_server\SVServer.cpp	22
Reason for this is that I would like to init WiFiServer with port which can by dynamically chosen (for example by serial port)
internalServer = new WiFiServer(port);

Add virtual destructor to WiFiServer class

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h
libraries/ESP8266WiFi/src/ESP8266WiFiType.h

Related: #2026.
This commit changes the API for subscribing to WiFi events.
Currently there are two functions: `WiFi.onEvent` and `WiFi.removeEvent`. The first one allows one to listen to WiFi events but doesn't pass along any useful information about the event. Then other one has a bug and doesn't work in some cases.
Proposed changes are as follows:
- `WiFi.onEvent` is kept but marked deprecated. It should not be used in new code.
- `WiFi.removeEvent` is removed.
- A bunch of new functions are added:
```c++
WiFiEventHandler onStationModeConnected(std::function<void(const WiFiEventStationModeConnected&)>);
WiFiEventHandler onStationModeDisconnected(std::function<void(const WiFiEventStationModeDisconnected&)>);
WiFiEventHandler onStationModeAuthModeChanged(std::function<void(const …
```

WiFi event handling refactoring

---

cores/esp8266/MD5Builder.cpp
cores/esp8266/MD5Builder.h

We found an issue with the MD5Builder::addStream method. 
If len > filelength handled a false hash was calculated. Refactored for better readability.  
Tested with a filestream resulted in calculating the correct hash.

MD5Builder::addStream: fixed falsy calculated hash for len > filelength

---

libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

- use WiFiClient::stop in WiFiClient::stopAll to make behaviour overridable
- clean up ClientContext pointer used by axTLS when WiFiClientSecure::stop is called

Fix for crash in WiFiClientSecure when WiFi is disconnected

---

cores/esp8266/spiffs_api.cpp
tests/host/fs/test_fs.cpp

Same as #1819 but with test case fixed.

Fix SPIFFS.openDir("")

---

cores/esp8266/Arduino.h
cores/esp8266/WMath.cpp
tests/device/test_random/test_random.ino

As discussed in #1710.
- Initially from startup, `random(howbig)` and `random(howsmall, howbig)` functions will return values from HW PRNG.
- If `randomSeed` is called, these functions will switch back to software PRNG to maintain compatibility with standard Arduino behaviour.
- Two new functions are added, `secureRandom(howbig)` and `secureRandom(howsmall, howbig)` — these always return values from HW PRNG and don't depend on `randomSeed` calls.

Bring back old semantics to random and randomSeed, add secureRandom

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h

Fix ESP.getSketchSize, add ESP.getSketchMD5

---

cores/esp8266/uart.c

`rx` and `tx` were mixed up in a few places.

Fix UART pins setting (#2098)

---

cores/esp8266/spiffs_api.cpp

Since heap is so precious on this chip, I though this might be of use. Most applications I write don't need more then 1 file open simultaneously.

added macro for max open SPIFFS files, setting it to 1 saves about 1k heap

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClient.h
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266WiFi/src/include/ClientContext.h
libraries/ESP8266WiFi/src/include/DataSource.h

Another attempt to do the same thing as in #1570.
`WiFiClient::write` used to block for every call until data was acknowledged by remote side. This also meant that for a series of `WiFiClient::write` or `WiFiClient::print` calls, each call would actually invoke tcp_output to send data and wait for acknowledgement, making the whole process really slow. Also with that design `WiFiClient::setNoDelay` didn't have any effect — because Nagle algorithm was never used in the first place.
With this change, `WiFiClient::write` will return as soon as all supplied data has been passed to the TCP stack. In practice that means that as much as 2 * 1460 bytes can be sent before `WiFiClient::write` will block. This change also changes `WiFiClient::write` behaviour for large blocks of data. Previously it …

WifiClient::write refactoring (second attempt)

---

doc/libraries.md

Hi, 
I added ESP.getFlashChipRealSize() function to the documentation. I couldn't determine flash size of my ESP based on getFlashChipSize function, so I was googling and found this: https://github.com/esp8266/Arduino/issues/785
I tested functionality and now adding here to official documentation.
Cheers!

Documenting of ESP.getFlashChipRealSize()

---

tools/espota.py

Using espota.py as a module by calling espota.main(args) was not working because the args given to main were not being passed into parser.parse_args().  I fixed this by having main pass args to the parser function, which in turn passes them to the parser object's parse_args() function.

fixed argument passing

---

doc/ota_updates/readme.md
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp

As suggested yesterday; this exposes the current sketch on device's MD5 hash through HTTP headers.

Exposed sketch MD5 through HTTP headers

---

libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ArduinoOTA/ArduinoOTA.h
libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino

Allows to decide if unmounting SPIFFS and potentially writing config files to SPIFFS is necessary.
Mentioned this on gitter- right now none of the examples show use of `SPIFFS.end()` nor is it possible to decide if thats even needed. Idea of this PR is to tell the handler what type of spiffs update is actually doing on. 
If updating the handler is undesired I could also a `getOTAType` function or similar that would expose the `_cmd` value.

Add OTA type to onStart callback

---

libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ArduinoOTA/ArduinoOTA.h
libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino

hashed password can be safely stored on flash

Ota hashed password

---

libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiScan.h

Adding onComplete event handler support for the asynchronous network scanning.

Adding onComplete event handler

---

cores/esp8266/WString.h

This will allow using the String library in a ranged for loop:
```C++
String s("Hi, this is a test");
for (const char& ch : s) {
Serial.print(ch);
}
```
and even modify
```C++
String s("Hi, this is another test");
for (char& ch : s) {
ch++;
}
Serial.println(s);
```

Updated String library to use C++11 iterators.

---

cores/esp8266/core_esp8266_wiring_pwm.c

Move to NMI interrupt
Rework the whole ISR to take less and more constant cycles
Current defaults run 10bits/1KHz@160MHz and 9bit/1KHz@80MHz (soft
mapped)

Fix analogWrite

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h

currently we can only pass const char * ("foo") as uri parameter to the on() method of the webserver. in more complex sketches with many uri handlers those strings use significant amount of RAM (in my case 250+ bytes). changing the uri parameter from const char * to const String &, allows strings to be moved to flash by wrapping them in the F() macro. example:
webserver->on(F("/files"), HTTP_GET,  handle_file_page_cb);

allow F() to be used for uri parameter

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h

Added HTTP Put in order to use some HTTP APIs.

Added PUT Request to HTTP Client

---

cores/esp8266/core_esp8266_timer.c
cores/esp8266/core_esp8266_wiring_digital.c
cores/esp8266/core_esp8266_wiring_pwm.c

related to https://github.com/esp8266/Arduino/issues/2175

digitalWrite and digitalRead cancel analogWrite enabled on a pin

---

cores/esp8266/FS.h
cores/esp8266/spiffs_api.cpp
libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ArduinoOTA/ArduinoOTA.h
libraries/EEPROM/EEPROM.cpp
libraries/EEPROM/EEPROM.h
libraries/ESP8266NetBIOS/ESP8266NetBIOS.cpp
libraries/ESP8266NetBIOS/ESP8266NetBIOS.h
libraries/ESP8266SSDP/ESP8266SSDP.cpp
libraries/ESP8266SSDP/ESP8266SSDP.h
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
libraries/ESP8266mDNS/ESP8266mDNS.cpp
libraries/ESP8266mDNS/ESP8266mDNS.h
libraries/Ethernet/src/Ethernet.cpp
libraries/Ethernet/src/Ethernet.h
libraries/SD/src/SD.cpp
libraries/SD/src/SD.h
libraries/SPI/SPI.cpp
libraries/SPI/SPI.h
libraries/SPISlave/src/SPISlave.cpp
libraries/SPISlave/src/SPISlave.h
libraries/TFT_Touch_Shield_V2/TFTv2.cpp
libraries/TFT_Touch_Shield_V2/TFTv2.h
libraries/Wire/Wire.cpp
libraries/Wire/Wire.h

creating global objects can be switched off by the following defines:
globally:
NO_GLOBAL_INSTANCES
locally:
NO_GLOBAL_SPIFFS
NO_GLOBAL_NETBIOS
NO_GLOBAL_SD
NO_GLOBAL_SPI
NO_GLOBAL_TWOWIRE
NO_GLOBAL_EEPROM
NO_GLOBAL_ETHERNET
NO_GLOBAL_ARDUINOOTA
NO_GLOBAL_MDNS
NO_GLOBAL_TFT
NO_GLOBAL_SPISLAVE
NO_GLOBAL_HTTPUPDATE
NO_GLOBAL_SSDP
i tried to find the most logical name for the define derived from the class name. creation of the global objects have been unified on the go.
EEPROM class got a new constructor, to allow 'external' instantiation of the class the same way es the global one (without knowing the location in flash).

allow global object instances be switch off with defines

---

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiAP.h

not very common but some might require to set the maximum number of clients, from code, to less than 4.
in my case i must allow only one client at a time.

set max_connection from code (when less than 4 is needed)

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
tools/sdk/include/user_interface.h

Thix fixes the issue for me as discussed here :
https://github.com/esp8266/Arduino/issues/1845
It seems like wifi_wps_status_cb gets an undefined status 4, I gave it a name and added the missing call to wifi_wps_disable.
here is a sketch for testing the case.
```
/*
*  This sketch demonstrates how to scan WiFi networks. 
*  The API is almost the same as with the WiFi Shield library, 
*  the most obvious difference being the different file you need to include:
*/
#include "ESP8266WiFi.h"
void setup() {
Serial.begin(74880);
Serial.setDebugOutput(1);
Serial.setDebugOutput(true);
// Set WiFi to station mode and disconnect from an AP if it was previously connected
WiFi.mode(WIFI_STA);
WiFi.disconnect();
delay(100);
Serial.println("Setup done");
}
void loop() {
// If not connected, run the WPS …
```

proposal for issue #1845 Scan networks don't work after WPS config failed

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp
libraries/ESP8266mDNS/ESP8266mDNS.h

this fix forces the mDNS to use the provided IP in the begin method
instead of the auto detected IP. this is required if the ESP8266 starts
in the AP_STA mode and activates only the AP initially.
because of the old behaviour of the begin method, and how the ip is retrieved, if the current mode is AP_STA, only the STA ip will be tried. the fix allows the usage of the explicitly provided IP. now  I can start the esp in AP_STA, with only AP active, and provide the AP ip. when STA will be connected the mDNS will continue to listen for connections on the AP IP, not disrupting the behaviour. 
there still might be a problem in how the mDNS behaves when using the begin method with only the hostname and the initial mode is AP, then esp moves to AP_STA and connects to a station, as it subscribes to …

ESP8266mDNS using the provided IP in the begin method

---

cores/esp8266/uart.c

should fix https://github.com/esp8266/Arduino/issues/2353

optimize uart rx isr and lower fifo full treshold

---

cores/esp8266/Updater.cpp

fixes: https://github.com/esp8266/Arduino/issues/2226

make updater fail if there is not enough space to fit the new firmware

---

cores/esp8266/WMath.cpp

Will return -1 like AVR would
connected to https://github.com/esp8266/Arduino/issues/2219

detect division by zero in map() to prevent exceptions

---

libraries/ArduinoOTA/ArduinoOTA.cpp
libraries/ArduinoOTA/ArduinoOTA.h

- Added option to control if the ESP should be rebooted on success
- Added delay before ESP.restart() is called
- Added some comments to the header

ArduinoOTA optimizations

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/Parsing.cpp

Should fix: https://github.com/esp8266/Arduino/issues/2131

match headers using equalsIgnoreCase

---

cores/esp8266/IPAddress.cpp
cores/esp8266/IPAddress.h

it doesn't modify any member variables, should be safe to be const.

const-correctness `IPAddress::toString()`

---

variants/ESPDuino/pins_arduino.h
variants/adafruit/pins_arduino.h
variants/d1/pins_arduino.h
variants/d1_mini/pins_arduino.h
variants/espino/pins_arduino.h
variants/espinotee/pins_arduino.h
variants/espresso_lite_v1/pins_arduino.h
variants/espresso_lite_v2/pins_arduino.h
variants/generic/common.h
variants/generic/pins_arduino.h
variants/nodemcu/pins_arduino.h
variants/phoenix_v1/pins_arduino.h
variants/phoenix_v2/pins_arduino.h
variants/thing/pins_arduino.h
variants/wifinfo/pins_arduino.h
variants/wifio/pins_arduino.h

See: arduino/Arduino#4814.
For instance this is used by the USB Host library: https://github.com/felis/USB_Host_Shield_2.0/commit/231fb542a8f42d5ada6325bdb5a3a2e1d8d37348.

Add PIN defines, so the pins can easily be used by external libraries

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

About the simplest change possible, just delete two characters and add one. The PUT(String) convenience method called the full POST method instead of calling the PUT method

Fixed PUT(String) method, it called POST in error

---

libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino
libraries/ESP8266WiFi/examples/WiFiClientEvents/WiFiClientEvents.ino

Many people have problems with using ESP8266 as WiFi-client due to
none of the examples mentioning that you should use WIFI_STA if you
only want the ESP8266 to act as a WiFi-client. Many WiFi-devices
will randomly try to connect to the ESP8266 if used as STA+AP and
complain about not being able to access the Internet or other devices
on the network.

Use WIFI_STA in WiFiClient-examples

---

doc/esp8266wifi/server-examples.md

Corrected a typo and improved grammar

Corrected a typo and improved grammar

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

For downcasting, static_cast<> is the appropriate cast. Using reinterpret_cast<> will NOT correctly adjust the `this` pointer and dereferencing such a value is undefined by spec. See [expr.reinterpret.cast]p7 for the relevant passage. The only legal use of this pointer is in another set of reinterpret_cast expressions that either land it into a numeric value, or back to the original type.

Use correct cast for downcasting reference.

---

libraries/ESP8266mDNS/ESP8266mDNS.cpp
libraries/ESP8266mDNS/ESP8266mDNS.h

Support responding correctly on both the AP and STA interfaces at once when both are active. More details in commit descriptions.

Mdns multi interface

---

cores/esp8266/Tone.cpp

As per the issue at #2491, there is a divide by error issue resulting from the specification of 0 as the frequency. This does not appear to affect the AVR implementation, but it crashes on ESP8266s. I have merely removed the division if the frequency is zero, which appears to be giving the expected results (no tone), without any code crashes. 
To test, simply load the toneMelody sketch included with the Arduino IDE (Examples -> 02. Digital -> toneMelody) and change the piezo to something else if you need to. On the Witty module used to test this, I could also tell by the wifi led blinking every time the code crashed as the ESP8266 immediately rebooted.

Prevent divide by zero error causing tone() to crash

---

cores/esp8266/core_esp8266_wiring_pwm.c

Fixed incorrect usage of memset() in PWM code which leads to incomplete initialization of struct. Thanks to GCC warning -Wsizeof-pointer-memaccess.

Fixed incorrect usage of memset() in PWM code.

---

cores/esp8266/libb64/cdecode.c

Libb64 decoder works when "char" type is signed. In esp8266 xtensa gcc "char" is unsigned, so libb64 decoder does not work. In the implementation file I replaced "char" to "int8_t" and created function wrappers in order to keep existing interface.
I  tested it, it works!

Fixed libb64 decoder.

---

cores/esp8266/Esp.cpp
cores/esp8266/Schedule.cpp
cores/esp8266/abi.cpp
cores/esp8266/cont_util.c
cores/esp8266/core_esp8266_main.cpp
cores/esp8266/core_esp8266_postmortem.c
cores/esp8266/core_esp8266_timer.c
cores/esp8266/core_esp8266_wiring.c
cores/esp8266/core_esp8266_wiring_digital.c
cores/esp8266/heap.c
cores/esp8266/libc_replacements.c
cores/esp8266/spiffs/spiffs_hydrogen.c
cores/esp8266/spiffs_api.h
cores/esp8266/time.c
cores/esp8266/uart.c
libraries/ESP8266WebServer/src/Parsing.cpp
libraries/ESP8266WebServer/src/detail/RequestHandler.h
libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266WiFi/src/WiFiServer.cpp
libraries/ESP8266WiFi/src/include/ClientContext.h
libraries/ESP8266WiFi/src/include/DataSource.h
libraries/ESP8266WiFi/src/include/UdpContext.h
libraries/ESP8266mDNS/ESP8266mDNS.cpp
libraries/ESP8266mDNS/ESP8266mDNS.h

Hello!
I fixed some warnings related to unused variables and uninitialized fields. I think not everyone is Core developer, so users should not see warnings in Core code when they compile their sketches. Related issue: #2587.

Fix warnings

---

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.h

Something like this is now possible:
```c
const size_t DST_Root_CA_X3_len = 846;
const uint8_t DST_Root_CA_X3[] = {0x30, ....., 0xfd}; 
client.setCACert(DST_Root_CA_X3, DST_Root_CA_X3_len);
```

Allow usage of byte arrays to set RootCAs

---

libraries/ESP8266LLMNR/ESP8266LLMNR.cpp
libraries/ESP8266LLMNR/ESP8266LLMNR.h
libraries/ESP8266LLMNR/README.md
libraries/ESP8266LLMNR/examples/LLMNR_Web_Server/LLMNR_Web_Server.ino
libraries/ESP8266LLMNR/keywords.txt

This is a simple implementation of an LLMNR responder for the ESP8266
Arduino package. Only support for advertizing a single hostname is
currently implemented.
LLMNR is a very similar protocol to MDNS. The primary practical
difference is that Windows systems (at least Windows 7 and later;
perhaps earlier) support the protocol out-of-the-box, whereas additional
software is required to support MDNS. However, Linux support is
currently more complex, and MacOS X support appears non-existent.

Add an LLMNR responder implementation

---

boards.txt
cores/esp8266/core_esp8266_phy.c
platform.txt
variants/arduino_spi/pins_arduino.h
variants/arduino_uart/pins_arduino.h

This PR introduces a new board called `Arduino` with three models:
- `Star OTTO`
- `Primo`
- `UNO WiFi`

Arduino boards with ESP8266

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClient.h
libraries/ESP8266WiFi/src/include/ClientContext.h
libraries/ESP8266WiFi/src/include/UdpContext.h

This PR brings minimum changes for libraries to compile with lwip2 (https://github.com/d-a-v/esp8266-phy).
#3075 seems to have been solved with it.
It is harmless otherwise.

prepare lwip2

---

libraries/ESP8266WebServer/src/ESP8266WebServer.h

This makes it easy for a user of `ESP8266WebServer` to override the value for HTTP_UPLOAD_BUFLEN. This is useful when RAM is constrained.

Allow for overridable value for HTTP_UPLOAD_BUFLEN

---

cores/esp8266/base64.cpp
cores/esp8266/base64.h
cores/esp8266/libb64/cencode.c
cores/esp8266/libb64/cencode.h
libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h

Add option to disable any newlines in output.
Resolves #3194

base64::encode() adds newlines every 72 (encoded) chars output.

---

cores/esp8266/esp8266_peri.h
doc/libraries.md
libraries/SPI/SPI.cpp
libraries/SPI/SPI.h

Hey this implement Issue #1062. Allows activation of HSPI overlap mode. I tested this with a 23LC1024 memory and it worked fine. But couldn't make it work with an SD card. The SD card was getting confused by the sharing of the SPI bus.

Implement support for HSPI overlap mode

---

cores/esp8266/core_esp8266_i2s.c

i2s_end was leaking memory and wasn't actually stopping i2s.

Free memory we allocated and actually stop i2s.

---

libraries/ESP8266WiFi/src/include/ClientContext.h

Previously, `_write_some` function would be called each time TCP stack
notifies the application that some data was delivered (via the `sent`
callback). In turn, `_write_some` would obtain more data to be sent from
the DataSource. In case of a DataSource backed by a Stream, this would
read from a stream. Some libraries (such as SD) may call `yield` and
other blocking operations from Stream read function, which can not be
used in TCP stack callbacks.
This change moves the data sending loop back into the Arduino task, with
a negligible loss of performance. TCP callback now wakes the main task
via `esp_schedule`, which performs stream read and provides more data
to the TCP stack.
Possible future optimization would be to buffer Stream data ahead of
time. That way, buffered data could be sent …

ClientContext: don’t read DataSource in TCP callback

---

libraries/SD/src/File.cpp

A problem with file streaming arose during some experiments with the SDWebServer example. It seems that the current version of the software has a problem with sending large files stored on the SD card to connected clients.
After trying to find the cause of this problem, I have found that large files are always streamed up to the first 32767 bytes, regardless of the value returned by the size() method of the File class. This can be easily seen in browser network diagnostic tools:
The issue is caused by the SD library's File class available() method, which causes its result to be saturated to 0x7FFF (32767), making the file streaming function behave incorrectly. After removing the value clamping code, the streaming works perfectly for files with sizes larger than 32kB:
I have also tested …

Remove SD file available size saturation

---

libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer.cpp
libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer.h

- fix response not being delivered to the browser after upload is done
(https://github.com/esp8266/Arduino/issues/2221)
- if Update.begin fails, don’t attempt to write data
- if update is not successful, send error message from Update to the
client
- move strings into PROGMEM

ESP8266HTTPUpdateServer: fix responses after uploading

---

cores/esp8266/MD5Builder.cpp
cores/esp8266/MD5Builder.h
cores/esp8266/md5.h
tests/host/core/test_md5builder.cpp

- const for constant function arguments of MD5Builder
solves : https://github.com/esp8266/Arduino/issues/1175

Const-correctness for MD5Builder (#1175)

---

.travis.yml
README.md
package/build_boards_manager_package.sh
package/package_esp8266com_index.template.json
platform.txt
tests/common.sh

Previously release process used a bunch of shell scripts which I had locally. Following up on https://github.com/esp8266/Arduino/projects/2, this PR implements releases via Travis CI.
Release date badge generation is dropped, to be replaced with https://shields.io/.
Separate "staging" release channel is dropped as well, both final and pre- releases will be available in a single package, distinguished by -rcX suffix in the version name.

ci: build and upload releases on Travis

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h
libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/include/ClientContext.h

WiFiClient inherits `Stream::setTimeout` method. The value passed to `setTimeout` is used by `Stream` methods like `readBytes`, `readStringUntil` and so on. Other operations with WiFiClient such as `connect` and `write` previously didn't have configurable timeouts. `connect` would time out after 5 seconds, and `write` would return only if LwIP reported an error.
This change implements timeout during `connect` and `write`. For `connect`, same timeout value is used for name resolution and the actual connection, so it is possible that worst case timeout will be twice the timeout requested. For writes, `write` function will return the amount of data sent by the time the timeout has happened.
Fixes #1420, #3247, #2120

Configurable timeout for WiFiClient connect and write operations

---

cores/esp8266/spiffs_hal.cpp

This applies patch provided in #3065.

SPIFFS: fix unaligned read in HAL (#3065)

---

boards.txt

The Generic ESP8266 Module provides the basis to compile for anything not on the current list.  Although most current boards use the 26MHz crystal, there are many using the 40MHz.  This change permits these to be readily accommodated as generic ESP8266 boards.

Add Crystal Frequency menu item for Generic module

---

cores/esp8266/pgmspace.h

Ref #3140
pgm_read_byte() and pgm_read_word() need to be macros, as some third party libraries and sketches testing macro existence.

Define pgm_read_{byte,word} as macros for compatibility

---

libraries/SPI/SPI.cpp

A few patches to decrease idle time while refilling FIFO, as well as decrease codespace.

SPI Write16, Write32, WriteBytes optimizations

---

libraries/ESP8266WebServer/src/Parsing.cpp

Currently, urlDecode() is being called before parsing arguments by '&'.
This is causing problems when passing a string containing special characters, strong passwords for example (WPA2-PSK in my particular scenario).
This tiny patch fixed it for me, while otherwise I'd have to use enctype="multipart/form-data" as a workaround.
I hope this won't break anything else (I've tested it thoroughly, however).

Fix: urlDecode done before parsing args

---

libraries/GDBStub/library.json

Custom manifest for @PlatformIO which instructs PIO Build System to do not archive library's object files. See 
- https://github.com/esp8266/Arduino/pull/3321#issuecomment-319386749
- http://docs.platformio.org/en/latest/librarymanager/config.html#libarchive

@PlatformIO library manifest for GDBStub

---

package.json
tests/common.sh
tools/platformio-build.py
tools/sdk/ld/eagle.app.v6.common.ld

- Build script for PIO
- CI Integration

Integration with @PlatformIO Build System

---

libraries/ArduinoOTA/keywords.txt

The Arduino IDE requires the use of a tab separator between the name and identifier. Without this tab the keyword is not highlighted.
Reference: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

Use correct separator in keywords.txt

---

doc/exception_causes.rst

The RST spec does not appear to believe in intra-cell line continuation as appeared to be expected by the original author.  Widen columns and unbreak words to fix output.

Fix exception_causes.rst formatting

---

cores/esp8266/core_esp8266_wiring_digital.c

Fixes https://github.com/esp8266/Arduino/issues/2916.

core: mask GPIO interrupts while attaching/detaching ISR handler

---

cores/esp8266/Esp.cpp

SDK uses final 4 sectors of flash for configuration data.
ESP.eraseConfig would only erase 2 sectors, so in some cases of
corrupted data ("system param error"), users could not fix the issue
using ESP.eraseConfig, and had to use esptool instead.
Thanks @HugoML for reporting this.

Fix erase size in ESP.eraseConfig

---

cores/esp8266/HardwareSerial.cpp

In relation to #2536 and #2502
Tested at 80MHz and 160MHz with flash-frequency at both 40MHz and 80MHz, the bug mentioned in the above issues manifests in all cases. The proposed workaround seems to work fine, I tested at 2400bps, 9600bps, 115200bps, 230400bps and 2Mbps and didn't see anomalous output.

Add a workaround-delay in Serial.flush()

---

libraries/EEPROM/EEPROM.h

Improved put function, compare data and only in case are different set _dirty flag, copy the data

EEPROM Library:

---

libraries/ESP8266AVRISP/examples/Arduino_Wifi_AVRISP/Arduino_Wifi_AVRISP.ino
libraries/ESP8266HTTPClient/examples/Authorization/Authorization.ino
libraries/ESP8266HTTPClient/examples/BasicHttpClient/BasicHttpClient.ino
libraries/ESP8266HTTPClient/examples/ReuseConnection/ReuseConnection.ino
libraries/ESP8266HTTPClient/examples/StreamHttpClient/StreamHttpClient.ino
libraries/ESP8266LLMNR/examples/LLMNR_Web_Server/LLMNR_Web_Server.ino
libraries/ESP8266NetBIOS/examples/ESP_NBNST/ESP_NBNST.ino
libraries/ESP8266WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino
libraries/ESP8266WebServer/examples/FSBrowser/FSBrowser.ino
libraries/ESP8266WebServer/examples/HelloServer/HelloServer.ino
libraries/ESP8266WebServer/examples/SDWebServer/SDWebServer.ino
libraries/ESP8266WebServer/examples/SimpleAuthentification/SimpleAuthentification.ino
libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino
libraries/ESP8266WiFi/examples/HTTPSRequestCACert/HTTPSRequestCACert.ino
libraries/ESP8266WiFi/examples/NTPClient/NTPClient.ino
libraries/ESP8266WiFi/examples/WiFiClientBasic/WiFiClientBasic.ino
libraries/ESP8266WiFi/examples/WiFiMulti/WiFiMulti.ino
libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino
libraries/ESP8266WiFi/examples/WiFiWebServer/WiFiWebServer.ino
libraries/ESP8266httpUpdate/examples/httpUpdate/httpUpdate.ino
libraries/ESP8266httpUpdate/examples/httpUpdateSPIFFS/httpUpdateSPIFFS.ino
libraries/ESP8266mDNS/examples/mDNS-SD_Extended/mDNS-SD_Extended.ino
libraries/ESP8266mDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino

I was surprised that many of the examples implicitly create an
unsecured access point with complete access to my application, which
was based off the WiFiWebServer example. I'm sure I'm not the only one
surprised by this behaviour.
Putting the WiFi into station mode prevents the open access point from being
created.

Put WiFi into station mode in examples

---

libraries/DNSServer/src/DNSServer.cpp
libraries/ESP8266mDNS/ESP8266mDNS.cpp

Other ESP8266 libraries share [a standard debug-output enablement scheme](http://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html) that allows the user to turn on sections of debug output by building with "-DDEBUG_ESP_FOO" and "-DDEBUG_ESP_PORT=<SomethingLikeAHardwareSerial>". This way you can enable implement your own debug output stream as your application might need.
This pull request makes the debug output of DNSServer and ESP8266nDNS conform to that standard.

Improve dns debugging

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266WebServer/src/Parsing.cpp

This PR for #2557 changes the ```_currentUpload``` field in the ```ESP8266WebServer``` class to ```std::unique_ptr<HTTPUpload>```, and allocates/deallocates it on demand.
Commit 67f4fc4 eliminates most of the exit paths in ```ESP8266WebServer::handleClient```. It moves the client reset and ```yield()``` call to the end of the function, introduces ```else``` clauses to remove exit paths, and inverts if/else constructs to simplify the function.

#2557 - ESP8266WebServer uses >2kb of stack when reinitialized in setup()

---

POLICY.md
Policy.md

First draft of a policy document, based on discussion under issue #3571

Issue policy

---

cores/esp8266/Arduino.h
cores/esp8266/core_esp8266_wiring.c
cores/esp8266/time.c

This resolves #3814 and adds a `micros64()` global function that is very useful.
There is certainly more that can be done to improve wallclock time-keeping, but this is a step in the right direction I feel.  This allows my application to have a reasonably decent current timestamp.
This now works well enough for me, when it previously was wrong:
```
auto now_ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
```
I purposely did not touch `clock_gettime()` or `time()` because I want to focus on achieving a functional `gettimeofday` first.  If this PR is accepted, I'm willing to work on those functions too.

Added micros64 and used to fix and improve gettimeofday.

---

libraries/ESP8266LLMNR/ESP8266LLMNR.cpp

Original fix by @d-a-v  (thanks!)

Fix ESP8266LLMNR for build with lwip2

---

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp

wifi_softap_set_config always fails, password cannot be 0 unless authmode is open, no documentation found, trial and error.

fixes #3793

---

cores/esp8266/Arduino.h

The _word_ type is an alias for _unsigned int_. It came directly from original Arduino SDK because ATmega-based boards has 16-bit int. But int for esp8266 board stores 32-bit value so _word_ in meaning _combination of two bytes_ is broken here.
For esp8266 it should be defined 16-bit long explicitly.

Fix too wide 'word' type -- it should be 16-bit instead of 32-bit

---

libraries/EEPROM/EEPROM.cpp
libraries/EEPROM/EEPROM.h

EEPROM: dirty flag, reallocate only if necessary, add getConstDataPtr method (#2217)

---

cores/esp8266/Schedule.cpp

Removed init_lists(). It was already marked as unused, so it doesn't generate a warning, but in truth it serves no purpose. The function pre-inits to 4 empty function slots, but the linked-list algorithms work without doing that init, and pre-initing that way has no performance advantage either.
If the function is ever needed in the future, for whatever reason, it can be retrieved from the file history.

Removed unused init_lists() function that serves no purpose

---

libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp

@igrr I'm starting to look at the issues labeled "easy" with milestone 2.4.0, and this is my first one. In this case, the refactoring was not so minor, so I think a review is in order. Who could review?

Refactor of WiFiMulti::run to reduce complexity and remove dead code (#2188)

---

doc/ota_updates/readme.rst

Due to the conversion of the documentation to .rst there were two broken links.
Replaced links to filesystem.md with filesystem.rst

Fixed broken links in ota_updates/readme.rst

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h

Add compatibility check for ::config() method with arduino arg order (#1168)

---

cores/esp8266/uart.c
doc/boards.rst
doc/reference.rst

Hi, this is a proposal to fix #1786

 Added Serial.setRxBufferSize method description in libraries reference document

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h

adds WiFi.getPersistent()

---

libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino

add limitations of https connections

[doc] update HTTPSRequest.ino

---

doc/esp8266wifi/client-secure-class.rst

add limitations of tls connection
seems not properly documented yet, cost me a lot of time to find out :(

[doc] update client-secure-class.rst

---

cores/esp8266/pgmspace.cpp
cores/esp8266/pgmspace.h

pgmspace.h is included from within extern "C" blocks (for example in tools/sdk/libc/xtensa-lx106-elf/include/assert.h) and from C files. This sometimes creates link errors when both the manged and unmangled versions are needed.
This change exports all symbols to C.

The pgmspace symbols are now exported to C

---

libraries/ESP8266WebServer/src/ESP8266WebServer.h

#3699
I instrumented ```Parsing.cpp:readBytesWithTimeout()``` and found with my current ideal setup (the esp alone distant to 1 meter of the AP's antenna and PC on ethernet) that I have a maximum "tries" time of 1154ms (it is 99% less than 5ms but sometimes increased for a single packet to around 1 second).
I did not try to tcpdump though, but with a bigger timeout it just works.
I think it is not too expensive to increase the timeout to 5 seconds.

increase HTTP SEND/POST timeout to 5s

---

libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiUdp.cpp
libraries/ESP8266WiFi/src/include/ClientContext.h
libraries/Ethernet/src/EthernetUdp.cpp
libraries/Ethernet/src/EthernetUdp.h

ClientContext::arduinoFlush() needs review

fix #1002 ::Flush() wait for empty send buffer

---

cores/esp8266/core_esp8266_i2s.c
cores/esp8266/i2s.h

i2s_available() It returns the number of samples than can be written before blocking

added int16_t i2s_available(); 

---

libraries/ESP8266WiFi/src/WiFiClient.cpp

fix #3983 
(I introduced this)

fix WiFiClient::availableForWrite() with no connexion

---

cores/esp8266/coredecls.h
cores/esp8266/sntp-lwip2.c
cores/esp8266/time.c
libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino

optional settimeofday()'s callback
fix #1679

handle tv.tv_usec in settimeofday()

---

cores/esp8266/cbuf.cpp

cbuf.size() must be at least one byte larger than cbuf.available() for
logic to work.  reject request to resize = available.  Issue #4002.

Fix boundary condition on resize

---

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

When application requests to write data, check if there is any unread decrypted data left. If there is, don't write immediately, but save the data to be written. When all decrypted data has been consumed by the application, send out the saved outgoing data.
Also don't use `available()` in the test for `connected()` to reduce the chance that plaintext buffer gets filled with incoming data when the application does not actually need it, and does not need to know its exact size.
Fixes https://github.com/esp8266/Arduino/issues/2256.

WiFiClientSecure: don't trash unread decrypted data when writing

---

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

- Use Client::_timeout in WiFiClientSecure::connect instead of a hardcoded value. This can be modified via Client::setTimeout before connecting.
- Set default _timeout for WiFiClientSecure to 15 seconds.
Ref. https://github.com/esp8266/Arduino/issues/3944

Configurable WiFiClientSecure connect timeout, better default value

---

libraries/ESP8266WiFi/src/include/UdpContext.h

Fixes https://github.com/esp8266/Arduino/issues/3989.

WiFiUDP: fix crash when calling destinationIP with no packet available

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

Call Client::setTimeout before connection to influence connection
timeout.
Closes https://github.com/esp8266/Arduino/issues/3451.

ESP8266HTTPClient: allow changing connection timeout using setTimeout

---

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

axTLS does not correctly implement max_fragment_length extension. This
causes servers which understand this extension (currently GnuTLS- and
WolfSSL-based) to reject the client hello.
Until this is fixed in axTLS, remove the call to enable this extension
from WiFiClientSecure.
Fixes https://github.com/esp8266/Arduino/issues/3932.

WiFiClientSecure: don't use the broken max_fragment_length extension

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp

Removes 2 warnings:
- `warning: unused parameter 'https'` in ESP8266httpUpdate.cpp
- `warning: enumeration value 'HC_NONE' not handled in switch` in ESP8266WebServer.cpp
This should cover https://github.com/esp8266/Arduino/issues/3778 I think.

Remove 2 compiler warnings

---

cores/esp8266/Schedule.cpp

When scheduling the same function from within a scheduled function the "run_scheduled_function" does not finish -> loop is not being called anymore.
Example function is : 
```
void CommandExecutor::getStreamChars(Stream* reqStream)
{
if (reqStream->available())
{
executorReceive(reqStream->read());
}
schedule_function(std::bind(&CommandExecutor::getStreamChars,this,reqStream));
}
```
I am using this in order to have all the code within my classes and not dependent on (addtional) calls from within the loop fucntion,
This patch starts a a new chain of scheduled functions when starting current cycle

Prevent endless loop in run_scheduled_functions

---

tools/get.py

Attempt to fix #4049.
Overall, whole `identify_platform()` should be rewritten to utilize platform.machine() and platform.system() to figure out CPU arch / OS type.
I didn't want to introduce large changes, as I'm not sure about dependent code, but do let me know if you want me to provide a rewrite.

Identify aarch64 properly.

---

libraries/ArduinoOTA/ArduinoOTA.cpp

Update ArduinoOTA.cpp to solve #4086

Update ArduinoOTA.cpp to solve #4086

---

libraries/ArduinoOTA/ArduinoOTA.cpp

Small fix to changes previously made by @yoursunny on #4090.  This stops ESP from crashing when receiving unrecognized UDP packets.

small fix to stop crash on unrecognized packets #4090

---

libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/WiFiClient.h
libraries/ESP8266WiFi/src/include/ClientContext.h

(*not yed* automatic) tcp-keep-alive for all new connections with standard default values
#2750

keepalive(2h,75s,9) API + status helper + change/disable methods (not enabled by default)

---

cores/esp8266/Updater.cpp
cores/esp8266/Updater.h

Makes change to printError detailed in #4007.

UpdaterClass::printError now accepts the Print object

---

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

This was a static, but when it was converted the initialization to nullptr was lost resulting in exception 28 on connect. Since it is no longer being initialized, it appears to be pointing to some random memory address.
I am seeing this exception occur everytime I connect to aws iot with client certificates.
https://github.com/esp8266/Arduino/commit/bd1c7ce1dc4f56d707637f2829f6473e888e533d#diff-26b5fb5b4e7d777dc7a201a0cdd26b2dL397 
```
Fatal exception 28(LoadProhibitedCause):
epc1=0x4020bb67, epc2=0x00000000, epc3=0x00000000, excvaddr=0x007e8008, depc=0x00000000
Exception (28):
epc1=0x4020bb67 epc2=0x00000000 epc3=0x00000000 excvaddr=0x007e8008 depc=0x00000000
ctx: cont
sp: 3fff1840 end: 3fff1b90 offset: 01a0
>>>stack>>>
3fff19e0:  62755362 65696c43 205d746e 65747441
3fff19f0:  6974706d …
```

initialize io_ctx to nullptr

---

tools/sdk/ld/eagle.app.v6.common.ld

This linker change saved my own app about 600 bytes of heap by pushing class vtables into .text and out of .rodata.  Only 1 line in the linker was added, really, with the rest of the diff simply moving .rodata and .bss after .text so that it can catch the specific mangled name.
...snip...
GCC places vtables in .rodata, with a mangled name of "_ZTV*."  Because
these are simply address jump tables, there is no need to place them in
RAM.  Instead, have the linker place them in the TEXT (aka ROM) section.
This will free up a variable amount of heap space, depending on the number
of classes with virtual functions used in any particular project.

Move C++ vtables into IRAM, out of HEAP

---

cores/esp8266/Updater.cpp
cores/esp8266/Updater.h

Added two boolean results in _writeBuffer() function, thus utilized UPDATE_ERROR_ERASE. This helps to notice whether ESP.flashEraseSector or ESP.flashWrite was unsuccessful when an error occurs. Previously, it would only show UPDATE_ERROR_WRITE.
With the request of @devyte , added _setError function to wrap some lines up and tidied the code.

Utilized UPDATE_ERROR_ERASE, added _setError function and refactored code

---

libraries/ESP8266WiFi/src/include/ClientContext.h

check ClientContext's this and _pcb once out of the ::connect() delay

---

cores/esp8266/umm_malloc/umm_malloc.c

Calloc was calling memset(0) on NULL when its implicit malloc failed,
causing a crash in UMM.  Instead, only do the memset if the memory
allocation succeeds.
Fixes issue #4207

Clear calloc block only if malloc succeeds

---

variants/oak/pins_arduino.h

headers from the Oak didn't import `common.h`, among other problems.  for example, Firmata fails to build if `NUM_ANALOG_INPUTS` is not defined.
I also modified the SCL/SCA definitions to look like the other variants.

add missing constants to variants/oak

---

platform.txt
tools/boards.txt.py

~17K smaller sketches when floats are not needed
discussion in #4089

new board generator option: --nofloat

---

libraries/ESP8266WiFi/src/include/ClientContext.h

ClientContext:_write_some: release buffer once data really accepted for sending

---

libraries/ESP8266WiFi/src/include/ClientContext.h
libraries/ESP8266WiFi/src/include/DataSource.h

Sorry for the duplicate.  Something weird with git is making it impossible for me to clean up #4066, so I'm closing that one and opening this as a new PR.  It has *only* the WiFiClient changes to clear up the NDEBUG build warnings, and does not touch the core (that's moved into #4187  completely).
...snip...
When building using the new NDEBUG option recently added, the assert()
macro is defined to nothing. This leaves a few variables unused in the
WiFi stack causing compiler warnings. Add in empty casts to remove
these warnings. Does not affect actual assert use when NDEBUG is not
defined.

Remove warnings when NDEBUG build option used

---

libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino

The certificate fingerprint included with the HTTPSRequest example seems
to be for an expired api.github.com certificate.  Replace with the current
one to avoid reporting "certificate mismatch" errors when running.

Refresh api.github.com x509 certificate

---

libraries/ESP8266WebServer/src/ESP8266WebServerSecure.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp

The first of these commits removes duplicated code for loading certs.  There's already a method to do this, so the add'l ones added for support of ESP8266WiFiServerSecure were not needed.
The second one fixes a compile error found in the WebServerSecure class when HTTP_SERVER debugging is enabled.  The output macro wasn't brought in from the original, non-secure file.

Minor cleanup of SSL server methods, missing macros

---

cores/esp8266/spiffs_api.h

Fix spiffs lseek typo for seek_end

---

doc/faq/readme.rst

doc/faq: tcpCleanup

---

cores/esp8266/Arduino.h

Added correct TIM_DIV256, changed TIM_DIV265 for deprecation

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/Parsing.cpp
libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h

additional mimetable fixes, additional string moves to progmem

---

libraries/ArduinoOTA/examples/OTALeds/OTALeds.ino
libraries/DNSServer/examples/CaptivePortalAdvanced/CaptivePortalAdvanced.ino
libraries/DNSServer/examples/CaptivePortalAdvanced/tools.ino
libraries/ESP8266AVRISP/src/ESP8266AVRISP.cpp
libraries/ESP8266AVRISP/src/ESP8266AVRISP.h
libraries/ESP8266LLMNR/ESP8266LLMNR.cpp
libraries/ESP8266WebServer/examples/FSBrowser/FSBrowser.ino
libraries/ESP8266WiFi/examples/NTPClient/NTPClient.ino
libraries/Ethernet/examples/BarometricPressureWebServer/BarometricPressureWebServer.ino
libraries/Ethernet/examples/UdpNtpClient/UdpNtpClient.ino
libraries/Ethernet/src/Dns.cpp
libraries/Ethernet/src/utility/socket.cpp
libraries/SD/src/SD.cpp
libraries/SD/src/utility/Sd2Card.cpp
libraries/SD/src/utility/SdFile.cpp
libraries/SPISlave/examples/SPISlave_Test/SPISlave_Test.ino
libraries/SPISlave/src/hspi_slave.c
libraries/Servo/src/esp8266/Servo.cpp
libraries/TFT_Touch_Shield_V2/TFTv2.cpp
libraries/TFT_Touch_Shield_V2/TFTv2.h
libraries/esp8266/examples/RTCUserMemory/RTCUserMemory.ino
tests/common.sh

-edit- This is now completed and there are no errors or warnings reported when run with -Wall -Werror as part of the build process.  Ready for review 
Use platform.local.txt to add -Werror to GCC for the build of all
code.  Any warnings on a submitted patch will cause an error.

Add -Werror to acceptance builds for C and CPP

---

libraries/ESP8266WiFi/src/WiFiClient.cpp
libraries/ESP8266WiFi/src/include/ClientContext.h
tests/device/test_WiFiClient/test_WiFiClient.ino

Reported in https://github.com/esp8266/Arduino/issues/4078.
WiFiClient::stopAll, called from a WiFi disconnected event handler,
could be called while WiFiClient::connect was in progress. This issue
was initially fixed in #4194, by testing `this` pointer for being
non-null in ClientContext::connect.
This change delegates deletion of ClientContext to WiFiClient
destructor. WiFiClient::stop only calls ClientContext::stop, which
closes/aborts the connection.

WiFiClient: don’t destroy ClientContext on ::stop

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

Initialize new .threshold field when setting up STA.

[WIP] ESP8266WiFi: initialize new fields, remove old workaround

---

libraries/ESP8266WiFi/src/WiFiClient.cpp

(bool)WiFiClient needs to return ::connected() since ClientContext is not destroyed on ::stop()

---

cores/esp8266/core_esp8266_main.cpp
cores/esp8266/core_esp8266_postmortem.c
cores/esp8266/gdb_hooks.c
cores/esp8266/gdb_hooks.h
libraries/GDBStub/src/GDBStub.h
libraries/GDBStub/src/internal/gdbstub.c

- Raise an exception when assert fails
- Move GDB stub hooks into a separate file, provide header for it
- Use syscall instruction raise user mode exception
- Remove unused code in postmortem.c
Fixes #4480

Raise an exception when assert fails

---

tools/sdk/include/eagle_soc.h

macro attributes should be used with brackets

---

doc/faq/a01-espcomm_sync-failed.rst

Fix menu and checklist in a01-espcomm_sync-failed.rst

Fix menu and checklist in a01-espcomm_sync-failed

---

cores/esp8266/HardwareSerial.h
cores/esp8266/uart.c
cores/esp8266/uart.h

WDT is triggerred when uart is flooded but not read (quickly enough) by user.
Here's a fix with a message on debug console (generally same uart though).
MCVE:
```
#define PRINT_INTV_MS 5000
unsigned long next;
void setup() {
Serial.setRxBufferSize(8);
Serial.setDebugOutput(true);
Serial.println("please type in chars");
next = millis() + PRINT_INTV_MS;
}
void loop() {
static int last = 0;
int avail = Serial.available();
if (last != avail)
{
last = avail;
Serial.printf("available: %i\n", avail);
}
if (millis() > next)
{
Serial.print("reading serial: ");
while (Serial.available())
Serial.print((char)Serial.read());
Serial.println();
next += PRINT_INTV_MS;
}
}
```
A choice has to be made when receive buffer is full:
discard oldest data, or newest data ?
Current master …

uart: fix wdt input overrun

---

libraries/ESP8266WebServer/src/ESP8266WebServerSecure.h
libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
libraries/ESP8266WiFi/src/WiFiClientSecure.h

ESP8266WebServerSecure's streamFile was using the base class' method
which did not use SSL encrypt before transmitting, leading to failure.
Add a new template method and required support for
WiFiClientSecure::write(Stream&) (using a local temp buffer since the
SSL libs do not grok Arduino Streams at all).
Fixes #4544

Fix WebServerSecure streamFile()

---

tests/device/test_ClientContext/test_ClientContext.ino
tests/device/test_ClientContext/test_ClientContext.py

This test needs any TCP server and tries to find one on the gateway.
20 tcp connections are made, heap is measured.
Might be improvable (python tcp server, better measurement?)
Problem is heap does not depend on the sketch only, even if one tries to keep it straight.
See the success run, measurement must not stop at the bad moment.
Also we cannot presume how much is lost on each loop (64 here).
The same test is good too with 200 connections instead of 20, se we could make averages that would lower glitches.
Suggestions are welcome.
failed run (without fix):
```
10.43.1.254:80
heap: 44824
001 44760 -64
002 44696 -64
003 44632 -64
004 44568 -64
005 44504 -64
006 44440 -64
007 44376 -64
008 44312 -64
009 44248 -64
010 44184 -64
011 44120 -64
012 44056 -64
013 43992 -64
014 43928 -64
015 …
```

device test for #4516 (WiFiClient leaking)

---

cores/esp8266/Updater.cpp

I accidentially tried to OTA a 2MB+ file, and found the Updater.begin() actually did not report any error.
Turned out there is an arithmetic underflow on an unsigned type.

Resolve updater size check bug

---

boards.txt
tools/boards.txt.py
variants/modwifi/pins_arduino.h

Changed from generic I2C SDA and SCL pin mapping to specific mapping for board modwifi, Olimex MOD-WIFI-ESP8266(-DEV)

defined SDA and SCL pins for Olimex MOD-WIFI-ESP8266(-DEV)

---

tools/boards.txt.py

useful when changing and pushing updates
+fix pkg regeneration with an old backup file already here

boards generator: new option --allgen

---

doc/libraries.rst

Lack of documentation became obvious when I worked on https://thingpulse.com/2018/04/10/max-deep-sleep-for-esp8266/

Mention ESP.deepSleepMax() in the list of ESP-specific functions

---

tests/device/test_http_client/test_http_client.ino

The comment indicates that 8K bytes are being requested while the code was asking for 4K, I changed the comment to match the code

Fix a very small typo in http client tests

---

tools/platformio-build.py

* Resolves https://github.com/esp8266/Arduino/pull/4618
* http://docs.platformio.org/en/latest/platforms/espressif8266.html#lwip-variant

@PlatformIO: VTables, custom lwIP, sync libs and flags

---

cores/esp8266/WString.cpp

String's destructor does the same as the 'invalidate' method.

Minimizing code redundancy

---

libraries/ESP8266httpUpdate/library.properties
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h

This Pull request fixes https://github.com/esp8266/Arduino/issues/1676 referenced on  https://github.com/openenergymonitor/EmonESP/issues/3 (fix stream error).

add http client configurable timeout usefull when download is slow on server side

---

.travis.yml
tests/common.sh

Arduino builds are now taking 49 minutes or more, and failing due to
Travis timeouts.
Split the Arduino build task into even and odd halves, where each job
will build every other test.  This will reduce any test's runtime
by 50% and speed up checks to avoid the timeout.

Add build_even/odd types to split Arduino tests

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

The SSL pipeline is multi-stage, and the TCP connection can go down
even though there is still data waiting to be decrypted or in the
decryption buffer.
Explicitly check that there if there can be any data made available
to the app, and if so report that we are still connected().  When
there is no data and there is no TCP connection, report disconnected.
Fixes #4738

Report connected when any bytes are available

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

When a message is sent by the app that is larger than the SSL buffer,
it will take multiple TLS fragments to transfer.  Writes will now
loop through and not complete until either all data is transferred
or there is an error.
The prior behavior caused an error in HTTPClient (and others) as it would only write the first chunk (i.e. 512b by default) and return "512" no matter how large the app write request was.  Unless the app was expecting this and trying it in a loop, this would either cause a protocol error if the app did not check write's return value, or an app error if it detected the short write.

Make BearSSL::write() blocking

---

cores/esp8266/FunctionalInterrupt.cpp

@devyte 
The ScheduledInterrupt PR uses the new ScheduledFunctions to do the actual scheduling.
But.. that is not yet integrated into the Schedule.h -> The attached function is never called.
This PR fixes this by using the current schedule_function(..).

ScheduledInterrupts should still use current schedule_function(..)

---

cores/esp8266/core_esp8266_main.cpp
doc/faq/readme.rst
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h
platform.txt
tools/boards.txt.py
tools/sdk/include/user_interface.h

* Disable WPS at compile time
* At the price of 4K in heap, allow WPS by using a `boards.txt.py` option
* documentation in FAQ
ref: #4779

optionally allow WPS

---

libraries/ESP8266WiFi/examples/BearSSL_CertStore/certs-from-mozilla.py

Change the "ar" options in the example CertStore.AR archive generator to
make them compatible with both Linux and MacOS.

Make ar compatible with GNU and BSD in example

---

cores/esp8266/core_esp8266_waveform.c

which harms frequent digitalRead/Write like SoftwareSerial.

Avoid unnecessary waveform de-initialization 

---

cores/esp8266/core_esp8266_waveform.c
cores/esp8266/core_esp8266_wiring_digital.c

Thanks to ideas from @shimarin for offering ideas to speed up the stopWaveform
calls which may help things like SoftwareSerial run better.
Optimize the stopWaveform routine to abort fast and early whenever possible.
Remove the stopWaveform call from digitalRead().  If you're running a waveform
on a pin and try to read it, that is a logic error and you'll end up reading the
waveform and not the outside world's view of the pin.

Optimize waveform stop routines

---

cores/esp8266/WString.cpp

As @devyte noticed, PR #4955 has an issue when you catenate a string to
itself and the string used to hold a longer value because it does not
explicitly 0-terminate the resulting string.  If the string was extended,
however, reserve() would 0-terminate by default.
Always terminate the result of `s += s;` now.

Fix concat not 0-terminating when String shrunk

---

doc/esp8266wifi/station-class.rst

Here's what it looks like locally:

Adding Notes in WiFi.begin docs (closes #4949)

---

doc/faq/a02-my-esp-crashes.rst
doc/faq/a05-board-generator.rst
doc/faq/readme.rst

Changes can be seen [there](https://github.com/d-a-v/Arduino/blob/boardsdoc/doc/faq/readme.rst).

board generator documentation

---

.travis.yml
package/README.md

* When `draft: true` is set, incorrect commit/tag information is sent to Github by Travis CI. Override tag/target fields for correct behavior. Ref. https://github.com/travis-ci/travis-ci/issues/9852.
This was the root cause of https://github.com/esp8266/Arduino/issues/5002.
* clarify some points in the release process document

Minor fixes for #4999

---

doc/reference.rst

According to this tutorial and my personal test with my Amica, 1.0V delivers 320 and 3.3V delivers 1024 at 10-bit resolution. I guess 3.3V is possible.

Analog input voltage can be 3.3V

---

cores/esp8266/Print.cpp
cores/esp8266/heap.c
cores/esp8266/pgmspace.h
cores/esp8266/uart.c
cores/esp8266/umm_malloc/umm_malloc_cfg.h
libraries/ESP8266WebServer/src/detail/mimetable.cpp
libraries/ESP8266WiFi/examples/WiFiHTTPSServer/make-self-signed-cert.sh

According to the GCC man page, __section__ attributes should only be used
for global variables.  However, the PROGMEM and ICACHE_RODATA macros use
this variable decorator even for local variables.  Most of the time it works,
but when a static or inlined function tries to use a PROGMEM/PSTR/etc.
variable the compiler can throw an error like:
error: XXX causes a section type conflict with YYY
Change the PROGMEM macro to emit a section name that is unique (a combo
of the file, line, and counter variables to ensure uniqueness).  The
standard linker script will place them properly in .IROM without
any changes.
Fixes #5036 and others.

Move all PROGMEM to their own section

---

cores/esp8266/pgmspace.h

__FILE__ is used to name the segments used for each PROGMEM constant,
but __FILE__ may have a space in it.  This would cause compilation
errors.
Add quotes around the entire segment name to work around this.

Enclose PROGMEM segment names in quotes

---

cores/esp8266/core_esp8266_postmortem.c
cores/esp8266/debug.h

The memory allocation failure message was accidentally stored in RAM
and not in PROGMEM.
panic() did not place the `__FILE__` string in PROGMEM, either.
Move both to PROGMEM, save ~200 (!!) bytes of heap (depends on length of path
of the Arduino core library).

Move some exception strings to PROGMEM

---

cores/esp8266/core_esp8266_phy.c

As per https://github.com/esp8266/Arduino/issues/3408#issuecomment-413661491 undo the change in https://github.com/esp8266/Arduino/commit/e02932fcddc24740852ec0e39e494e57a8906df2. I've tried the sketch in #619 that the commit was original done to fix and it does work now without the commit.

Fix for #3408 

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h
doc/libraries.rst

As mentioned in https://github.com/esp8266/Arduino/issues/3408#issuecomment-413279368 here's an update to add an 'instantly' option to the deepSleep function.

Add instantly option to deepSleep

---

package/README.md
package/build_boards_manager_package.sh
platform.txt

In tools menu, boards belonging to each platform are grouped together.
The title of the groups is the board package name. When switching
between versions, mentioning the version number in package name helps
identify the installed version.
Rename board group from "ESP8266 Modules" to "ESP8266 Boards (2.5.0-dev)", to be
more similar to other platforms, and to reflect the fact that most
entries included are boards, not modules.
In the next released version (e.g. 2.5.0) the name will be automatically set to "ESP8266 Boards (2.5.0)".
As an extra change, when building the boards manager package, set
version number in platform.txt based on git tag name. This saves one
step when creating the release — don't need to update platform.txt
twice.
Closes https://github.com/esp8266/Arduino/issues/5007.

package: add version to board package name

---

platform.txt
tools/boards.txt.py
tools/sdk/ld/eagle.flash.16m.ld
tools/sdk/ld/eagle.flash.1m0.ld
tools/sdk/ld/eagle.flash.1m128.ld
tools/sdk/ld/eagle.flash.1m144.ld
tools/sdk/ld/eagle.flash.1m160.ld
tools/sdk/ld/eagle.flash.1m192.ld
tools/sdk/ld/eagle.flash.1m256.ld
tools/sdk/ld/eagle.flash.1m512.ld
tools/sdk/ld/eagle.flash.1m64.ld
tools/sdk/ld/eagle.flash.2m.ld
tools/sdk/ld/eagle.flash.4m.ld
tools/sdk/ld/eagle.flash.4m1m.ld
tools/sdk/ld/eagle.flash.4m2m.ld
tools/sdk/ld/eagle.flash.512k0.ld
tools/sdk/ld/eagle.flash.512k128.ld
tools/sdk/ld/eagle.flash.512k32.ld
tools/sdk/ld/eagle.flash.512k64.ld
tools/sdk/ld/eagle.flash.8m.ld

arduino-builder 1.3.25 (shipped with Arduino 1.8.5) forces full
recompilation when any file in the core directory is modified. Avoid
full recompilation by placing generated ld script into build
directory, not source directory.
Also fix an issue where git version description would not be generated
if there were spaces in build path.
Closes #5008.

build: place generated ld script into build directory

---

libraries/Servo/src/Servo.cpp

When I went to change the pulse width for my servos, the pulse width did not change with the pre-existing code.

fix min and max for Servo library

---

doc/esp8266wifi/station-class.rst

Changed in-line style to bulleted lists for improved readability

Format lists for readability

---

doc/esp8266wifi/generic-class.rst

doc: improve WiFi.persistent documentation

---

doc/esp8266wifi/readme.rst
doc/esp8266wifi/soft-access-point-class.rst
libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp

In several places of the documentation one can read "the maximum number of stations that may be connected to ESP8266 soft-AP is five." or something along those lines. However, the [softAP method](https://github.com/esp8266/Arduino/blob/9634f79f45eead2e053e30460b973ea000a0a8f6/libraries/ESP8266WiFi/src/ESP8266WiFiAP.h#L39) has a `int max_connection = 4` argument which represents ["Max simultaneous connected clients"](https://github.com/esp8266/Arduino/blob/9634f79f45eead2e053e30460b973ea000a0a8f6/libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp#L86). It would thus seem that the maximum number of stations that may be connected to ESP8266 soft-AP is four by default. This PR brings the documentation in line with the source code.
While looking into this issue I noticed that the topic may not be …

Soft-AP documentation update

---

doc/esp8266wifi/soft-access-point-class.rst

As suggested by @d-a-v in PR #5088.

Fix formatting of bullet lists in soft-AP documentation.

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h

ESP8266HTTPClient: allow getString() more than once

---

tools/sdk/include/c_types.h
tools/sdk/ld/eagle.app.v6.common.ld.h

Similar to PROGMEM changes, make the name of each ICACHE_* variable/fuction
unique to avoid issues with section conflicts.
Fixes #5115 
Added `.irom0.text.*` and `.iram.text.*` to ldscript.

Make unique sections for ICACHE_* variables

---

tools/sdk/include/c_types.h
tools/sdk/ld/eagle.app.v6.common.ld.h

With the changes in PR #5117 , blink and other examples compile but the 8266
gets stuck in a reset loop.  Undo the changes from that commit.

Undo 5117 changes to ICACHE macros

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h

implement EspClass::getFreeContStack method

---

libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino

Update api.github.com certificate signature

---

libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino
libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h

BearSSL has many more ciphers than axTLS, but they are more compute intensive
and slower.  Add an option to use only the same, limited security, axTLS ciphers
as well as allow users to specify any suite of ciphers they want using standard
BearSSL formats.
Fixes #5110

Allow cipher specification for BearSSL

---

platform.txt
tools/boards.txt.py
tools/platformio-build.py
tools/sdk/include/c_types.h
tools/sdk/ld/eagle.app.v6.common.ld.h
tools/sdk/ld/eagle.flash.16m14m.ld
tools/sdk/ld/eagle.flash.16m15m.ld
tools/sdk/ld/eagle.flash.1m.ld
tools/sdk/ld/eagle.flash.1m128.ld
tools/sdk/ld/eagle.flash.1m144.ld
tools/sdk/ld/eagle.flash.1m160.ld
tools/sdk/ld/eagle.flash.1m192.ld
tools/sdk/ld/eagle.flash.1m256.ld
tools/sdk/ld/eagle.flash.1m512.ld
tools/sdk/ld/eagle.flash.1m64.ld
tools/sdk/ld/eagle.flash.2m.ld
tools/sdk/ld/eagle.flash.2m1m.ld
tools/sdk/ld/eagle.flash.2m512.ld
tools/sdk/ld/eagle.flash.4m.ld
tools/sdk/ld/eagle.flash.4m1m.ld
tools/sdk/ld/eagle.flash.4m2m.ld
tools/sdk/ld/eagle.flash.4m3m.ld
tools/sdk/ld/eagle.flash.512k.ld
tools/sdk/ld/eagle.flash.512k128.ld
tools/sdk/ld/eagle.flash.512k32.ld
tools/sdk/ld/eagle.flash.512k64.ld
tools/sdk/ld/eagle.flash.8m6m.ld
tools/sdk/ld/eagle.flash.8m7m.ld

Similar to PROGMEM changes, make the name of each ICACHE_* variable/fuction
unique to avoid issues with section conflicts.
Also rename the generated LD linker script to avoid issue with older copies
of the eagle.app.v6.common.ld which were generated by the build process
in a global directory before being moved to the {build.path}.  The linker
would use the older, generated *.ld file instead of the generated one, which
would lead to runtime failures on some systems and cause the VTABLE location
to not correspond to the IDE menu selection.
Fixes #5115, and is an update to #5117 and #5116.

Move ICACHE_* to unique sections, local LD script

---

libraries/ESP8266WiFi/src/include/ClientContext.h

ClientContext::_wait_for_sent() could dereference a TCP's _pcb after
the connection was dropped by the OS, resulting in a crash.
Move the connection dropped check to catch this case, and replace
a fixed millisecond delay() with a yield and timeout value to minimize
wasted time when transmission completes.

Fix TCP race condition, remove fixed delay in CC

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

The cipher list values were not initialized to NULL appropriately for the
BearSSL::WiFiClientSecure() constructor called by the Server object.
This caused a crash as a random value was free'd when conecting to the
SSL server object.

Clear cipher list on server creation, fix crash

---

libraries/ESP8266WiFi/src/include/ClientContext.h

fix: tcp_output() should always be called after tcp_write(), does not break nagle (+ doc)

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

The cipher list count/pointer was cleared separately in the three
constructors available.  Move this reset to _clear() to reduce code
duplication and keep the semantics.

Minor patch to move _cipher* init to _clear() for consistency

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h

The BearSSL second stack, once allocated, was never deallocated.  The
reference count of the stack pointer never hit 0 due to the initial
creation counting as one.  Now, check to see if there is only one use_count
and if so then delete the stack.

Really free stack after last BearSSL obj destroyed

---

libraries/ESP8266WebServer/examples/SimpleAuthentication/SimpleAuthentication.ino

Address #5187 to fix use of "authentification" in ESP8266WebServer example.

There is no such word as "authentification" #5187

---

cores/esp8266/Updater.cpp
cores/esp8266/Updater.h

also no need to backup led state

fix led-pin in updater

---

cores/esp8266/Esp.cpp
cores/esp8266/Esp.h
cores/esp8266/cont.h
cores/esp8266/cont_util.c
libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino

Allow the unused stack to be reset to the check value at any time in
the application, allowing for delta-stack calculations to be done.
Add in some dumping in the BearSSL_Validation example to show the
usage for those that care.

Add stack repainting call to cont_utils

---

cores/esp8266/core_esp8266_waveform.c

Match the behavior of pre-2.4.2 PWM by allowing stopWaveform to be
called from an interrupt.
Fixes #5247

Make stopWaveform call interrupt callable

---

libraries/ESP8266WiFi/src/include/ClientContext.h

for #5237 
Bug introduced by #5167 which replaced `delay()` by `yield()`,
and that should have been `esp_yield()` which is the one `delay()` calls.
To be noted for current maintainers included myself:
`delay()` and `esp_yield()` can be called from sys context

fix: WiFiClient::flush() yields but can be called from events

---

libraries/ESP8266WiFi/src/include/ClientContext.h

As discussed in https://github.com/esp8266/Arduino/commit/e5493552215f279b0ca3c069d5ebcdfe06773d62#diff-3f3ed90c696a8411853b28574edb12d8

Fix webserver unresponsiveness

---

cores/esp8266/WString.cpp
cores/esp8266/WString.h
libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266WebServer/src/Parsing.cpp

try to fix http parsing

---

libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino
libraries/ESP8266WiFi/examples/WiFiClientBasic/WiFiClientBasic.ino
libraries/ESP8266WiFi/examples/WiFiHTTPSServer/WiFiHTTPSServer.ino
libraries/ESP8266WiFi/examples/WiFiMulti/WiFiMulti.ino
libraries/ESP8266WiFi/examples/WiFiWebServer/WiFiWebServer.ino

Deleted some left over code from a few example files in ESP8266WiFi library. #3496

examples code cleanup

---

cores/esp8266/core_esp8266_si2c.c

Fixes #4063 .
I am not changing the clockCount init value of 20 to 10 because I don't know the impact. Given that it's essentially a timeout, it shouldn't be relevant.

Add missing decrement operator to I2C clockCount

---

cores/esp8266/core_esp8266_waveform.c

The ISR could end up writing a 0 to a GPIO that had previously been
stopped, effectively overwriting user writes to those pins.  Fix to
only actually disable and write when a pin was enabled and times out.
Fixes #5306

Only stop waveforms actually running in ISR

---

doc/esp8266wifi/bearssl-client-secure-class.rst
doc/esp8266wifi/bearssl-server-secure-class.rst
doc/esp8266wifi/readme.rst

Document the BearSSL::WiFiClientSecure, ::WiFiServerSecure, and the
helper classes required to use them.
Fixes #1743 and other SSL documentation issues.

Add BearSSL documentation

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
tests/device/test_http_client/test_http_client.ino
tests/device/test_http_client/test_http_client.py

update HTTPClient API usage
skip the second POST as end() has different semantics and nulls the client pointer
use bearssl in ssl tests
add delay in python side when shutting down http web server so MacOS does not complain about address already in use

Fix device/test_http_client tests

---

doc/libraries.rst

Update libraries.rst with ESP-NOW

---

doc/esp8266wifi/soft-access-point-class.rst
libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp

Fixed two documentation errors from #3298 and #4067.

Fix doc for ESP8266WiFi

---

tools/sdk/include/eagle_soc.h

Relevant part is Timer reg section.
Some whitespace cleanup.
Fixes #1705

deprecate RTC_REG macros in favor of TIMER_REG macros (old typo in macro names)

---

libraries/DNSServer/src/DNSServer.cpp

Fix debug provision for DNSServer

---

doc/esp8266wifi/client-examples.rst

fix #5257, rendered
- [there](https://github.com/d-a-v/Arduino/blob/loopdoc/doc/esp8266wifi/client-examples.rst#read-reply-from-the-server)
- and [there](https://github.com/d-a-v/Arduino/blob/loopdoc/doc/esp8266wifi/client-examples.rst#general-client-loop)

document wificlient loop

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

Check for WEP when setting authmode

---

.travis.yml

Remove "sudo: false" from travis.yaml due to Travis changes:
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Move from container to VM per Travis requirements

---

cores/esp8266/Esp.cpp

Fix rtc mem bounds check in EspClass

---

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h

Convert the HTTPClient debug macro to store strings in PROGMEM and
use the printf_P method to dump them.
Saves ~2.3KB heap when in debug mode.

Save 2.3K in HTTPClient debug mode by PSTR

---

.travis.yml
tests/common.sh

PIO is taking 27+ minutes now, very close to the runtime limit.
Split into even and odd, just like standard Arduino.

Split PIO job into even and odd builds

---

libraries/ESP8266SSDP/ESP8266SSDP.cpp

I recently starting playing around with a few esp8266-01s and tried to use the SSDP libraries to work with Smarthings discovery:
https://docs.smartthings.com/en/latest/cloud-and-lan-connected-device-types-developers-guide/building-lan-connected-device-types/building-the-service-manager.html
on the docs there are example grovy files that do simple service discovery, i was not able to get SSDP to work correctly, though i was able to find some other projects that did (python fauxmo works for alexa, but with modifications i was able to make it work for custom devices in ST).
after digging to figure out why the python code was working and the ESP SSDP lib was not i noticed there is a string comparison in the grovy file and it was failing to match the udn with the original usn device id. The ST …

usn and udn differences cause issues with smarthings

---

cores/esp8266/IPAddress.cpp
cores/esp8266/IPAddress.h
libraries/ESP8266WiFi/src/WiFiUdp.cpp
libraries/Ethernet/src/Dns.cpp

more compatibility fixes for IPAddress, restore INADDR_ANY, INADDR_NONE

---

package/package_esp8266com_index.template.json

Some needed tools are not yet built for Win64, so use the Win32 binaries.
Add them to the platform.json file so get.py and Arduino can find them.

Add in Win64 pointers to Win32 tools

---

tests/host/common/AddrList.h
tests/host/sys/pgmspace.h

created empty AddrList.h and added some functions_P helpers

mock build on host: minor updates

---

doc/libraries.rst
doc/ota_updates/readme.rst

From discussion in #5330 
Mention eboot use of RTC memory in both ESP and Updater sections
Update explanation of the `offset` argument

Update ESP.rtcUserMemoryWrite/Read documentation

---

libraries/ESP8266mDNS/src/LEAmDNS.cpp
libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp
libraries/ESP8266mDNS/src/LEAmDNS_Helpers.cpp
libraries/ESP8266mDNS/src/LEAmDNS_Priv.h
libraries/ESP8266mDNS/src/LEAmDNS_Transfer.cpp

The bug referenced in the code that required a custom macro to enable
PSTR/PROGMEM compilation ( https://github.com/esp8266/Arduino/issues/3369 )
was fixed a while back and all PROGMEM references now live in their own
save .sections.
This patch simply is the output of `sed -i s/PSTR_LEA/PSTR/g *` and
`sed -i s/PROGMEM_LEA/PROGMEM/g *` on the codebase and the removal
of those defines.

Convert to standard PSTR/PROGMEM macros

---

package/build_boards_manager_package.sh
platform.txt
tools/signing.py

The boards packager was deleting what was at the time it was written
unused lines in the platform.txt file before deploying to Arduino.
One of these lines is now needed for signing to work, so don't delete
it.
Also, explicitly call "python signing.py" because it looks like Arduino
is sanitizing/removing executable bits on files when extracting from
boards manager installations.
Fixes #5483

Keep signing commands in platform.txt on release

---

package/README.md

Fix json url typo
Clarify some points
Add readthedocs instructions

Update release instructions README.md

---

.travis.yml
package/build_boards_manager_package.sh

- git: clone with depth=1
- git: no recursive submodule
no more dependency on savannah.nongnu.org nor bearssl.org

CI: reduce git load

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

if the passphrase is empty, use secure auth mode could not connect to wifi.

fix bug. in sta mode, empty passphrase should not use secure auth mode

---

libraries/ESP8266WebServer/src/ESP8266WebServer.cpp

This PR fixes Issue #4717.
As stated in the issue, some devices send `qop="auth"` in the authorization header, but the server only accepts `qop=auth`. This apparently affects IPhone/IPad devices, but also python-requests.
The PR fixes it by accepting both header versions, even if one might violate the RFC standard.

Fix: WebServer: Digest authentication failed for some clients

---

tools/boards.txt.py
tools/sdk/ld/eagle.flash.2m.ld
tools/sdk/ld/eagle.flash.4m.ld

Noticed by @arihantdaga in https://github.com/xoseperez/espurna/issues/1436
Same as <=1024 KiB boards, just make start=end

Fix negative SPIFFS size for 2M/4M (no SPIFFS) boards

---

libraries/ESP8266mDNS/src/ESP8266mDNS_Legacy.h
libraries/ESP8266mDNS/src/LEAmDNS.h

#5295 should be applied to mDNS::begin() I guess :)

mDNS: Add support for String arg to begin()

---

cores/esp8266/IPAddress.cpp
cores/esp8266/IPAddress.h
libraries/ESP8266WiFi/examples/IPv6/IPv6.ino

add 1 more IPAddress constructor

---

tools/sdk/ld/eagle.app.v6.common.ld.h

PR #5538 made exceptiond disabled by default and changed some file names
which not get updated in the linker file, resultin in exceptions ending up
back in IRAM.

Move exceptions back out of IRAM

---

libraries/DNSServer/src/DNSServer.cpp
libraries/DNSServer/src/DNSServer.h

These changes rework DNSServer so that it's more robust in the face of real-world DNS queries. They should resolve issues #5534 #5529 and #3357

Rework DNSServer to be more robust

---

.travis.yml
tests/build.sh
tests/build6.sh
tests/common.sh
tests/debug.sh
tests/platformio.sh
tests/run_CI_locally.sh

Fixes the TODO created by @igrr in #5474.
By the way, the `BUILD_TYPE` values `package`, `host` and `style` seem to be unhandled?

Split common.sh into separate scripts for each job

---

cores/esp8266/Udp.h
libraries/ESP8266WiFi/src/WiFiUdp.h

cleanup WiFiUdp virtual override decorators - add virtual destructor

---

doc/installing.rst

Should be singular, not plural (submodule, not submodules). 
```
git: 'submodules' is not a git command. See 'git --help'.
The most similar command is
submodule
```

Documentation: Correct 'git submodule' syntax

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h
tools/sdk/include/user_interface.h

Effect of `WiFi.hostname("new name")` on the network:
My AP runs `openwrt` with `dnsmasq`, and I can ping the new hostname as soon as `Wifi.hostname("name")` is called on the esp.
Sketch:
```
#include <ESP8266WiFi.h>
#include <PolledTimeout.h>
#ifndef STASSID
#define STASSID "your-ssid"
#define STAPSK  "your-password"
#endif
const char* ssid     = STASSID;
const char* password = STAPSK;
void connect ()
{
WiFi.mode(WIFI_STA);
WiFi.begin(ssid, password);
while (WiFi.status() != WL_CONNECTED) {
delay(500);
Serial.print(".");
}
Serial.println("");
Serial.println("WiFi connected");
Serial.println("IP address: ");
Serial.println(WiFi.localIP());
}
void setup() {
Serial.println();
Serial.println();
Serial.print("Connecting to ");
Serial.println(ssid); …
```

dynamic WiFi.hostname("newname")

---

doc/gdb.rst

Fix missed backquote to make monospaced text in gdb.rst

---

.travis.yml
cores/esp8266/IPAddress.h
libraries/ESP8266NetBIOS/ESP8266NetBIOS.cpp
libraries/ESP8266WiFi/examples/StaticLease/StaticLease.ino
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
libraries/ESP8266mDNS/src/LEAmDNS_lwIPdefs.h
tests/build1.sh
tests/host/common/user_interface.cpp
tests/run_CI_locally.sh

adaptations for lwIP-v1.4 

---

cores/esp8266/IPAddress.h

fix testing IPAddress validity

---

libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.cpp

Fixes #5701 WDTs and other issues with BearSSL::WiFiServerSecure
The BSSL server was creating the client it returns on a connection in a
way that caused the counter for the stack_thunk to get out of sync and
cause it to be freed improperly by having the destructor be called on
more time than the constructor.  Looks like RVO.
Rewrite the ::available() function in order to avoid this issue with
help from @devyte.

Fix BearSSL Server WDT

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp

fix #5667 
Bug is reproduced
This patch stops dhcp client when WiFi goes off,
dhcp client was anyway started by firmware when WiFi goes on.
Thanks @dalbert2 
*edit: bug no more appearing*

stop lwIP dhcp client when WiFi goes off.

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h
libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.cpp
libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.h

Because the constructors of the BSSL client and server add a reference
count to the stack_thunk, if there is no copy constructor defined then
the stack thunk reference count can get out of sync causing the stack
thunk memory to be freed while still in use.  That could cause random
crashes or hangs.
Add a very basic copy constructor to the WiFiClientSecure and
WiFiServerSecure objects, using the default operator= to duplicate
simple types and shared_ptr classes.

Fix copy constructors to BearSSL server/client and axTLS compat wrappers

---

libraries/SPI/SPI.cpp
libraries/SPI/SPI.h

Fixes #4967
Support any alignment of input and output pointers and transfer lengths
in SPI::transferBytes.  Use 32-bit transfers and FIFO as much as
possible.

Allow unaligned input/output to SPI::transferBytes

---

libraries/Wire/Wire.cpp
libraries/Wire/Wire.h
libraries/Wire/examples/master_reader/master_reader.ino
libraries/Wire/examples/master_writer/master_writer.ino
libraries/Wire/examples/slave_receiver/slave_receiver.ino
libraries/Wire/examples/slave_sender/slave_sender.ino

Wire Examples based on AVR ones of the same name

---

boards.txt
doc/boards.rst
tools/boards.txt.py

Update XinaBox CW01

---

tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h

Fix dereferencing in pgm_read_ptr() macro on 8266 and host.
Fixes #5733

Fix pgm_read_ptr()

---

cores/esp8266/AddrList.h
libraries/ESP8266WiFi/src/include/UdpContext.h

Per 'udp_set_multicast_netif_addr()' signature and comments in lwIP sources:
An IPv4 address designating a specific interface must be used.
When an IPv6 address is given, the matching IPv4 in the same interface must be selected.
fix https://github.com/esp8266/Arduino/commit/e3bc3c226b4789f30e6f6a77a5522776b01f83bc#r32235572

UdpContext::setMulticastInterface(): fix for IPv6

---

tools/sdk/ld/eagle.app.v6.common.ld.h

Match `__FUNCTION__` linking, keep C++ function names out of rodata/heap.

Move __PRETTY_FUNCTION__ to progmem

---

libraries/ArduinoOTA/ArduinoOTA.cpp

Fixes #4643 
This is especially important when compiling for host mode, because ArduinoOTA is pulled in unconditionally by the Makefile in tests/host. Thus it breaks the build as soon as NO_GLOBAL_INSTANCES or NO_GLOBAL_MDNS is defined.

Fix hardcoded dependency of ArduinoOTA on mDNS

---

tests/host/Makefile

Fixes missing symbols during linking of sketches that use them.

emulation on host: Add base64 decode library to mock files

---

tests/host/Makefile

This patch splits ARDUINO_LIBS into two variables. The second variable is called OPT_ARDUINO_LIBS and can be overridden by the caller as it uses the ?= assignment operator. Additionally it unifies and simplifies collecting the files in common/ by using the addprefix macro. All changes should be 100% backwards compatible.

emulation on host: Make non essential ARDUINO LIBS optional.

---

cores/esp8266/Updater.h
libraries/ESP8266WiFi/src/include/UdpContext.h

Add progress callback to Updater class.

---

tests/host/common/user_interface.cpp

optimistic_yield() takes micro seconds not milliseconds as interval parameter

emulation on host: Fix optimistic_yield(interval_us)

---

package/package_esp8266com_index.template.json

Use local copy of python distro to include a subdir

---

platform.txt

fix #5798: from @AcuarioCat: There is a typo in platform.txt on line 87 that causes makecorever.py to fail.

fix typo in platform.txt

---

package/package_esp8266com_index.template.json
platform.txt
tools/upload.py

Fixes problem of python files expanding in tools/ dir and not
in tools/python.

Point to proper uploaded python repackage w/subdir

---

platform.txt
tools/upload.py

No need to explicitly send in full paths for esptool and pyserial Python
libs because they're in well known locations relative to upload.py.
Make upload.py calculate these on-the-fly and clean up platform.txt.

Clean up uploader.py, use implied paths

---

tests/host/common/ArduinoMain.cpp

I don't know how this happened, sorry for the slip-up. :-/

emulation on host: fix wrong tty_restore instead of restore_tty variable

---

tools/signing.py

The try-except swallowed the following error: `ord() expected string of length 1, but int found`
Poor error handling resulted in a syntax error and subsequent compilation failure in `Updater.cpp`

Fix encoding error and error suppression

---

libraries/ESP8266WiFi/src/CertStoreBearSSL.cpp

Add OOM check and debug message in CertStore

---

cores/esp8266/cont_util.cpp
tools/signing.py

Fixes #5794 as found by @mattbradford83

Fix repaintable stack calculation

---

.gitmodules

The BearSSL submodule reference is missing the .git extension on the
URL.  Add it, to match the rest of the repos.

Add .git to BearSSL repo reference

---

cores/esp8266/sntp-lwip2.cpp

Implement sntp_get|set_timezone_in_seconds()

---

tests/host/common/MockUART.cpp

GCC reports the following warning about ignoring the return value of
write() (to the console/UART in this instance).
````
common/MockUART.cpp: In function ‘void uart_do_write_char(int, char)’:
common/MockUART.cpp:67:8: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
write(uart_nr + 1, &c, 1);
~~~~~^~~~~~~~~~~~~~~~~~~~
````
Add a simple warning printout to STDERR which may not be the same as the
UART stream and could succeed.

Fix minor warning w/Ubuntu18.04 in host test build

---

cores/esp8266/spiffs_api.h

The check if the end address of the SPIFFS partition is smaller or equal to the start of the partition breaks sketches that are linked with zero size SPIFFS linker scripts, but create their own SPIFFS partition later at arbitrary flash locations. But this check can safely be removed, because the check if the the SPIFFS partition is of size 0 is done a few lines further down anyway.

Remove redundant check for zero size SPIFFS partition

---

tests/host/common/ArduinoMain.cpp
tests/host/common/ArduinoMainUdp.cpp
tests/host/common/ClientContextSocket.cpp
tests/host/common/HostWiring.cpp
tests/host/common/MockEEPROM.cpp
tests/host/common/MockEsp.cpp
tests/host/common/MockTools.cpp
tests/host/common/MockWiFiServer.cpp
tests/host/common/MockWiFiServerSocket.cpp
tests/host/common/UdpContextSocket.cpp
tests/host/common/include/ClientContext.h
tests/host/common/include/UdpContext.h
tests/host/common/mock.h
tests/host/common/user_interface.cpp

* uart emulation on tty: add cmdline `-b` debug option to disable raw tty 
* emulation with socket: fix nasty delay
* properly check all return values (read() returning 0 indicates closed peer)
* ClientContext::state() triggers read() to check for closed peer
* hide annoying MOCK messages, add cmdline `-v` option to show them
* uart emulation on tty: check more return values 
* emulation on host: tcp/udp port shifting: new cmdline `-s`(port Shift) option

emulation on host: fix nasty delay

---

cores/esp8266/core_esp8266_version.h
libraries/ESP8266WebServer/src/ESP8266WebServer.cpp
libraries/ESP8266WebServer/src/ESP8266WebServer.h
libraries/ESP8266mDNS/src/ESP8266mDNS.h

* make (static) `ESP8266WebServer::responseCodeToString` visible and usable
* esp8266:coreVersionNumeric(): add a define to check on its usability
```
#if HAS_ESP8266_VERSION_NUMERIC
if (esp8266::coreVersionNumeric() >= 20500042)
{
// modern api
}
else
#endif
{
// older api
}
```

small addons

---

tools/upload.py

Avoid picking up system pyserial/esptool

---

cores/esp8266/FS.h
cores/esp8266/HardwareSerial.h
cores/esp8266/Print.h
tests/host/fs/test_fs.cpp

Replace the individual override with the existing SD.h File's
implementation for all methods of File::write.
Fixes #5846

Reimplement SD.h write methods exactly in File

---

cores/esp8266/HardwareSerial.h

Add missing "using Print::write" to the HWSerial class to get the proper
overrides to make Serial.write(0) and Serial1.write(0) work as expected.
Fixes #5846

Fix Serial.write(0) overloading

---

libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp

Fix SSID reporting for 32-char SSIDs

---

libraries/ESP8266WiFi/examples/BearSSL_CertStore/certs-from-mozilla.py

The input file containing certificates has changed, certificates (the column PEM_INFO) are now at position 31.

BearSSL CertStore Example: Fix the changed structure of the input file

---

cores/esp8266/WString.cpp
cores/esp8266/WString.h
tests/host/core/test_string.cpp

Fixes #5883 and supercedes #5890
The replace() function was using len() while in the middle of buffer
operations.  In SSO mode len() is not stored separately and is a call to
strlen(), which may not be legal if you're in the middle of overwriting
the SSO buffer, as was the case in ::replace when the replacement string
was longer than the find string.  This caused potential garbage at the
end of the string when accessed.  Instead, just cache the length in a
local while doing the operation.
Add in test cases from #5890 as well as some new ones that fail on the
unmodified core.

Fix String::replace()

---

platform.txt

The link to the Arduino-IDE-1.5-3rd-party-Hardware-specification has changed in the meantime,
from https://github.com/arduino/Arduino/wiki/Arduino-IDE---1.5-3rd-party-Hardware-specification
to https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification

Update link in platform.txt

---

README.md

Since we have some submodules it is recomended to include them while cloning the project.

include submodules with git clone --recursive

---

libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp

Remove duplicate debug statement when debug mode is enabled (`-DDEBUG_ESP_MDNS_INFO`) and do not use Serial when debug mode is disabled (default)

LEAmDNS: remove implicit debug statements

---

libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp

OTA is broken in AP mode because ESP8266mDNS is checking whether the station is connected before processing. Change the logic to WiFi.isConnected() OR WiFi.softAPgetStationNum()>0 fixes the issue.

Fix OTA in AP mode

---

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp

bugfix: restore WiFi::setSleepMode functionality with sdk-2.2.x

---

doc/esp8266wifi/udp-examples.rst

C arrays are 0 indexed, accordingly writing to array[255] actually writes to the 256th position, which is naturally out of bounds of a 255 item array. increasing the size of the array to 256 corrects that error. Also, 0 is an int and requires a cast into a char, '\0' is just a cleaner (a more syntactically pedantic) way to achieve the same end.

Correct out of bounds condition and remove an unnecessary cast

---

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

fix https://github.com/esp8266/Arduino/commit/ca79f2ce39724527052319717a731b3501d5f0b2#commitcomment-33018667
fix #5945

use static_assert to check on fw structure changes over updates (fix)

---

doc/filesystem.rst

Update the docs to point to the later version of the 8266 sketch data
uploader and inform existing users of the need to upgrade.
Fixes #5845

Add note about needing 0.4 esp8266fs uploader

---

cores/esp8266/PolledTimeout.h

polledTimeout: ensures timeType is unsigned

---

cores/esp8266/core_esp8266_wiring_digital.cpp

ISR: check for address in IRAM

---

cores/esp8266/FunctionalInterrupt.cpp

#5995 hasn't actually merged any PR - the minimum to get actual code working is in this PR.
Caveat: I don't know how to check if ICACHE_RAM_ATTR has the desired effect on lambda expressions, if it does not, there will still be an adverse performance (no real-time behavior!) impact over the standard Arduino attachInterrupt() usage.
Q: why not implement void attachInterruptArg(uint8_t pin, void (*)(void*), void * arg, int mode) like the ESP32 has already?

ISR code must be in ICACHE_RAM - the check was commited in ab125162bf

---

tests/README.md

Some users didn't know they had to update the submodules before running tests on host (see esp8266/Arduino/issues/5910). Added a notice to prevent wasting time of users new to git

Added notice to update submodules to test README

---

tests/host/Makefile

Force GCC to run with -funsigned-char during host tests  to make
the PC match the default behavior used by the xtensa GCC port.

Make chars unsigned by default, matching ESP8266

---

libraries/SPISlave/src/hspi_slave.c

I am fixing the PR https://github.com/esp8266/Arduino/pull/5489 that ended incorrectly. All facts described in the original PR hold.

Fix spi slave timing (library SPISlave)

---

doc/esp8266wifi/station-class.rst
libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp

For some reason, ip address is not propagated in a visible way for lwip2
when switching to static address (wifi.config()) *after* wifi.begin().
This patch calls lwip-v1.4's netif_set_addr() with the new ip address to set
all things up, just like it is done and right when wifi.begin() is called
after wifi.config().
Also tested when IPv6 is enabled.
fixes #5839
fixes #6024

fix switching to static address with lwip2

---

libraries/ESP8266mDNS/src/LEAmDNS.cpp

MDNS Callback setting needs std::bind parameter by reference instead of by value

MDNS Callback std:bind reference

---

.gitignore

git clean honors .gitignore, leaving the build tools downloaded by tools/get.py in place.

tools/python is missing from .gitignore

---

libraries/ESP8266HTTPClient/examples/StreamHttpClient/StreamHttpClient.ino
libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp

fix #6033 
(bug is reproduced and fixed)

Honor timeout in HTTPClient

---

package/drop_versions.py

Printing 'Dropping' debug strings to stdout leads to write in package json.
This moved that to stderr stream.
Alternatively it can be removed.

Moved 'Dropping' print from stdout to stderr in drop_versions.py

---

package/build_boards_manager_package.sh

To avoid issues as seen in 2.5.1 release where an invalid JSON was
published for a few hours, fail the board script if JQ can't parse the
generated output file.

Fail if generated JSON file cannot be read

---

libraries/ESP8266WiFi/src/include/ClientContext.h

Couple of days I was troubleshooting strange behavior with stability of components built on top of WiFiClient and WiFiClientSecure. Finally, I found the root cause of these issues. From time to time it happened that call of write method get stuck until the remote peer closed connection. It seems that root cause bug is present for quite long time in the code. 
When tcp send buffer is full, ClientContext::_write_from_source increments _send_waiting and switch context to NONOS using esp_yield. If something else call esp_schedule (not _write_some_from_cb method in the same instance of ClientContext), the cycle in  _write_from_source is repeated, send buffer is still full and value of _send_waiting is incremented again (thus from this moment _send_waiting>1). Any successful ack on the relevant …

Bugfix for stuck in write method of WiFiClient and WiFiClientSecure until the remote peer closed connection

---

libraries/SD/src/SD.h
tests/host/fs/test_fs.cpp

Make FILE_WRITE append in SD.h wrapper

---

platform.txt

Changes since 2.5.1 (to 2.5.2)
Core
----
* Add explicit Print::write(char) (#6101)
Build system
----
* Fix typo in elf2bin for QOUT binary generation (#6116)
* Support PIO Wl-T and Arduino -T linking properly (#6095)
* Allow *.cc files to be linked into flash by default (#6100)
* Use custom "ElfToBin" builder for PIO (#6091)
* Fail if generated JSON file cannot be read (#6076)
* Moved 'Dropping' print from stdout to stderr in drop_versions.py (#6071)
* Fix PIO issue when build environment contains spaces (#6119)
Libraries
----
* Remove deadlock when server is not acking our data (#6107)
* Bugfix for stuck in write method of WiFiClient and WiFiClientSecure until the remote peer closed connection (#6104)
* Re-add original SD FAT info access methods (#6092)
* Make FILE_WRITE append in SD.h …

Release 2.5.2

---

doc/reference.rst

Since v2.5.1, ISRs are required to have ICACHE_RAM_ATTR before them, this pull request adds this info to the documentation.

Document ISRs need ICACHE_RAM_ATTR before them

---

cores/esp8266/StackThunk.cpp

Fix #6143 which found a cipher combination which overran the old limit
of 5600 bytes (it required 5700 bytes).

Expand BSSL stack to 5750 bytes

---

cores/esp8266/StackThunk.cpp
cores/esp8266/StackThunk.h

On return from a BSSL call, check that the last element of the stack is
still untouched.  If it is modified, print an error and abort().
Will catch problems like #6143 many times with an informative error
message instead of corrupting the heap and having a random crash
sometime later.

Add basic canary check to BSSL stack thunk

---

tools/sdk/ld/eagle.app.v6.common.ld.h

As found by @mhightower83, umm_malloc was placed in flash during the
.c->.cpp conversion because of a missed linker change.
Adjust the link script to the new name .cpp

Move umm_malloc back to IRAM

---

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp

Since PR #6065 x509 memory structure are dropped after succesful handshake. This is ok as long as there is no TLS renegociation, otherwise it will crash.
Adding this flag to avoid any TLS renego, as described here: https://bearssl.org/x509.html

Added BR_OPT_NO_RENEGOTIATION flag to forbid TLS renegociation

---

libraries/ESP8266WiFi/examples/BearSSL_Server/BearSSL_Server.ino

Needed for future automated performance test suite use, to allow
selecting between EC and RSA signed keys for the server's cert.

Add an EC keyed certificat to BearSSL Server example
