libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
#6026 was not tested in every cases.
This PR hopefully fixes a missing one
(trigger address change by calling lwIP-v1.4 api *only when ip is already set by other mean (generally dhcp)*)
fixes #6191
=> lwip2: (re)fix setting static ip address

README.md
1. The current version is ~at~ on the Arduino website
2. Start Arduino and open _the_ Preferences window
3. Enter ```https://arduino.esp8266.com/stable/package_esp8266com_index.json``` into _the_ *Additional Board Manager URLs* field
4. The current version is ~at~ on the Arduino website
5. [PlatformIO](https://platformio.org?utm_source=github&utm_medium=arduino-esp8266) is an open source ecosystem for IoT
development with _a_ ~cross platform~ cross-platform build system, library manager and full support
6. [ESP8266 Community Forum](https://www.esp8266.com/u/arduinoanswers) is a ~well established~ well-established community
7. or just want to discuss how to approach a problem, (removed extra space after 'problem')
8. when encountering an issue ~which~ that happens at run time
9. attach …
=> Fix editing, typos and grammatical errors

tests/host/Makefile, tests/host/common/Arduino.cpp, tests/host/common/ArduinoMain.cpp
(temporarily disable littleFS mock due to missing file)
=> emulation: add fake cont_yield

libraries/esp8266/examples/ConfigFile/ConfigFile.ino, tests/common.sh, tests/platformio.sh
Followed the video and examples that was provided here : 
https://arduinojson.org/v6/doc/upgrade/
=> Updated Example to use ArduinoJson6

cores/esp8266/interrupts.h
The interrupts.h header includes a few headers that are not strictly needed, but the xt_rsil xt_wsr_ps are in Arduino.h, and that was not included.
Master compiles fine after cleanup.
For instance in EspSoftwareSerial, the unfixed interrupts.h forced inclusion of Arduino.h before interrupts.h, that's confusing to the human reader, this PR fixes that hidden prerequisite.
=> Unrelated includes, but necessary Arduino.h missing

libraries/esp8266/examples/SerialStress/SerialStress.ino
Using the std::bind workaround via FunctionInterrupt while attachInterruptArg is pending.
=> EspSoftwareSerial release 5.2.1

cores/esp8266/Esp.cpp, cores/esp8266/Schedule.cpp, cores/esp8266/Updater.cpp, cores/esp8266/interrupts.h
Fix now and future collisions with 3rd party Arduino libraries (currently Adafruit DHT has this issue).
=> Put InterruptLock (from interrupts.h) into namespace esp8266

tests/device/Makefile, tests/device/libraries/BSTest/runner.py
this is an issue probably since we switched from esptool.exe to esptool.py.
=> device tests: filter weird characters from esp output to python

package/package_esp8266com_index.template.json
Fixes #6220
MklittleFS had different configuration options which affected small
files and could result in crashes or corruption on upload.
Update mklittlefs tool to one that matches the config of the current
library.
You will need to re-run tools/get.py to get the new tool version if you
are running from Git.
=> Update mklittlefs to match library

.gitignore
The Arduino IDE for Visual Studio in part uses the standard MS Visual Studio project layout.
=> Expand gitignore to cover files created by Visual Micro

cores/esp8266/Schedule.cpp
Functional was not initialized because of `malloc()` instead of `new`.
First assignment calls destructor on initial value which was not constructed (->frozen,wdt)
=> scheduled function: replacing new by malloc needs to initialize complex members

libraries/ESP8266WiFi/src/include/UdpContext.h
fix for #5960 didn't take fragmented packets into account
fixes #6218
=> udp remote pbuf helper: honor fragmented packets

cores/esp8266/AddrList.h, libraries/ESP8266mDNS/src/LEAmDNS.cpp, libraries/ESP8266mDNS/src/LEAmDNS.h, libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp, libraries/ESP8266mDNS/src/LEAmDNS_Priv.h, libraries/ESP8266mDNS/src/LEAmDNS_Transfer.cpp
Default interface is STA (or AP if available and STA is unavailable).
An interface can also be specified in `::begin()` by its IP address.
MDNS will not cross interfaces (there is currently no notion of "bridged interfaces")
Multiple instances should be working, this is not tested in this commit.
=> mDNS: restriction to a single interface

.travis.yml, libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp, tests/buildm.sh, tests/host/common/AddrList.h, tests/host/common/ClientContextSocket.cpp
(trivial AddrList emulation)
Also fix mock TCP write
=> mock: addrList fix

cores/esp8266/Arduino.h, cores/esp8266/FunctionalInterrupt.cpp, cores/esp8266/core_esp8266_wiring_digital.cpp
Fixes: #6049 
- BUG FIX: __attachInterruptArg is known in the field, but it's use fails due to incorrect delete of arg pointer via cleanupFunctional. This PR guards against this case.
- Original author commented that ScheduledFunctions.(h|cpp) were added by mistake, and should be removed.
- ICACHE_RAM_ATTR was previously applied to attachInterrupt() / detachInterrupt() functions, but reviewer of #6003 commented that this can be reverted to save some precious IRAM, as attaching / detachInterrupt from inside ISR are corner cases.
- Properly expose attachInterruptArg() via Arduino.h
(Reference: PR #6047 implement all-C++ functional based interrupt service routine handling. Caveat: ICACHE_RAM_ATTR attributes maybe don't quite work on functional instances, like lambdas, yet)
=> Bugfix: attach interrupt (#6049)

libraries/ESP8266WiFi/src/include/UdpContext.h
This bug changes UDP payload when packet are not read fast enough.
=> fix bug in storing UDP remote address

cores/esp8266/Arduino.h, cores/esp8266/core_esp8266_app_entry_noextra4k.cpp, cores/esp8266/core_esp8266_main.cpp, libraries/ESP8266WiFi/src/include/UdpContext.h, tools/sdk/ld/eagle.app.v6.common.ld.h, tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h
Apply most compatible changes needed to get the core compiling under GCC
7.2 to the main gcc 4.8 tree to ease porting for 3.0.0.
Update pgmspace.h with corrected and optimized unaligned pgm_read
macros.  Now pgm_read_dword in the unaligned case gives proper results
even if optimization is enabled and is also written in assembly and only
1 instruction longer than the pgm_read_byte macro (which also has been
optimized to reduce 1 instruction).  These changes should marginally
shrink code and speed up flash reads accordingly.
The toolchain should/will be rebuilt at a later time with this
optimization to ensure it's used in the libc.a/etc. files.
=> Clean up code to build under GCC7, fix pgm_read_unaligned

cores/esp8266/IPAddress.h, libraries/ESP8266NetBIOS/ESP8266NetBIOS.cpp
With this change plus the leamdns change, the core will compile
unmodified on GCC 4.8 and GCC 7.2, making keeping the two in sync for
3.0 much easier.
=> Clean up remaining non-LeaMDNS diffs from gcc4.8 to gcc7.2

libraries/Ticker/Ticker.h, libraries/Ticker/examples/TickerParameter/TickerParameter.ino
Fixes errors seen in #6281 and adds a slight test case to the examples
to ensure no compiler errors.
=> Fix Ticker callback casting.

package/build_boards_manager_package.sh, platform.txt
This makes the right value available in ARDUINO_SIGNING in the sketch.
The order of compilation makes the actual value of the define `ARUDINO_SINGING` inconsistently available to users. It might come in handy to check from user code if signature validation is enabled. This PR changes the moment in the build process the `Updater_Signing.h` file is updated.
Old order of build process:
1. The core contains a place holder file "Updater_Signing.h" with `#define ARDUINO_SIGNING 0`, this file is always readily available.
2. **Compile sketch**
3. Compile libraries
4. **Enabling binary signing** - generates "Updater_Signing.h" with `#define ARDUINO_SIGNING 1`.
5. Compile core
If the sketch is build and no cache is available, `ARDUINO_SIGNING` will be `0` during sketch compilation (step 2). …
=> Prepare signing before sketch is compiled

cores/esp8266/Arduino.h
memory references loaded to registers before the fence, in computation
within the fence. These values could have changed before xt_rsil()
(critical section start) was called.
addresses: https://github.com/esp8266/Arduino/pull/6274#issuecomment-511173751
=> Added memory fence to xt_rsil(). Without this the compiler may use

cores/esp8266/AddrList.h, cores/esp8266/IPAddress.h, cores/esp8266/core_esp8266_wiring_digital.cpp, cores/esp8266/gdb_hooks.cpp, cores/esp8266/umm_malloc/umm_malloc_cfg.h, libraries/ESP8266WiFi/src/WiFiClientSecureAxTLS.cpp, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h, libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.h, libraries/GDBStub/src/internal/gdbstub.c, tools/sdk/ld/eagle.app.v6.common.ld.h, tools/sdk/libc/xtensa-lx106-elf/include/sys/reent.h
Cleans up all warnings seen w/GCC 9.1 to allow it to track the main
branch more easily until 3.x.
Does not include Ticker.h "fix" of pragmas around a function cast we're
doing that GCC9 doesn't like, that will be addressed separately and
maybe only in the 3.0 branch.
=> Fix GCC 9.1 warnings (except Ticker.h)

cores/esp8266/core_esp8266_postmortem.cpp
This is a proposal 
~It seems this has no *visible* effect:~
```
__asm__ __volatile__ ("syscall"); // triggers gdb or does nothing
```
On `panic`/`abort`/`assert` called from user context, WDT happens due to the following `while(1);` and finally produces an exception with the right message (after the WDT reason and delay).
On ISR context, only the WDT reason is visible.
This commit permits to avoid WDT and show the right message from both user or ISR context.
Before #4482, `*((int*)0)=0` was used to trigger an hardware exception (similar to the WDT exception we have now, also showing an additional message unrelated to the real cause).
On real hardware exception, `raise_exception()` is not called.
fixes #6283 (thanks @mhightower83)
=> fix raise_exception()

cores/esp8266/core_esp8266_main.cpp, cores/esp8266/core_esp8266_wiring.cpp
The Arduino delay() (at least on AVR) cyclically calls yield(), whereas on Espressif SOCs the delay scheduling is quite different. In order to implement cooperative scheduling in a portable fashion, with global yield() and delay() in large sketches upholding the principle of least surprise, the delay() function must be supplanted. This patch allows that by the usual weak linkage approach.
Additionally, a weakly-linked loop_end() is added, that allows libraries to add special main-loop functionality, in case the Schedule recurrent et cetera functionality is not appropriate.
(EspSoftwareSerial is updated to 5.2.3, containing review results for circular_queue and minor internals)
=> Make delay() as overridable as yield() already is, and add overridable loop_end()

cores/esp8266/FS.h
The SPIFFS config object was defined in FS.h in its own namespace, but
is not made easily available like other SPIFFS and FS objects because of
a missing `using` statement.  Add it in FS.h
Fixes #6322
=> Add `using fs::SPIFFSConfig` to FS.h

cores/esp8266/Updater.cpp
Fixes #2090
The Updater checks that an update isn't already in progress on ::begin,
but when an error happens in the middle of an upload it's impossible to
actually reset this flag w/o a reboot.
Reset the state members (esp. _size) on any error condition so
that you can restart the transfer with a new ::begin.  Any error
condition is fatal, anyway, so there is no reason not to clear the
current state at that point.
=> Clear updater state on any error

tools/espota.py
From platform.txt, the binary to be uploaded is hardcoded to *.bin file.
This is not the expected behaviour when Signed Update is used.
Fixes: https://github.com/esp8266/Arduino/issues/6323
=> tools: fixed bug to select signed bin

cores/esp8266/core_esp8266_i2s.cpp
Fixes #6066
Preserve any existing sample rate for the I2S unit when performing an
`i2s_begin`.  If nothing has ever been set, default to 44.1KHz as
before.
=> Preserve prior bitrate for I2S begin

cores/esp8266/Arduino.h
It can be disabled with` -DPUYA_SUPPORT=0`.
closes #6359
=> enable PUYA flash chips support by default 

cores/esp8266/WString.cpp
=> wstring: fix concatenation from flash

cores/esp8266/uart.cpp
The core should never reference a library. This uses the pre-existing header file in the core to get the GDB function prototypes instead of referencing an external library with a hard-coded relative path.
=> Uncouple uart from GDBStub library

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
I'm pretty sure that was copied and pasted from another method and not updated.
=> wrong param documentation

tools/makecorever.py
The PR compares old and new and suppresses file writing if nothing changes.
This stops builds from oscillating between 5s and 20s, when there is NO change to the core and "core libraries".
=> Prevent rewriting core_version.h if content unchanged

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h
This commit makes it possible to create derived classes that connect to destination hosts through proxy servers (socks5 etc).
=> Set method _connectSSL as protected

libraries/ESP8266WiFi/src/include/ClientContext.h
... and standardizes processing of `_delaying` over lwIP callbacks
fixes #6459
=> ClientContext: rework an assert

cores/esp8266/HardwareSerial.cpp
After quick review comment, both of the two places in HardwareSerial.cpp shall use PolledTimeout - fixed by this PR.
=> Refactor HardwareSerial.cpp for consistent use of PolledTimeout

cores/esp8266/Esp.h, cores/esp8266/core_esp8266_features.h
Someone found out that on the ESP32, ESP::getCycleCount() is not ISR safe.
While the fix, inlining the machine code, is taken from ESP8266, on this platform I suggest additionally adding
`__attribute__((always_inline))`
to the respective functions to force the GCC to inline, no matter what compiler options are used by the build process.
This is a port of the fixing PR https://github.com/espressif/arduino-esp32/pull/3165.
=> Inline ESP::getCycleCount() to make it safe to call from ISRs

cores/esp8266/core_esp8266_timer.cpp
Placing timer functions in iram enables it to be used from pin ISRs too, or from timer interrupt itself.
=> move timer functions to iram

libraries/ESP8266WiFi/src/include/ClientContext.h
=> ClientContext: restore use of two different pending booleans for connect and write

package/package_esp8266com_index.template.json
Python renamed to python3, but not in package JSON.
=> Fix tool name to point to proper JSON entry

cores/esp8266/WString.cpp, tests/host/sys/pgmspace.h, tools/sdk/libc/xtensa-lx106-elf/include/sys/string.h
memmove_P is now in libc, so use it to allow WString to handle F()
pointers without errors.
Supercedes #6368
Fixes #6384
=> Add memmove_P, use it in String to ensure F() safety

cores/esp8266/HardwareSerial.cpp, cores/esp8266/HardwareSerial.h
Add HardwareSerial::updateBaudRate(unsigned long baud) to change the baudrate after ::begin() was called.
=> Add HardwareSerial::updateBaudRate(unsigned long baud) 

platform.txt, tools/sizes.py
Since IRAM is such a precious resource on the ESP8266, dump out its size
(and all other segments) at the end of the build process.
Ex:
````
Executable segment sizes:
IROM   : 338932
IRAM   : 27263
DATA   : 1476
RODATA : 2896
BSS    : 30304
Sketch uses 370567 bytes (35%) of program storage space. Maximum is 1044464 bytes.
Global variables use 34676 bytes (42%) of dynamic memory, leaving 47244 bytes for local variables. Maximum is 81920 bytes.
````
=> Add segment size printout to standard build process

tools/sizes.py
*(updated)*
Adding hints into segment size printout:
```
Executable segment sizes:
IROM   : 276348          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 28904   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1284  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 3064  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26040 )         - zeroed variables      (global, static) in RAM/HEAP 
```
=> segment size printout cosmetics

doc/libraries.rst
As mentioned by @d-a-v https://github.com/esp8266/Arduino/pull/6537#issuecomment-533703771
> This rotate library was proposed here as a PR and instead moved to an arduino library #4493
> [doc](https://arduino-esp8266.readthedocs.io/en/latest/libraries.html#improved-eeprom-library-for-esp-esp-eeprom) (should be moved to the 'Other libraries' paragraph below?)
> https://github.com/jwrw/ESP_EEPROM
Update EEPROM description with mention of current implementation limitations
Move ESP_EEPROM to Other Libraries, update description from upstream README
Add https://github.com/xoseperez/eeprom_rotate to Other Libraries as an alternative
Note:
Both libraries depend on #6543 
ESP_EEPROM is reimplementing EEPROM class, so the default address would be different from the original library when upgrading …
=> Update EEPROM library documentation

libraries/EEPROM/EEPROM.cpp, libraries/EEPROM/examples/eeprom_read/eeprom_read.ino, libraries/EEPROM/examples/eeprom_write/eeprom_write.ino
Add debug printouts when EEPROM calls fail, even if the API doesn't
allow returning a success/failure code.
Adds error checking to the example to make it explicit that when you
call EEPROM::commit(), you need to look at the result code in your code.
Fixes #6551 , or would fix it if there was error checking in the MCVE.
=> Add EEPROM debug printouts, error check to example

doc/installing.rst
The Mac requires special handholding to allow SSL connections for
get.py, so document those for end users.
Hopefully this will avoid issues like #6528 which can be very perplexing to end users...
=> Add info about installing python3 on Mac, Linux

doc/filesystem.rst
Trivial addition to filesystem upload documentation.
Supersedes #2904 which cannot merge due to file renames and massive
changes to the filesystem.rst file since it was pushed.
Original from @seanspotatobusiness was approved by @igrr.
=> Minor FS documentation change from #2904

doc/installing.rst, doc/reference.rst
Adds a section on interrupts to the docs and lists the restrictions
and warnings about running long tasks.
Fixes #6428
=> Add interrupt section to docs

.travis.yml, tests/common.sh, tests/run_CI_locally.sh
=> use arduino IDE stable in CI

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
The function accidentally compared the current location instead
of the passed in (new) location, which didn't match intended
logic and the code comment.
=> Fix setURL() handling of path-only parameters

cores/esp8266/WString.cpp, tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h
GAS doesn't support the C language idiom of catenating two strings
together with quotes (i.e. "x" "y" === "xy").
Specify the section attribute fully in the section attribute, instead,
to allow this.
Fixes #6575 and probably #6574
=> Replace ASM block w/C macro for PSTR

package/build_boards_manager_package.sh
tag '0.0.1' in the repository should trigger the build of a special '-0.0.1' release visible in arduino board manager.
This is intended to provide a regular snapshot of git head to arduino board manager.
This way of releasing alpha versions is a workaround to https://github.com/arduino/Arduino/issues/6012
closes #6511 
*edit*: https://twitter.com/mbanzi/status/1173532857857400832
=> prepare alpha channel release builder

tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h
Fixes #6590
The ASM block that implements the read-uint32-unaligned returns a
uint32_t.  The old code was doing a cast like `(float)(uint32_t ret)
which actually goes and creates a new float of the positive uint value
(approx, of course due to exponent and sign bits) which is not correct.
C and C++ don't have a concise way to convert the bits in a register
from int to float interpretation, so avoid the whole issue by making a
new function which uses the same ASM block as the read-uint32-unaligned,
just make the destination and return values as floats.
=> Fix pgm_read_float_unaligned macro

cores/esp8266/base64.cpp, cores/esp8266/base64.h
This is another instance in the core library where we pass in read-only
parameters as pass-by-value, where in the case of String() that
is inefficient as it involves copy-constructor/temp string creations.
=> Base64::encode : const correctness / String by reference passing

platform.txt
`esptool.py`'s  `--trace` is a debug option, not a verbose option
fixes #6605
=> remove esptool.py --trace option

cores/esp8266/Esp.cpp
=> Minor cleanups in ESPClass

libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino, tools/sdk/include/sntp.h
This removes definitions relating to the built-in SNTP client that
are LwIP v1 specific. Instead of duplicating these pull in the
LwIP header that correspond to the required functions depending on
the version of the stack being used.
Without this fix calls to sntp_getserver() work but return invalid
data and can lead to stack exhaustion.
Update the NTP-TZ-DST example to use the Arduino sntp.h header
rather than duplicate the conditional checks to use the LwIP header.
Tests:
- Build against a simple SNTP API demonstratin app and all
LwIP configurations. Verify that the app runs for an extended
period and that the expected results are obtained.
=> Remove duplication and incompatible declarations in sntp.h

libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp, libraries/ESP8266mDNS/src/LEAmDNS_Transfer.cpp
When trying to resolve mdns hostname using lwip built-in resolver (`WiFi.hostByName("something.local")`), LeaMDNS responder does not construct a response that lwip expects. While it does preserve the request ID here:
https://github.com/esp8266/Arduino/blob/48ca7cfce3de99f1d906e95938a67895e73f7f4a/libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp#L248-L250
This ID is never set when preparing the message:
```
[MDNSResponder] _parseQuery: Legacy query from local host 10.0.0.22, id 30!
...
[MDNSResponder] _prepareMDNSMessage: ID:0 QR:1 OP:0 AA:1 TC:0 RD:0 RA:0 R:0 QD:1 AN:1 NS:0 AR:0
...
```
(debugging message could be improved though)
=> MDNS: fix legacy unicast responses

cores/esp8266/cont.S
cont_run is only called by loop_task(), which is not going to execute
during an IRQ and is stored, itself, in flash.
cont_yield cannot be called from an IRQ (since it's illegal to yield
inside IRQs), so move it out of IRAM, too.
Saves ~71 bytes of IRAM
=> Move cont_run/cont_yield out of IRAM

libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
We need to disable HTTPUPDATE_1_2 support when HTTPCLIENT_1_1
compatibility is not desired to avoid using methods that are
disabled.
=> Fix build with -DHTTPCLIENT_1_1_COMPATIBLE=0

libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino
This change expands the NTP-TZ-DST example to list the active
SNTP servers. It lists the IP address server name (if used) and
reachability in ntpq style octal format.
Tests:
- Build against all LwIP stack configurations and correct
operation with a single SNTP server
- Vary connectivity to an SNTP server and check reachability
updates
- Configure 3 SNTP servers by name
- With a patched LwIP stack that supports simultaneous DHCP
and DHCPv6 SNTP servers check that all server details are
listed and update correctly during operation
=> Expand NTP-TZ-DST example to list SNTP servers

.travis.yml, tests/ci/build_docs.sh, tests/ci/style_check.sh
Ubuntu Trusty used in CI is EOL since may 2019, trying with Bionic(18.04)
=> CI: trusty (u14.04) -> bionic (u18.04)

tests/common.sh
Windows installers place each version of Python in their own, uniquely
named directory.  Can't programatically override w/free Chocolatey, so
use the shell and figure it where it installed it dynamically.
=> Dynamically find the Python3 dir on Windows CI

tests/device/Makefile, tests/device/libraries/BSTest/requirements.txt, tests/device/libraries/BSTest/runner.py, tests/device/libraries/BSTest/xmerge.py, tests/device/libraries/BSTest/xunitmerge, tests/device/test_ClientContext/test_ClientContext.py, tests/device/test_http_client/test_http_client.py, tests/device/test_http_server/test_http_server.py
The Python3 migration didn't include fixes for local scripts in the
device test tree.
Fatal build and run Python errors fixed.
The last update to xunitmerge is ~5 years ago, so it looks to be
unsupported now.
Use a local copy of the two components to allow patching to work with
Python3.
The serial test seems to send garbage chars (non-ASCII/etc.), so use a
codepage 437 which supports all 255 chars.
Fixes: #6660
=> Fix Python3 errors for device tests

libraries/esp8266/library.properties
In some cases, "esp8266" library archive is used by arduino builder but is non existent because there is no source file.
Disabling building this archive fixes #6663.
=> fake library directory: prevent building an archive

cores/esp8266/Schedule.cpp, cores/esp8266/Schedule.h
I have a use case for the ESP8266 core schedule class that needs the capability to let recurrent, delayed functions run immediately on the next iteration of the scheduler without taking into account a remaining delay or repeat timeout.
This PR [originally added] an optional parameter `const std::atomic<bool>* wakeupToken` to `schedule_recurrent_function_us()`. This was changed, after review comments, into a `std::function<bool(void)>` alarm polling callback.
The remaining delay or the logic by which the scheduled function return value determines whether to keep scheduling for execution or to be removed from scheduling is unaltered by the alarm.
[CoopTask release 2.0.0](https://github.com/dok-net/CoopTask/releases/tag/2.0.0) depends on this PR for it's new Semaphore with milliseconds …
=> Wakeup delayed scheduling

libraries/ESP8266HTTPUpdateServer/library.properties
Newer version of Platformio generates a warning
=> Remove non-ASCII or non-UTF8 character

.travis.yml, doc/esp8266wifi/bearssl-server-secure-class.rst
CI: move longer jobs before smallers
doc: fix typo in bearssl links
=> fix documentation, CI: minor update

doc/ota_updates/readme.rst
Elaborate more on what the flag does, and why it might be wanted. Ended up writing more than I intended... (correcting 'overriding').
=> Re-wording of ATOMIC_FS_UPDATE documenation

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
=> Remove useless call to setContentLength()

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
Apparently I messed up testing #6715 and something broke. This rolls back that PR.
That means #2132 remains closed with no action.
=> Rollback setContentLength removal (#6715)

cores/esp8266/FS.h, cores/esp8266/HardwareSerial.h, cores/esp8266/libc_replacements.cpp, cores/esp8266/time.cpp
Added missing time.h include. The path is relative (instead of simply using ``<time.h>``) so it doesn't conflict with Time.h of the Arduino Time library. See https://github.com/esp8266/Arduino/issues/6714#issuecomment-551554120 for details.
=> Add missing time.h include, use relative include path on time.h includes

libraries/ESP8266WebServer/README.rst
Getting the body of a POST request is a very common use-case in ESP8266WebServer. But it's now undocumented and very hard to find out how without reading whole `PostServer` example or source code. So I document it in README.
Also, I think there should be a `requestBody()` method. It's more reasonable than `arg("plain")`.
=> add docs: how to get POST body in ESP8266WebSever

cores/esp8266/IPAddress.h
`espconnn.h` references ipv4_addr_t, so it seems appropriate it be defined here also.
If `#include <IPAddress.h>` added to MCVE, closes #5753. 
The change to `espconn.h` suggested by the OP
```
#ifndef ipv4_addr_t
#define ipv4_addr_t ip_addr_t
#endif
```
sets off needing to define `ip_addr_t`, etc, so is not suitable.
=> Add `ipv4_addr_t` for espconn/LwIP1.4 compat

doc/installing.rst
=> Mention erasing arduino15 contents before installing git

variants/nodemcu/pins_arduino.h
Given that most nodemcu boards are based on the ESP12 boards, the definition of the builtin led is now changed to 2.
In addition, for those nodemcu boards that have an additional LED on the board connected to gpio16, an additional define is added called LED_BUILTIN_AUX.
Fixes #4715
=> Puts to rest the confusion about the builtin leds for nodemcu boards

README.md
=> Add some useful links

libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino, libraries/esp8266/examples/SerialStress/SerialStress.ino
Due to user request, the ctor/begin() pair is now backward compatible with EspSoftwareSerial releases 5.0.4 and prior (only for the common cases with complete default argument use).
=> Updated EspSoftwareSerial brings backward compatibility

cores/esp8266/WString.h
Tasmota uses a lot of `String` with constructs like below:
```
str->replace("aa", "bb);
str->replace(F("cc"), String(num));
str->startsWith(F("prefix"));
str->endsWith(F("suffix"));
```
Currently for any non `String` argument, the compiler silently instantiates a new `String`object and deletes it after the call. This generates more than 1k of not very useful code.
This PR adds explicit methods to deal with common arguments `const unsigned char *` and `const __FlashStringHelper *`. It does not change the fact that a `String` object is created then deleted, it just reduces redundant code.
With this change, we see a 1k code size reduction with Tasmota.
=> WString explicit converters to reduce Flash size

cores/esp8266/WString.cpp, cores/esp8266/WString.h, tests/host/core/test_string.cpp
Fixes #5061
Adds a concat(const char *data, int len) method which allows arbitrary
sequences of data (including ones w/embedded \0s) to be appended to a
String.  May be useful for certain MQTT operations.
Adds sanity test for the feature to host suite
=> Add String::concat(char*, len) to allow non null-term strings

cores/esp8266/Schedule.cpp
Fixes #6764
Here's my take - unknowingly working in parallel to @d-a-v - on the same issue #6764.
Copy and pasted, then adapted, the code from `run_scheduled_recurrent_functions`
Also, extended the MCVE to end re-scheduling at one point, in order to show that the end condition still works:
```c++
#include "Arduino.h"
#include "Schedule.h"
void cp()
{
static int c = 0;
if ((c++ % 10000) == 0) Serial.printf(".");
if (c < 100000) schedule_function(cp);
}
void setup()
{
schedule_function(cp);
}
void loop()
{
static int l = 0;
if ((l++ % 10000) == 0) Serial.printf(":");
}
```
The result:
```
:.:.:.:.:.:.:.:.:.:::::::::::::::::::::::
```
=> Fix issue with functions scheduled from scheduled functions

libraries/ESP8266WebServer/examples/PostServer/PostServer.ino
In order to be displayed properly by a browser the HTML should be returned as text/html.
=> Root page should be of type text/html

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiSTA-WPS.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp, libraries/ESP8266WiFi/src/include/ClientContext.h
Where async event scheduling uses ``delay()``/``esp_yield()`` and ``esp_schedule()``, use same wording and properly identify source / target site pairs.
This is a purely cosmetic PR.
This PR helps identify these sites and aids in (my) discussion about the effects this pattern has on the
compatibility to (AVR) Arduino-style overridable weak-binding yield()/__yield() based 3rd party scheduling [libraries](https://github.com/dok-net/CoopTask).
=> Comments for target and source sites of async scheduling

platform.txt, tools/upload.py
PR #6765 introduced an incompatibility with the existing Java uploaders
for SPIFFS and LittleFS,  breaking them because of the upload.py
parameter format change to support single stage erase/upload.
Add in patch to silently eat the single --end and to parse the write
address and filename properly as generated by calls from the plugins,
while retaining compatibility with the current IDE changes.
=> Make upload.py compatible with existing FS upload

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
remove `clear()` before `beginInternal()` so _location is not cleared before its passed to `beginInternal()`
Fixes #6778
=> fix http client redirects (broken from const String& changes)

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
Fix typo to make timeout 1s instead if 1ms, as originally intended.
=> Fix typo in mode timeout loop

libraries/ESP8266SSDP/ESP8266SSDP.cpp, libraries/ESP8266SSDP/ESP8266SSDP.h
Supercedes #2806
Make SSDP::schema(WiFiClient&) use a by-ref (reduce stack use)
Add a SSDP::schema(Print&)
From @Palatis' original PR:
useful when using AsyncWebServer.
=> [SSDP] add `schema(Print &) const`

cores/esp8266/core_esp8266_main.cpp
This is a cosmetic change in master, that would kindly allow the use of CoopTask and similar pattern libraries to release adapted code that just-works while PR #6782 is in review.
=> Weak binding lessens version dependency between ESP8266 and MT library

libraries/ESP8266WebServer/examples/SDWebServer/SDWebServer.ino
Fixes #2481
Send a 0-len chunk when the directory is completed (in a chunked HTTP
transfer) to terminate the HTTP transfer properly.
=> Terminate the chunked printDirectory in SDWebServer

cores/esp8266/HardwareSerial.cpp, cores/esp8266/HardwareSerial.h, cores/esp8266/uart.cpp, cores/esp8266/uart.h, tests/host/common/MockUART.cpp
=> Implement invert for HardwareSerial

cores/esp8266/StackThunk.cpp, libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino
Fixes #6811 which found an issue where connecting to scripts.google.com
would *occasionally* cause a crash.  On inspection, it was found that up
to 5828 bytes of stack were used once in a while, so expand the stack to
5900 bytes to cover this case plus a little extra.
=> Expand BSSL stack

bootloaders/eboot/eboot.c
The eboot command was cleared from the rtc mem before the firmware copy
making it possible for a power failure during an OTA update to brick the
esp until the firmware was loaded via USB because of a partial firmware
copy that would never be restarted.
Moving the eboot_command_clear to after the copy ensures that any partial
copy is restarted at next power on.
=> Move eboot_command_clear to after firmware copy.

tests/host/common/mock.h
This PR fixes the include order of Arduino.h in mock.h.
=> Using clockCyclesPerMicrosecond() in host build fails

cores/esp8266/sntp-lwip2.cpp
=> Conflict with pre-included Arduino.h (the indirect includes thereof)

cores/esp8266/core_esp8266_si2c.cpp
Finally figured out what I'd done wrong with the earlier commit.  No -a in a local commit!
issue #2162
Added devyte's PolledTimeout in a nested loop replacing the original WAIT_CLOCK_STRETCH().  The outer loop exits if SCL goes high or the loop times out.  The inner loop does a yield() every 5ms while we're waiting.
Additionally, two small changes to twi::status that add a clock stretch test before we exit if we find SCL stuck low, and the trailing **if (!write_start())** at the end is removed as it leaves SDA low, killing the bus.
=> added clock stretch yield, [issue 2162] fixed twi::status

libraries/GDBStub/examples/gdbstub_example.ino, libraries/GDBStub/src/internal/gdbstub.c
Avoid a warning by not including the unneeded "user_interface.h" from
gdbstub.c.  Leftover from original stub code from the SDK, this include
is unnecessary in the Arduino core.
=> Remove user_interface.h from gdbstub includes

cores/esp8266/core_esp8266_si2c.cpp
Bonehead mistake: I left the multipliers in there when they're now pointless since the PolledTimout isn't frequency sensitive.
=> removed TWI_CLOCK_STRETCH_MULTIPLIER

libraries/ESP8266WebServer/src/ESP8266WebServer.h
=> webserver: fix sending char*

cores/esp8266/Print.cpp
Fixes #6524
Should help with speed of output when printing large flash strings to
things like a file or a TCP connection.
Use a 128 byte chunk in a temp buffer to send data using write(),
reducing the # of write calls by ~127x.
=> Use 128B chunks instead of 1B writes in Print::print(FlashStringHelper)

libraries/ESP8266WiFi/src/include/UdpContext.h
This commit avoids OOMs on an udp corner case where a delay() in the main
loop would allow memory filling.
A memory leak has been observed with such semantically forbidden delay,
unsolved yet, and preventing to use a simple counter instead of walking
through a linked list.  The count limit is however small.
fixes #6831
=> udp: limit buffer depth

variants/nodemcu/pins_arduino.h
=> NodeMCU v1.0 board option "Builtin Led" define overrides variant define

cores/esp8266/Updater.cpp, cores/esp8266/core_esp8266_si2c.cpp
heavily modified to insure that the 'inline helpers' are truly inline (they are, verified in the dump)
=> change to make inline helpers truly inline [issue 6875]

tests/common.sh
Chocolately seems to be unstable and cannot specify an install path to a
package, so use the original Python.org install ZIP file for Windows
Travic CI builds
=> Fix Windows CI build

cores/esp8266/umm_malloc/umm_local.c
also called through xPortGetFreeHeapSize, umm_free_heap_size, ...
=> Added missing "if (umm_heap == NULL) {..." to umm_free_heap_size_lw

cores/esp8266/Esp-version.cpp
This saves about ~ 60 bytes of flash usage (50% reduction of
the total function size)
=> Code size optimisations for ESP.getFullVersion()

cores/esp8266/WString.cpp, doc/PROGMEM.rst, libraries/ArduinoOTA/ArduinoOTA.cpp, libraries/DNSServer/src/DNSServer.cpp, libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp, libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer-impl.h, libraries/ESP8266WebServer/examples/FSBrowser/FSBrowser.ino, libraries/ESP8266WebServer/examples/SDWebServer/SDWebServer.ino, libraries/ESP8266WebServer/src/Parsing-impl.h, libraries/ESP8266WiFiMesh/src/ESP8266WiFiMesh.cpp, tests/device/test_WiFi_events/test_WiFi_events.ino
Use the proper api (::clear(), isEmpty()) instead of doing
comparisons/assignments of empty strings. Also fix mixture
of tabs and spaces in the source code.
=> Various String handling cleanups

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h, libraries/ESP8266WebServer/src/ESP8266WebServer.h
Doing returns with String/FlashStringHelper conversion for every
case means that the code for doing that is duplicated, which
is wasteful. doing it only once saves about 250 bytes (50%) of
code size.
=> PROGMEM footprint cleanup for responseCodeToString

cores/esp8266/core_esp8266_si2c.cpp, cores/esp8266/umm_malloc/umm_local.c
Corrects the fixed I2C bus clock selections and allows slower bus clocks down to ridiculously low bus speeds if you need that.  Originally prompted by Earle's comment in https://github.com/esp8266/Arduino/issues/2524 about computing the bus clock timing.
Additionally, the dead Twi::stop was removed.  The compiler was removing it in slave compiles anyways, as it wasn't called by any of the functions except for one oversight in the slave state machine.  Slaves can't issue STOP commands.  Although the Twi::stop was listed as an exposed function, it wasn't linked from Wire.h, so it was optimized out.
=> Issue2524 allow clocks below 100KHz

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
This improves both performance due to fewer memory allocations/copies
as well as reduces code size by ~ 25% (150 bytes)
=> Reduce temporary string creation in HTTPClient::sendHeader

libraries/LittleFS/src/LittleFS.h
Fixes #6958
To match SPIFFS, we get rid of the "." and ".." dirents when we open a
directory on LittleFS.  Do the same on a rewind().
=> Skip . and .. on LittleFS::dir::rewind()

libraries/LittleFS/src/LittleFS.cpp, libraries/LittleFS/src/LittleFS.h
Fixes #6955
LittleFS was updating the timestamp on any close, not only for files
when they were opened for writing.  This could lead to excessive writes
to the flash.
Preserve the LFS flags, and only update the timestamp if the file was
opened for writing.
=> Only update LittleFS timestamp when opened write

libraries/SDFS/src/SDFS.h
Forgot to add a Dir->fileTime override, resulting in it always returning
(time_t)0, or Jan 1, 1970.
Add the override, returning the proper lastWriteTime.
Fixes #6981
=> Add SDFS::Dir::fileTime callback

libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
The problem was that the library was assuming that `FS::exists()` would return false for directories, which is true for SPIFFS, but not for LittleFS. I changed the implementation to be compatible with both.
I don't like using `fs.open()`, but I couldn't find any better way to check if something is a directory or a file. If there is such a thing, please point me in the right direction and I will be happy to use that instead.
=> Add LittleFS support to ESP8266WebServer.serveStatic()

libraries/LittleFS/src/LittleFS.cpp
To mimic SPIFFs behavior, we automatically create subdirectories when a
file is opened in a subdir.
The check mixed up a bitmask check with a boolean AND.  Fix it.
=> Fix boolean/logical & mixup in LittleFS open

libraries/ESP8266WiFi/src/WiFiServer.cpp, libraries/ESP8266WiFi/src/WiFiServer.h
When calling WiFiServer with a 'port = 0', a free port is auto-selected, but this port isn't updated to the '_port' member. In addition, the used port is made accessible.
=> Updating _port to really used port and made _port accessible

package/package_esp8266com_index.template.json
Fixes #7006
mklittlefs for 32-bit Linux disappeared from the packages.json.  Looks
like a transient build problem on the older eqt release (later builds
look fine).  Add it back, pointing to the first successful mklittlefs
build for lin32.
=> Add back mklittlefs for linux32 target

package/package_esp8266com_index.template.json, tools/boards.txt.py
Updated `packagegen` to use `newfilestr` instead of `filestr` when writing the JSON file.
Three missing boards are now in package/package_esp8266com_index.template.json.
@d-a-v please check this. I am not sure where this file gets used or how to
test this change. Before making the change, I was seeing a different result
between --package and --packagegen.
=> Missing boards in package_esp8266com_index.template.json

libraries/ESP8266WiFi/src/CertStoreBearSSL.cpp
In some cases, `initCertStore` may need to be called multiple times
(i.e. to update certs w/oa reboot).  In that case, the saved file names
leaked when the new ones were `malloc()`'d.
Fix by freeing the old strings, if present.
=> Remove memory leak on multiple calls to initCertStore

cores/esp8266/Esp.cpp
This function has excessively long datastrings that can
better be stored in flash, reducing runtime memory footprint.
Also detailed formatting only makes sense when there is an
exception or a watchdog. In other cases instead of printing
an unhelpful "flag: 0" we can just return the ResetReason, which
is much more readable.
Saves about 120 bytes of (data) memory.
=> Reduce mem footprint of ESP.getResetInfo()

libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer-impl.h
Because gzip-compressed OTA is cool
=> allow ".bin.gz" filter in update server file selector

tests/host/common/Arduino.cpp
On host, can work just like plain `yield()` there - do nothing at all.
=> host build: optimistic_yield() wrongly delays() instead of avoiding excessive yields

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
Looks like this was introduced in #5250 - it missed the need to clear `_canReuse` in `setUrl()` if the new URL has a hostname and is not just a path.  Without it `disconnect()` will assume it can reuse even tho the hostname may be different.
fixes #7033
=> Fix redirect support in http client.

cores/esp8266/Esp.cpp
doing if/else snakes for something that is a switch/case
is wasteful, as it repeatedly evaluates the same if() condition.
Also repeating strcpy_P is adding code bloat.
This simplification reduces size from 111 to 41 bytes.
=> Code size optimisation of ESP.getResetReason()

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
sendRequest has a major problem when sending a big payload, the comparator in the IF loop has its two operators changed at the same time, so the last part of payload is never sent. This is seen when you try to send a payload that needs more than one operation.
The modification has been tested for a 1500 bytes payload.
*edit from maintainer:* fixes #7049
=> Fixes large payload issues for sendRequest

cores/esp8266/WMath.cpp
Inspired by Servo.cpp's `improved_map`, this superseded that code, and has better performance (identical to prior WMath implementation).
I expect this is better used to replace the core implementation, then drop "improved_map" from Servo.cpp, than keep it local and have a map() function that may be compatible but works horribly ;-)
=> Fix WMath's map() implementation for inverse/round-trip mapping

libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
Fixes #6984
When a directory index is requested with an explicit index.html, follow
the original webserver order and check for: index.htm, index.htm.gz,
index.html, index.html.gz, in order.
Fixes the regressions introduced in 9f2cfb8 and 6768116
=> Fix serach order for index.htm(l)(.gz) files

cores/esp8266/Print.cpp, cores/esp8266/Print.h, cores/esp8266/core_esp8266_noniso.cpp
Fixes #7043
Two slightly different custom routines were implemented by hand in
dtostrf (an AVR-lib non-ISO function) and Print.  This resulted in
inconsistent output of float/double vars when rounding was needed.
Replace them all with a call to sprintf(), removing the duplicated, not
quite correct code.
Print(String(float)) and Print(float) now generate the same output.
=> Use sprintf to output floats in Print/dtostrf

tools/platformio-build.py
This will allow users to set any linker script from `platformio.ini` file using the following syntax:
```ini
[env:esp01]
platform = espressif8266
framework = arduino
board = esp01
board_build.ldscript = custom_ldscript.ld
```
This is a more correct way of specifying it in comparison with using the `-Wl,-T` flag.
=> Allow using custom linker scripts in PlatformIO build script

package/build_boards_manager_package.sh
This PR allows the package builder to generate more than one alpha release version.
Previously only version 0.0.1 was considered as an alpha version.
With these changes, any 0.0.x version will be generated as experimental and it will be easy to integrate unmerged-yet pull requests into an alpha release to help testing without using git.
These changes are transparent for the regular release process.
=> package builder: updates for alpha releases

cores/esp8266/time.cpp
@arendst Can you try it ?
fixes #7092
=> SNTP: backport espressif sntp api for lwip2

doc/ota_updates/readme.rst, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
Made severing connections optional as per the patch in the issue.
Also fixed a minor spacing issue.
=> Resolved issue #3359

libraries/ESP8266WebServer/examples/PathArgServer/PathArgServer.ino, libraries/ESP8266WebServer/src/Uri.h
=> Add flash helper constructor to Uri

cores/esp8266/time.cpp
fixes #7107 
@Jason2866 do you confirm tasmota fits in its previous size ?
About that, are you using compressed OTA ?
=> simple TZ api: bypass sprintf/sscanf: + 7KB

libraries/ESP8266WiFi/src/include/UdpContext.h
This follows #7036 where udp pbuf chain handling is made hairy because of interleaved information fragment introduced with IPv6.
@szekelyisz Could you please test this change ?
fixes #7124
=> udp: fix again pbuf management

libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino
Due to recent changes, environment variable `TZ` may not be set up after `configTime()`.
In the example, inform user when it is not defined.
related: #7141
=> avoid printing nullptr string

cores/esp8266/Updater.cpp, cores/esp8266/Updater.h, libraries/ESP8266WiFi/src/BearSSLHelpers.cpp
Fixes #7145
When doing a signed update, the signature calculation can use a lot of
stack, so move it silently to the BearSSL second stack.
Also fix a memory leak of signature-bytes found by @JiriBilek
=> Use 2nd stack for update signature verification

cores/esp8266/StackThunk.cpp
As found by @d-a-v, if the malloc() used to get the BearSSL stack does
not succeed abort() immediately.
=> Abort if BearSSL stack allocation fails

tests/platformio.sh
There is no `stage` branch anymore, CI build should use the development branch instead.
=> Use development branch of espressif8266 platform in PlatformIO build

cores/esp8266/Esp.cpp, cores/esp8266/core_esp8266_postmortem.cpp, cores/esp8266/coredecls.h
=> Attribute `__real_system_restart_local()` as `(noreturn)`

cores/esp8266/Tone.cpp, cores/esp8266/core_esp8266_wiring_digital.cpp
Add 2 comments since I found out where the 5KHz upper limit on Tone output frequency was, apparently added for compatibility with the Arduino library some time in the past.
If you want the full 20KHz audio frequency range, change the two lines in Tone.cpp at line 38 to:
```cpp
high = std::max(high, (uint32_t)25);  // new 20KHz maximum Tone frequency
low = std::max(low, (uint32_t)25);
```
=> Tone limit 20KHz 

tools/platformio-build.py
Follow up of #7180, there was no way to enable the `-DFP_IN_IROM` flag when generating the ld script.
=> Ability to define -DFP_IN_IROM when generating ld script

libraries/ESP8266WiFi/src/include/ClientContext.h, libraries/ESP8266WiFi/src/include/UdpContext.h
credit: Simon Arlott @nomis - similar to #6541 for TCP
=> Fix TCP send to IPv6 link local addresses

cores/esp8266/MD5Builder.cpp, cores/esp8266/MD5Builder.h
In order to guarantee exception-safety I used `unique_ptr` to `uint8_t[]`, with `std::nothrow` decorator.
I cannot mark the functions as no-except because I don't know if the called functions (especially the Stream implementations) are no-except.
I also fixed the const-correctness of const member functions, such as toString() and getters. 
I executed the host tests, I still need to run tests on the ESP8266, but this is the first time that I contribute with you, so I have to study how to setup and run your tests suite on my device.
=> MD5 Builder: Rework for unqiue_ptr instead of malloc for internal dynamic buffers.

libraries/ESP8266mDNS/src/LEAmDNS.cpp
=> mDNS: protect MDNSResponder::queryService against misuse

cores/esp8266/Esp.cpp, cores/esp8266/Esp.h, cores/esp8266/PolledTimeout.h, cores/esp8266/core_esp8266_main.cpp, tests/host/common/MockEsp.cpp, tests/host/common/mock.h
Then ESP.getCpuFreqMHz() can be optimized to use F_CPU and be constexpr.
polledTimeout using F_CPU instead of the dynamic ``system_get_cpu_freq()`` anyway, I see no issue.
On review, please consider this, in `core_esp8266_main.cpp`:
```
void preloop_update_frequency() __attribute__((weak));
void preloop_update_frequency() {
#if defined(F_CPU) && (F_CPU == 160000000L)
REG_SET_BIT(0x3ff00014, BIT(0));
ets_update_cpu_frequency(160);
#endif
```
Could this be turned into dynamic frequency switching?
=> Use F_CPU if (?) CPU frequency switch is compile-time only

cores/esp8266/Tone.cpp, cores/esp8266/core_esp8266_waveform.cpp, cores/esp8266/core_esp8266_waveform.h, cores/esp8266/core_esp8266_wiring_pwm.cpp
Allow the PWM to specify sub-microsecond waveform edges, as have been
proposed by @dok-net and me.  No other changes intended.
This will increase the linearity at 30 and 40 kHZ PWM rates, but leave
most other things unaffected.
=> Allow waveforms to be specified in clock cycles

libraries/ArduinoOTA/ArduinoOTA.cpp, tools/espota.py
The OTA script was not reporting the actual reported upload status from
the ESP8266, and instead always printed "Result: OK" no matter what
happened.
Now check for ERROR or OK in final message (and ensure the message is
not accidentally merged with the final byte count) and report properly.
Fixes #7162
=> Fix espota completion success/fail check

libraries/ESP8266WiFi/src/WiFiClient.cpp
Fixes exception 28 in `IPAddress(const ipv4_addr* fw_addr);` with null ip_addr
pointer passed in by `WiFiCient.cpp localIP()`. I assumed that `localIP()`
was called shortly after _pcb became null.
=> Null pointer call from WiFiClient::localIP() to IPAddress

libraries/ESP8266mDNS/src/LEAmDNS.h
=> Add isRunning getter to check is ::begin already called

libraries/ESP8266mDNS/src/LEAmDNS_Helpers.cpp
=> Changing listen to listen the current iface only instead of 0

cores/esp8266/Tone.cpp, cores/esp8266/core_esp8266_waveform.cpp, cores/esp8266/core_esp8266_waveform.h, cores/esp8266/core_esp8266_wiring_pwm.cpp, libraries/Servo/src/Servo.cpp, libraries/Servo/src/Servo.h
Future-proofing #7122, newly introduced public `startWaveformCycles()` is more aptly named `startWaveformClockCycles()` (like in rest of core API for this type of use).
Fix/clarify comments.
Fix redundancies in Tone, end Tone waveform on exact period limit for proper sound.
Fix redundancies in wiring_pwm.
Extend Servo to map in-use pins, Tone already has this.
=> Pickup some loose ends from PR #7211

tests/host/fs/test_fs.inc
Verify that a file is truncated on opening with w+ even if no data is
written to it, for all FSes.
=> Add test for FS::open("w+")

doc/esp8266wifi/station-class.rst
It might be the thing in some other doc files but I only noticed it here
=> Fixed misplacement of back quotes

cores/esp8266/esp8266_peri.h
Documentation that bit USTX in UART status register USS(u) / U0S / U1S is not mirroring TX level as expected but always reads 0, see issue #7256
=> Document USTX in USS/UxS not working as expected

package/README.md
Update release instructions to reflect reality, add copy-paste checklist to ease issue.
=> Update release instructions

libraries/ESP8266WiFi/src/BearSSLHelpers.h
The BearSSL SigningVerifier was moved to the 2nd stack because some uses
required much more stack than available on the normal stack.
Add a reference to the second stack on object creation (which will
allocate it, if there is no BSSL stack already allocated), and delete
that reference on exit.
Fixes #7288
=> Allocate BSSL stack for SigningVerifier

libraries/ESP8266WebServer/src/detail/mimetable.cpp, libraries/ESP8266WebServer/src/detail/mimetable.h
Superseded #7311 
The current mime-type array is based on `Entry` structure with fixed size string that waste a lot of Flash space (~400 bytes):
```
struct Entry
{
const char endsWith[16]; 
const char mimeType[32];
};
```
I replaced with standard PROGMEM strings.
I also added `#define MIMETYPE_MINIMAL` to reduce the footprint to mime-types that are strictly necessary: `html`, `txt`, `gz`
Overall this saves 1kB for Tasmota.
=> Flash size reduction for mime-type

cores/esp8266/time.cpp
fixes #7319
Timezone sign was incorrectly set
=> Fix configTime(tz,dst,)

doc/libraries.rst
Fixes #7322.  Because of UMM internals, the largest `malloc()`able block
will be smaller than the largest contiguous free RAM block.  Note in the docs.
=> Document ESP.getMaxFreeBlockSize() != max malloc size

doc/faq/readme.rst, doc/libraries.rst
This PR adds an extra line of documentation and a new FAQ entry relating to #3072, on how to enable WiFi connectivity after implementing deep sleep with `WAKE_RF_DISABLED`
=> Add documentation on recovering from deep sleep with WAKE_RF_DISABLED

tools/elf2bin.py
Per https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp
> Unlike TemporaryFile(), the user of mkstemp() is responsible for deleting the temporary file when done with it.
`read_segment()`'s `dumpfile` was never deleted, producing 5 'segment' files each build.
Instead, this patch creates a temporary directory which is later used for objcopy output. `TemporaryDirectory()` context manager will handle the deletion.
Plus, some minor refactoring to reduce line length and add some pythonisms (hopefully, not too much)
Noticed this issue accidentally by inspecting a specific Windows PC install using WSL circa January. `/tmp` was ~2.5GB and there was a *lot* of files.
=> elf2bin.py objcopy cleanup

tests/host/common/MockWiFiServerSocket.cpp, tests/host/common/MocklwIP.cpp, tests/host/common/include/UdpContext.h, tests/host/sys/pgmspace.h
=> emulation on host: various fixes

cores/esp8266/CallBackList.h
API change to facilitate executer to know the number of active callbacks
=> CallbackList API

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
Hi,
This should fix the problem seen from time to time on our device. The default IP should be 192.168.4.1 and not 192.168.244.1
This should fix this issue: https://github.com/esp8266/Arduino/issues/5627
=> Fix the bad address of the the AP if the settings are wrong

cores/esp8266/core_esp8266_postmortem.cpp, doc/faq/a02-my-esp-crashes.rst
Users aren't reporting/seeing the actual PC of failures because they
are only copying the >>stack<< into the decoder and not the Exception
line.  Add an ALL CAPS "CUT HERE FOR EXCEPTION DECODER" line to the
output to make it blindingly obvious to include the full crashdump
both in bug reports as well as exception decodes.
=> Add a "-- CUT HERE --" marker to exception output

tests/host/common/Arduino.h, tests/host/common/MockWiFiServerSocket.cpp, tests/host/common/UdpContextSocket.cpp, tests/host/common/mock.h, tests/host/common/user_interface.cpp
This allows to effectively use virtual interfaces (ifconfig eth0:1) with a different IP address.
Very useful for testing (currently with the incoming new mDNS).
=> emulation on host: fix binding from a particular interface

libraries/SPI/SPI.cpp, libraries/SPI/SPI.h
Not to complicate comment chain in #6294 further
SPI library code erroneously assumed that <s>abs() is a C function, so include stdlib.h is required.
what happens instead is Arduino.h shadows `abs()` with it's own macro</s>
`freq - calFreq` or `freq - bestFreq` may produce negative results and require `abs()`
In the referenced PR, when adding `using std::abs;` it confuses GCC by introducing multiple functions named abs(), neither of which have uint32_t argument. As it turns out, `uint32_t() - int32_t()` promotes to `uint32_t`, where old libc abs() silently converted it back to `int`
Fixing casts for `freq` to explicitly make it a signed int when comparing with generated values, both of which are signed.
*edit: noting that abs() isn't a macro and we actually want signedness*
=> libraries/SPI: abs -> std::abs and cast fixes

tests/host/common/UdpContextSocket.cpp
mocking lwIP which always receive multicast packets
=> emulation on host: enable and fix multicast udp server

libraries/ESP8266WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino
The certificate was regenerated yet again, so update the FP in the
SSL validation example.
Fixes #7394
=> Update GitHub cert fingerprint in example

cores/esp8266/heap.cpp, cores/esp8266/umm_malloc/umm_local.c, cores/esp8266/umm_malloc/umm_malloc.cpp, cores/esp8266/umm_malloc/umm_poison.c
Corrected missed edit in check_poison_block() change variable ok from int to bool.
Updated time_stats (used by UMM_CRITICAL_METRICS) initializer to
include UMM_POINSON_CHECK_LITE.
Update maintenance comment block for UMM_REALLOC_...
=> For UMM_CRITICAL_METRICS fixed time_stats initializer. 

variants/modwifi/pins_arduino.h
There was a typo in I2C pin assignment, SCL was set to GPIO #4 instead of GPIO #14, The schematic can be seen here: https://github.com/OLIMEX/ESP8266/blob/master/HARDWARE/MOD-WIFI-ESP8266-DEV/MOD-WiFi-ESP8266-DEV%20revision%20B1/MOD-WiFi-ESP8266-DEV_Rev_B1.pdf
=> I2C pin assignment fix

libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiMulti.h
WifiMulti->run has a built in timeout when connecting set to 5s. In some cases this is not enough time to set up the connection.
I noticed that my ESP-boards quite often failed to connect to my wifi if my repeater mode AP was selected as the strongest SSID. Don't know the reason for the slow connection setup, but my other devices connect without issue.
For Esp32, the 5s timeout was added some time ago based on this project (https://github.com/espressif/arduino-esp32/pull/1220/files). They implemented it a bit different where the timeout could be altered and with a default set to 5s.
I made a PR that changes the API to the same as for Esp32.
=> Ability to set connect timeout in WifiMulti->run

doc/esp8266wifi/generic-class.rst
=> Add some pending methods to generic-class docs

package/README.md, package/esp8266-arduino-doc.bash
This patch fixes spelling typos found in following files
README.md
esp8266-arduino-doc.bash
=> Fix spelling typos in files under packages dir

doc/esp8266wifi/station-examples.rst
Added a bunch of missing "the"s and "a"s mostly. Didn't change any of the coding examples or the meaning of this example. Great example though, thanks.
=> Grammar fixes

libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
reference: https://github.com/esp8266/Arduino/pull/6583#discussion_r452732028
=> webserver: string optimization

doc/esp8266wifi/readme.rst
This patch fixes some spelling typos in doc/esp8266wifi/readme.rst
=> Fix spelling typos in readme.rst

platform.txt
When stacksmash protection was added, the variable used by the compile
lines and the boards.txt.py generator is "build_stacksmash_flags".
Unfortunately, the default variable name  in the platform.txt is
"build_stacksmash" w/o the "_flags."
=> Fix typo in platform.txt causing device test fails

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
WiFiClientSecure.setInsecure() was clearing the secret key (but not the
_chain public client cert) incorrectly.  The other server authentication
modes also had the same effect.
The only way for it to work would be if the app first set the server
authentication method and then the client keys.  There's no good reason
for this.
Adjust the connection to only clear the server id methods and leave the
client ID untouched.
Fixes #7455
=> Keep client certs when server authentication set

cores/esp8266/Updater.cpp
_ledPin should be initialized to -1 in the constructor to avoid setting a random pin when calling Updater::end without having called Updater::begin before. This happens, for example, in the Homie software
=> Initialize _ledPin

cores/esp8266/Esp.cpp
This merge fixes flash writing on PUYA flashes when write size is not a multiple of 4.
This bug prevents updating via Arduino OTA when using gzipped image.
=> Fixed PUYA flash write buffer alignment

cores/esp8266/Crypto.cpp
Parameters that are only used in an assert() statement are unused when
the NoAssert-NDEBUG option is used.  This causes the following unused
parameter warnings while building:
````
/home/earle/Arduino/hardware/esp8266com/esp8266/cores/esp8266/Crypto.cpp: In function 'String {anonymous}::createBearsslHmac(const br_hash_class*, uint8_t, const String&, const void*, size_t, size_t)':
/home/earle/Arduino/hardware/esp8266com/esp8266/cores/esp8266/Crypto.cpp:101:71: warning: unused parameter 'hashTypeNaturalLength' [-Wunused-parameter]
101 | String createBearsslHmac(const br_hash_class *hashType, const uint8_t hashTypeNaturalLength, const String &message, const void *hashKey, const size_t hashKeyLength, const size_t hmacLength)
| …
```
=> Remove warnings when buinding NoAssert

libraries/ESP8266WiFi/examples/WiFiClient/WiFiClient.ino, tests/ci/host_test.sh, tests/host/common/ArduinoMain.cpp
Run valgrind on host mock example runs to catch more bugs in CI.  These
tests would have caught the problem in #7464 before users did.
Add a list of some randomly picked examples to run, and add an option to
run the loop exactly once in the host mock routine, so the test will
actually exit under valgrind.
=> Add valgrind mocked test to CI

cores/esp8266/HardwareSerial.cpp, cores/esp8266/HardwareSerial.h, cores/esp8266/core_esp8266_main.cpp
Match the AVR SerialEvent implicit callback.  Callback is executed
in normal user mode, not IRQ, so standard processing can be uses.
Fixes #752 after 5 years. :)
=> Add SerialEvent() callback to loop processing

tests/ci/host_test.sh
It allows to run CI tests on computers having gcc-multilib installed
=> CI: on host: force 64 bit mode like `make -j2 CI` implicitly does

tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h
* Refactor asm tabs for `.S` cosmetics
* Avoid fixed regname (`a14`) allocation
* Remove unnecessary explicit cast and word masking
=> sys/pgmspace.h: Refactor inline asm

doc/reference.rst
=> Fix and add details to Serial doc

doc/faq/a01-espcomm_sync-failed.rst, doc/faq/a02-my-esp-crashes.rst, doc/faq/a05-board-generator.rst, doc/faq/readme.rst
This patch fixes some spelling typo found in doc/faq.
=> Fix spelling typo under doc/faq

boards.txt, tools/boards.txt.py
upgrade esp8285 variant to full generic device
=> add sdk options to "generic esp8285 module"

cores/esp8266/Esp.h
The method is declared in Esp.h and implemented in Esp.cpp.
That was broken by #7356.
Currently, F_CPU is always defined.
=> getCpuFreqMHz(): fix when F_CPU is not defined

.github/workflows/pull-request.yml, bootloaders/eboot/eboot.c, tests/ci/eboot_test.sh
Check that building the eboot.c block generates the same binary as
the verison checked into the repo.  Catches the case where a library
or eboot.c file is changed, but an updated eboot.elf isn't included
in a PR.
Can't do simple binary diff of the ELFs because paths and compile
times will change, so dump the two sections we care about.
=> Add CI test for eboot build

libraries/ArduinoOTA/ArduinoOTA.cpp, libraries/ArduinoOTA/ArduinoOTA.h, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
This removes a bit of code repetition.
=> Use direct member initialization instead of ctr initialisation

cores/esp8266/Stream.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
Converting floats to doubles is very expensive on esp8266, so prefer
calculations or comparisons as float. This saves 10% (20 bytes) of the
String::parseFloat() code size and probably quite a bit of runtime
overhead.
=> Avoid float-double-conversion

tests/README.md, tests/host/README.txt, tests/platformio.sh
This patch fixes some spelling typos found in tests directory.
=> Fix typos in tests

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
The logic can be simplified by using integer logic without a functional
change. Reduces code size by 40% (78 bytes -> 46 bytes) and silences
a Warith-conversion warning.
=> Reduce codesize of setOutputPower

cores/esp8266/WString.cpp
Althought GCC seems to be able to grok it, it looks weird
in my editor. this is the only place in the code base where
this combination is used, so I hope its okay to remove it.
=> Fixup weird combination of oneline/multi line comments

libraries/ESP8266HTTPClient/examples/DigestAuthorization/DigestAuthorization.ino
Simple example update to pass the method as a parameter to getDigestAuth(), so it is more easily used for POST.
=> Update DigestAuthorization.ino (Simple example update)

cores/esp8266/IPAddress.cpp
Before, `aResult` was set to `INADDR_NONE`, so `255.255.255.255` (broadcast). When timeout was too low and callback didn't fire, the `aResult.isSet()` line returned always true and that's not the correct behaviour.
Even thought I'm not a native speaker, `INADDR_ANY` and `INADDR_NONE` are confusing me.
Whenever I think about it, I always associate `INADDR_NONE` with 0.0.0.0 and `INADDR_ANY` with `255.255.255.255`, but it's the other way.
Also lwIP has the same scheme.
I would like to ask if we can add a `clear` method to `IPAddress` like did to `String` class (maybe in another PR) to resolve any doubts.
=> Fix Error in hostByName with low timeout

cores/esp8266/IPAddress.cpp, cores/esp8266/IPAddress.h
Added `clear` method to `IPAddress` class that will set the ip to `INADDR_ANY` (aka `0.0.0.0`).
That's because INADDR_ANY and INADDR_NONE confuse me, and every time I don't remember which is which.
This method will help me (and others?) a lot.
=> Add clear method to IPAddress

.github/workflows/pull-request.yml
=> ci: apt update

doc/gdb.rst
Used this nice tutorial several times, but each time had to use find to find gdb since it's not in hardware but in tools and also in a version-numbered folder
=> Update path of gdb

libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
In the StaticRequestHandler method, exception 28 (LoadProhibitedCause) occurs when debugging with the DEBUG_ESP_CORE option and if the default parameter null is used for cache_header.
In this commit, the pointer is checked for null before output.
=> FIX StaticRequestHandler crashes when cache_header is null

libraries/ESP8266WebServer/src/detail/mimetable.cpp
In addition to #7312 the MIME type for txt files is to be corrected.
Currently the MimeType for txt files is the file extension ".txt". 
In the commit the variable with text/plain is used again.
=> FIX MIME-Type for txt-suffix

cores/esp8266/WString.cpp, cores/esp8266/WString.h
ref.
- https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-move-noexcept
- https://rules.sonarsource.com/cpp/RSPEC-5018?search=noexecept
- https://clang.llvm.org/extra/clang-tidy/checks/performance-noexcept-move-constructor.html
> Move constructors of all the types used with STL containers, for
example, need to be declared noexcept. Otherwise STL will choose copy
constructors instead. The same is valid for move assignment operations.
With a basic example based on the `master`
```diff
diff --git a/cores/esp8266/WString.cpp b/cores/esp8266/WString.cpp
index 46aad5d5..1c93d8f2 100644
--- a/cores/esp8266/WString.cpp
+++ b/cores/esp8266/WString.cpp
@@ -225,6 +225,7 @@ String & String::copy(const __FlashStringHelper *pstr, unsigned int length) {
#ifdef __GXX_EXPERIMENTAL_CXX0X__ …
```
=> WString: mark move ctor as noexcept

cores/esp8266/WString.cpp, cores/esp8266/WString.h, tests/host/core/test_string.cpp
target = std::move(source) does not reset source's buffer pointer back to the sso
#7553 fixes this behaviour
Added as a separate test, perhaps it could go into the existing SSO
*edit:* failing, as intended:
https://github.com/esp8266/Arduino/pull/7611/checks?check_run_id=1166504473#step:4:2364
```
-------------------------------------------------------------------------------
core/test_string.cpp:22
...............................................................................
core/test_string.cpp:30: FAILED:
REQUIRE( origin.c_str() != nullptr )
with expansion:
{null string} != nullptr
```
=> WString: c_str() returns null pointer after move

cores/esp8266/Print.cpp, cores/esp8266/Print.h
@d-a-v We've talked about it yesterday. Even if PR'ing AVR Arduino is a good idea to do first|also, could you give this an eye, please?
Compiled size is not affected if not used with (u)int64_t, if print(int64_t) gets used, 288 bytes IROM are used additionally.
=> Extend Print class for 64bit integers.

README.md
Pull axtls link, add Espressif's NONOS SDK repo link
=> Pull deprecated axtls link

libraries/ESP8266WiFi/examples/WiFiMulti/WiFiMulti.ino, libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiMulti.h
Fixed critical issues WiFiMulti library:
- WiFi scan timeout implemented to prevent endless connect loop
- Fallback implemented on WiFi connect failure to prevent endless loop
- Fast WiFi connection at startup
- Improved debug prints
- Doxygen added
- Code maturing
- Example update
The API is identical.
=> Redesign ESP8266WiFiMulti.[cpp|h]

doc/esp8266wifi/bearssl-client-secure-class.rst, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h, libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.cpp, libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.h, tests/device/test_sw_http_client/test_sw_http_client.ino
Remove the axTLS compatability functions from WiFiClient/ServerSecure,
device tests for axTLS, and any document refs to axTLS.
=> Remove stray axtls refs, deprecated compat funcs

tools/signing.py
Updater_Signing.h is rewritten at each compilation forcing the recompilation of some ESP libs.
This fix compares the content if the file already exists and updates it only if changed.
Very similar to "core_version.h" fix in #6414
=> Prevent rewriting Updater_Signing.h if content unchanged

cores/esp8266/time.cpp
Since #7109, `sntp_stop` and `sntp_init` are not called anymore when using
`configTime(int timezone_sec, int daylightOffset_sec, const char* server1, const char* server2, const char* server3)`
This results in NTP sync not working. (`settimeofday_cb` callback is never called).
=> Add missing sntp_init/sntp_stop

doc/ota_updates/readme.rst
The headers sent when an OTA update is requested of an HTTP server have changed in the code. This change is to update the documentation accordingly. PHP sample code was changed but not tested.
=> Update OTA HTTP Server Header Information

libraries/ESP8266WiFi/src/CertStoreBearSSL.cpp, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
When the debug level for the device includes SSL but the debug port is
chosen as "None," don't attempt to write debug messages.
Fixes #7638
=> Fix error when debug enabled but no port chosen

doc/esp8266wifi/readme.rst, doc/esp8266wifi/station-class.rst, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp, libraries/ESP8266WiFi/src/include/wl_definitions.h, libraries/esp8266/examples/interactive/interactive.ino
=> BREAKING: Add Wrong Password wifi status case

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h
#Fixes #7641.
Change the return type of RSSI() to match the underlying SDK API.
This is a breaking change because the method signature changes.
=> BREAKING: Change return type of RSSI()

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h
Fixes #7643.
Change return type of channel to match the return type of the underlying SDK API
This is a breaking change because the method signature changes.
=> BREAKING: Change return type of channel()

libraries/Netdump/library.properties
When building with the Netdump library, the IDE generates the following warning:
> WARNING: library Netdump claims to run on (esp8266 lwip) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).
Fix the library.properties to call the architecture just "esp8266"
=> Fix Netdump library architecture

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
Use a base64 encode that doesn't add CRs to the output when comparing
username:password values for authentication.
Fixes #7664
@arendst, can you please give this patch a try?  I've tested a 100 character password with the HTTPBasicAuth example and it works for me.
=> Fix long password validation in WebServer

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
=> Catch and display SSL errors for fatal alerts

libraries/ESP8266WiFi/src/CertStoreBearSSL.cpp
As was discussed at https://github.com/esp8266/Arduino/issues/7684
Added fs:: before FS stuff used in file.
=> compile failure fix with FS_NO_GLOBALS flag

libraries/SDFS/src/SDFS.cpp, libraries/SDFS/src/SDFS.h, tests/host/fs/test_fs.cpp
The SDFS implementation didn't include plumbing to support user-supplied
timestamp generators (for file create/write times) because the SDFat
library doesn't support a callback parameter.
Work around it by using a single, global (inside sdfs namespace) that
the static timestamp callback member can see and use.
Add a test of the feature in CI.
Fixes #7682
=> Hook up custom timestamp proc for SD/SDFS

doc/esp8266wifi/server-examples.rst
=> update documentation example

cores/esp8266/WString.cpp, cores/esp8266/WString.h, tests/host/core/test_string.cpp
=> Provide String::indexOf for a char* needle

cores/esp8266/WString.cpp, cores/esp8266/WString.h
* move bodies of dtor, `init()` and `charAt()` to .h (implicitly inlined)
* unify the description of initialization into one: `init()` (literally), and called from each ctors, `invalidate()` and `move()`.
* invert the SSO state logic in order to make init state zeroed (as a result, inlined `init()` insns: 4 to 3)
IROM size @ FSBrowser: 304836 -> 304596 (saved 240 from master)
=> WString: Optimize a bit

cores/esp8266/Schedule.cpp
It was noticed while checking code in [this comment](https://github.com/esp8266/Arduino/issues/7646#issuecomment-729932874) that `schedule_recurrent_function_us()` should be in IRAM.
=> Scheduled functions: schedule_recurrent_function_us() should be in iram

cores/esp8266/core_esp8266_waveform_phase.cpp, cores/esp8266/core_esp8266_waveform_phase.h, cores/esp8266/core_esp8266_waveform_pwm.h
And also fix inline documentaton for both waveform "flavors".
=> Waveform, fix callback return to CPU cycles instead of µs (wrt PR 7022)

libraries/ESP8266WebServer/src/ESP8266WebServer.h, libraries/ESP8266WebServer/src/Parsing-impl.h
Use a simpler, cleaner implementation of multipart form detection as
defined in https://tools.ietf.org/html/rfc7578 .
Implements a simple state machine that detects the `\r\n--<boundary>`
stream in input a character at a time, instead of buffering and
comparing in chunks which can miss things due to alignment issues and
which also had a problem with replacing characters in a binary stream.
Fixes #7723
=> Rewrite multipart boundary detection

README.md
As a newcomer to Arduino IDE, it is not obvious where the "Additional Boards Manager URLs" field is
=> Specify where Additional Boards Manager URLs is

doc/ota_updates/readme.rst
The documentation was a bit unclear what was happening, so after reading the source code I thought to update the documentation a bit.
The most stuff is clarification, but I had to remove the `INCLUDING-THIS-32-BITS` part, as the size is just the size of the signature (hard coded to `[0x0, 0x1, 0x0, 0x0]` (256 little endian)).
=> Clarified implementation of the signed OTA implementation

cores/esp8266/debug.cpp, tests/host/Makefile
- include debug.cpp (`hexdump()`)
- fix Makefile messages
- fix cleaning (lcov was not removed)
=> emulation on host: various minor fixes

platform.txt
Fixes https://github.com/esp8266/Arduino/issues/7749#issue-760585820
Corrected recipe.hooks.prebuild.1x.pattern.windows in platform.txt and placed in proper order.
=> Fix platform.txt issue #7749 for Windows

platform.txt
Some tools have issues with pattern.XX numbers above 9 in platform.txt.
Adjust all pattern.XX numbering to start at 1 and remove the numbering
when there is only one step.
=> Normalize platform.txt pattern numbers

libraries/ESP8266WiFi/src/WiFiServer.cpp
* fix warning as below:
```
...\libraries\ESP8266WiFi\src\WiFiServer.cpp: In member function 'WiFiClient WiFiServer::available(byte*)':
...\libraries\ESP8266WiFi\src\WiFiServer.cpp:120:55: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
120 |             tcp_backlog_accepted(_unclaimed->getPCB());
|                                                       ^
```
=> WiFiServer.cpp: Fix warning

cores/esp8266/core_esp8266_main.cpp
Removed obsolete debug block from `core_esp8266_main.cpp`.
=> Removed obsolete debug code

cores/esp8266/core_esp8266_i2s.cpp, cores/esp8266/i2s.h
~~A `dac`~~ rx/rxDrive/tx/txDrive parameters are added to allow using only i2s in/out data pin without clock pins.
This is necessary for example in no-DAC mode when i2so-bck and i2so-ws are repurposed,
Found when using SDFS because SPI SS GPIO was overlapped.
*edit*: Related: https://github.com/earlephilhower/ESP8266Audio/pull/344
=> i2s: adds i2s_rxtxdrive_begin(enableRx, enableTx, driveRxClocks, driveTxClocks)

libraries/SD/src/SD.h
The included SD library is missing the 'rename' method. Fortunately, the underlying SDFS library has full support for this method, so we just had to create the proper wrapper in SD.h, preserving the style of the other wrapper methods. This is a minor and convenient addition.
=> Add the missing 'rename' method wrapper in SD library.

platform.txt, tools/cp.py, tools/mkdir.py
* add double-quotes to `compiler.S.flags`
* fix windows-specific processes (`recipe.hooks.linking.prelink.[12].pattern.windows`)
* rewrite processing of "mkdir" and "cp" in python because of platform-independence
* make consistent with the use of quotation marks in other `*.py` files
=> Fix: cannot build after #7060 on Win64

cores/esp8266/Esp.cpp, cores/esp8266/Esp.h
=> Added missing check for failure on umm_push_heap calls in Esp.cpp

.github/workflows/pull-request.yml, tests/common.sh
Thanks to @mcspr.  Make sure the cached toolchain is only valid when the
package.json file is identical.  Also, add the Arduino IDE to the cache
to avoid re-downloads.
=> Use smarter cache key, cache Arduino IDE

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h
Error in copyright text about Arduino Wifi library.
I have seen this error in several repositories inhereted from this one.
=> Typo error in ESP8266WiFiGeneric.h

cores/esp8266/uart.cpp
EspSoftwareSerial successfully uses optimistic_yield for the same purpose already.
Fixes #7746
=> UART write loop could lead to wdt with low bitrates or large buffers

libraries/ESP8266WebServer/src/Parsing-impl.h
When a file upload ends in \r\n (i.e. a Windows formatted text file) the
sequence of bytes on the wire is `\r\n\r\n----...boundary-marker...`.
When the FSM in Webserver was evaluating the stream, that 2nd `\r` would
be written as valid data and the FSM parser would be reset and see `\n`
as the 1st character, which wouldn't match.  This would a) add an extra
`\r` to uploaded files, and b) cause uploads to hang.
Fix by checking on a header FSM mismatch if the next character input
could possibly match our marker, and if so handle it properly.
Fixes #7803
=> Fix header FSM in webserver, fix Windows uploads

libraries/esp8266/examples/irammem/irammem.ino
Make verify fail more visible.
Updated example irammem.info to show performance and test int16 handling when IRAM is used.
Removed 4K performance test. It didn't show any new information over the 1K test.
=> Add verify IRAM sum results using DRAM as reference.

cores/esp8266/core_esp8266_wiring_analog.cpp
Fixes #6410
We actually provide a function prototype for `analogReference()` in
`Arduino.h`, but no implementation.  Add a dummy one that only supports
DEFAULT (like other Arduino boards).
=> Add stub for analogReference

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
If a server returns "HTTP/1.x -8 OK", for example, it can misguide an application developer into freeing less-important memory so the request can be retried and succeed, when the problem is in the server.
_returnCode is never used anywhere else, but it could still contain a negative value returned by a broken server and therefore could cause troubles in the future (if _returnCode is in fact used)
=> Protect against server hijacking error handling

cores/esp8266/FS.cpp
Fixes #7814.
Return 0, not MAXINT, when a read is called on a File without a backing
instance of a SPIFFS/LittleFS/SD File.
=> Invalid read return value fix

libraries/ESP8266WiFi/src/WiFiClient.cpp, libraries/Netdump/src/Netdump.cpp, libraries/Netdump/src/Netdump.h
Fixes #7821.
This does not report the OOM to the user. But it already prevents UB from [Netdump::tcpDumpProcess](https://github.com/esp8266/Arduino/blob/7f38e141c7502032af594fdd502c1b1f6049377c/libraries/Netdump/src/Netdump.cpp#L169).
=> Avoid UB and abort on nullptr buffer

cores/esp8266/core_esp8266_non32xfer.cpp, cores/esp8266/exc-c-wrapper-handler.S, cores/esp8266/exc-sethandler.cpp
Adaptation of `_xtos_set_exception_handler` for Arduino ESP8266 core
This replacement for the Boot ROM `_xtos_set_exception_handler` is used to install our replacement `_xtos_c_wrapper_handler`. This change protects the value of `excvaddr` from corruption.
The issue, the Boot ROM "C" wrapper for exception handlers, `_xtos_c_wrapper_handler`, turns interrupts back on just before calling the registered "C" function. This leaves `excvaddr` exposed to possible overwrite before it is read. For example, if an interrupt is taken during the exception handler processing and the ISR handler generates a new exception, the original value of `excvaddr` is lost.  To address this issue we have been using a replacement `_xtos_c_wrapper_handler` in file `exc-c-wrapper-handler.S` for the non-32-bit access …
=> Replacement for the Boot ROM _xtos_set_exception_handler

libraries/ESP8266AVRISP/src/ESP8266AVRISP.cpp, libraries/ESP8266AVRISP/src/ESP8266AVRISP.h, libraries/ESP8266WiFi/src/BearSSLHelpers.cpp
Based on my last PR I grepped for malloc and found these places where the null check was missing.
=> Prevent nullptr dereference on OOM

cores/esp8266/spiffs_api.h
Remove a straggler `undef min/max` from core header
Supersedes #3856
=> Supersede #3856, remove undef min/max

tools/platformio-build.py
At the moment, exceptions are disabled by default in the PlatformIO build script. This PR adds a new configuration macro `PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS` to allow users dynamically enable exceptions.
https://github.com/platformio/platform-espressif8266/issues/237
cc @ivankravets
=> Add dynamic exceptions configuration for PlatformIO

cores/esp8266/debug.cpp, cores/esp8266/debug.h, tests/host/common/mock.h, tests/restyle.sh
- `hexdump()` must be declared as `"C"` like its C counterpart.
- add ascii data in dump
- avoid caps
=> Hexdump fix&update

cores/esp8266/core_esp8266_i2s.cpp
Adjust the number of bittimes when returning the real I2S rate.
=> Fix I2S reported rate for 24b mode

boards.txt, tools/boards.txt.py
A couple board types reported ESP8266_GENERIC instead of their proper
types in boards.txt (and in defined generated therefrom/etc.).
Give them proper board types based on their names, like other modules.
=> Fix improper GENERIC board IDs

package/package_esp8266com_index.template.json
Fatfingered the 32-bit Windows pointer to the Python interpreter.  Our
CI and my own testing missed due to being on 64-bit Windows.
For 2.7.4 release, I'll add a file of the appropriate name to the
release for now, but this will correct things for 3.0.0 and forward.
=> Fix typo in 32-bit Windows package JSON

cores/esp8266/LwipDhcpServer.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
Although legacy logic is greatly improvable, at least AP now seems to run like before, offering 192.168.4.100+ addresses, whether debug mode enabled or not.
Fixes #7880 
Fixes #7795 
The difference between debug mode enabled (not `DHCPS_DEBUG` but general debug options) had an effect on one of the uninitialized variables.
=> AP & dhcp-server: fix uninitialized variables

cores/esp8266/FS.cpp, cores/esp8266/FS.h, cores/esp8266/FSImpl.h, libraries/LittleFS/src/LittleFS.h
This PR enables attributes on the root, such as [creation/modification time of volume](https://github.com/earlephilhower/mklittlefs/pull/15).
```cpp
fs::Dir fs = LittleFS.openDir("/");
Serial.print("FS creation timestamp: ");
Serial.println(fs.fileCreationTime());
```
After quite some testing I believe the attached changed is the only one required. It didn't seem to break anything in my tests, though I'm not 100% sure, because the use and value of `_valid` in undocumented and unclear to me.
Test project available: [LittleFSTest](https://github.com/qistoph/LittleFSTest)
Effects of checking 'c' and 't' attributes on a root node, if:
1. **attribute present**: return its value (mklittlefs since [PR15](https://github.com/earlephilhower/mklittlefs/pull/15))
2. **attribute unavailable at root …
=> Allow attribute get on root

cores/esp8266/heap.cpp
Some random code falsely call `malloc(0)`.
This change avoids useless warnings.
=> OOM: avoid warn when calling *alloc(0)

doc/esp8266wifi/readme.rst
Topic under this link does not exist.
Link should point to ESP8266 SDK repository on GitHub.
=> Fix link to ESP8266 NonOS SDK

cores/esp8266/WString.cpp
When OOM debug is enabled: User helper to warn about misused Strings
With this sketch:
```cpp
void setup ()
{
String s;
Serial.printf("empty\n");
for (int i = 0; i < 170; i++)
{
char c = 'a' + (i % 26);
s += c;
Serial.printf("+%c (%2u) %s\n", c, s.length(), s.c_str());
}
}
void loop ()
{
delay(1000);
}
```
```
[... no warning from 1 to 140]
22:26:24.074731667 +j (140) abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij
22:26:24.076687969 +k (141) abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk
22:26:24.095628380 +l (142) abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnop …
```
=> OOM debug: warn about String reallocation

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
Copy using the provided length and directly use the string as a buffer.
Resolve #7929
=> Fix WiFi events with 32byte wide SSIDs

cores/esp8266/HardwareSerial.h, cores/esp8266/uart.cpp, cores/esp8266/uart.h, tests/host/common/MockUART.cpp
Change return type from void to bool on affected functions, return false on failure.
=> HW Serial swap and pin setting work only on a few pins

libraries/ESP8266WiFi/src/WiFiClient.cpp, libraries/ESP8266WiFi/src/include/ClientContext.h
`WiFiClient`'s `ClientContext` was originally designed to take data from a Stream through a specific `DataSource` class which is now removed by the `Stream::send` changes.
Ability to stream from flash or dram to `WiFiClient` was missing from these changes, this is now restored. 
Fixes #7928 ([comment](https://github.com/esp8266/Arduino/issues/7928#issuecomment-804574643))
=> fix WiFiClient::write(from flash or iram)

cores/esp8266/core_esp8266_features.h, doc/esp8266wifi/generic-class.rst, libraries/ESP8266WiFi/src/ESP8266WiFi.h
=> Fixes #7988: reverse dependency core on libraries: `enableWiFiAtBootTime()`

cores/esp8266/core_esp8266_features.h, cores/esp8266/core_esp8266_waveform.h, libraries/esp8266/examples/FadePolledTimeout/FadePolledTimeout.ino
Move the prototype for `enablePhaseLockedWaveform()` linker magic into header that's included by default instead of particular internal core header.
Fixes #7976 .
=> Make `enablePhaseLockedWaveform()` visible from `Arduino.h`

cores/esp8266/core_esp8266_app_entry_noextra4k.cpp
Correct missed ICACHE_RAM_ATTR in `cores/esp8266/core_esp8266_app_entry_noextra4k.cpp`.
=> Updated HWDT one missed ICACHE_RAM_ATTR

cores/esp8266/Esp.cpp, cores/esp8266/Esp.h
ESP has no data members, is used as singleton object, and can be called before C++ runtime setup during boot.
As a additional benefit, this change reduces binary code size.
=> ESP is singleton w/o data members, make all functions static 

.github/workflows/release-to-publish.yml
- following this error message
Error: Unable to process command '::set-env name=TRAVIS_TAG::3.0.0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
- this guide:
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
=> update release github action

.github/workflows/tag-to-draft-release.yml
ditto on the draft action file
=> update draft release github action

README.md, package.json, platform.txt
closes #8035 
*edit*: 
For some reason the sha256 from the release page https://github.com/esp8266/Arduino/releases/download/3.0.0/package_esp8266com_index.json (b3d4a5477acb17e8d84d6e492701c950d0d9cc3bb828e02bd3117c45833c1210 which is right)
differs from the one used by Arduino IDE one from esp8266.github.io
https://arduino.esp8266.com/stable/package_esp8266com_index.json
(9f6929a182c97a96c093137720ce85a0749b06bfd1a8850b401cc5ab0c50e758)
This need to be sorted out by @igrr or @earlephilhower
=> back to dev (3.0.1)

cores/esp8266/core_esp8266_waveform_phase.cpp
Even if a very small function, loading any code from flash while in ISR can and will eventually crash the MCU.
Added IRAM_ATTR to _stopPWM() so that digitalWrite() would work inside ISR.
Fixes #8043
=> digitalWrite() in `enablePhaseLockedWaveform` mode: need IRAM_ATTR on all `stopPWM()` impls

package/build_boards_manager_package.sh
WIP about https://github.com/esp8266/Arduino/issues/8049
Ref: [empty variable](https://github.com/esp8266/Arduino/runs/2592755965?check_suite_focus=true#step:5:35)
=> release script: protect bash variables and add logs

libraries/SD/library.properties
When multiple libraries contain files matching an `#include` directive in the program, the Arduino build system must pick one to use for compilation. Multiple factors are used in order to make an intelligent determination of which library is best, as documented [here](https://arduino.github.io/arduino-cli/dev/sketch-build-process/#dependency-resolution).
In order to enhance this determination, the closeness of match between [the library.properties `name` value](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) and the filename in the `#include` directive is being added as one of those factors. This new factor is referred to as [**"Library Name Priority"**](https://arduino.github.io/arduino-cli/dev/sketch-build-process/#library-name-priority) …
=> Use optimal bundled library name

tools/platformio-build.py
This PR updates the PlatformIO build script according to the latest changes in the core `v3.0`: 
- Replaces the default MMU configuration process by adding new flag options similar to the menu in the Arduino IDE (see [PlatformIO docs for ESP8266](https://docs.platformio.org/en/latest/platforms/espressif8266.html#mmu-adjusting-icache-to-iram-ratio)). Additionally, all MMU flags are now used when generating LD script.
- Adds missing `-free` and `-fipa-pta` flags.
=> Synchronize PlatformIO build script

cores/esp8266/core_esp8266_i2s.h
Complements fix PR #8108  for #8107
=> Normalize I2S core header's include guard.

tools/platformio-build.py
Synchronizes the `platformio-build.py` build script with what is actually there in the core folder. The folder `tools/sdk/libc` was removed since [core version 3.0.0](https://github.com/esp8266/Arduino/tree/3.0.0/tools/sdk), (but existed in [2.7.4](https://github.com/esp8266/Arduino/tree/2.7.4/tools/sdk)), however the script was not updated.
This makes users unsure as there is warning about this not-found directory in VSCode then ([source](https://community.platformio.org/t/problems-with-platformio-and-seemingly-missing-file-esp01-1m/22003)). 
Fixed by simply removing the non-existant folders from the build script.
=> Remove include and lib folders removed since 3.0.0 core

cores/esp8266/core_version.h, package/README.md, package/build_boards_manager_package.sh, tools/makecorever.py
- Release process update is based on #8034.
- `makecorever.py` is now used as part of the release process script.
- `MAJOR`/`MINOR`/`REVISION` are added in `core_version.h` based on `platform.txt`'s `version` when building with Arduino-CLI, or git tag when releasing. PlatformIO will have to be updated too (this is not addressed here).
This is WIP but is going to be merged anyway in order to try the release script executed remotely by CI.
A tag will be added (3.0.1) and removed right after that (this gymnastic happens quite often while releasing these days).
This will allow to check generated logs and archive to address #8049
=> Release process fix & major/minor/rev macro addition

package/README.md, package/build_boards_manager_package.sh, platform.txt, tools/makecorever.py
Following #8126 
- Release script: fix variable name error
- Release process in README is described twice. Syncing the two walk-throughs.
=> Release process fix #2

tools/makecorever.py
=> makecorever.py: restore ARDUINO_ESP8266_GIT_VER even without .git/

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
Sometimes a url is specified in all upper case and HTTPClient rejects it when it would be perfectly fine.  This just makes the protocol detection case insensitive so the url is accepted if the protocol is uppercase.
=> Change protocol detection so uppercase or lowercase works

libraries/ESP8266WiFi/src/WiFiClient.cpp, libraries/ESP8266WiFi/src/WiFiClient.h, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h
Fixes #8079
Because WiFiClientSecure inherits WiFiClient, and WiFiClientSecureCtx also
inherits WiFiClient, they both end up in the list of TCP connections that
are used for WiFiClient::stopAllExcept().  This would cause the underlying
SSL connection to be closed whenever you attempted to
stopAllExcept(WiFiClientSecure)
Fix by adding a "_owner" pointer in the WiFiClient object which points to
nullptr (default case) or to the associated upper-layer connection.
When stopping all connections except one, only look at the uppermost
connections.
=> WiFiClientSecure owns context, fix stopAllExcept

boards.txt, tools/boards.txt.py
Hello!
We recently merged Arduino/arduino-cli#1326 on the Arduino CLI, it introduces an enforcement of the platform specifications for [custom board options][custom-board-options]. Boards that define some custom options without their name defined somewhere else in the `boards.txt` won't be loaded, the rest will be loaded without issues if they respect the specifications.
A user reported in Arduino/arduino-cli#1329 that `esp8266:esp8266:espduino` is not loaded because of this change, this PR will fix that issue.
That change has not been released but is only available in the nightly, so most users are not affected as of now but will in the next release. 
[custom-board-options]: https://arduino.github.io/arduino-cli/latest/platform-specification/#custom-board-options
=> Add missing menu.UploadTool name definition

doc/requirements.txt
This should restore a decent documentation presentation
=> fix readthedoc python dependencies

platform.txt, tools/platformio-build.py
GCC 10.x seems to have a knack for crashing when a function which is declared
to return a value does not.  Add a warning, present on all builds, when this
is the case.  For more info see
https://github.com/esp8266/Arduino/discussions/8160
Thanks to @hreintke for the tip
=> Add errors on invalid/missing function return type

.github/workflows/pull-request.yml, .github/workflows/release-to-publish.yml, .github/workflows/tag-to-draft-release.yml
Per discussion with @mcspr.
When not specifiying `bash` as running shell, default options do not include `-o pipefail` [as it should](https://github.com/actions/runner/issues/353).
It may not prevent a script to stop when one component of a pipe chain fails (ex: `false | true` won't fail but it should).
As a consequence in this PR, `bash` is [explicitely specified as default shell](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-2).
Also enforcing issue detection by breaking down commands
`echo "$(command)" >> file`  =>  `var=$(command)` then `echo ${var} >> file`
=> github action: enforce issue detection with bash 

doc/Troubleshooting/debugging.rst
The link to the debug levels was broken in that the file changed and it no longer points to the correct lines. Update the line numbers and also include the commit hash in the URL to prevent it from breaking in the future.
=> Update debug level list link

libraries/LittleFS/src/LittleFS.h
The LittleFS constructor could cause a divide-by-zero error and crash the
chip during pre-main startup (i.e. when the constructors were called).
Avoid by only initializing the LittleFS control structure when there is
a filesystem specified in the flash layout.
As identified by @drzony on https://gitter.im/esp8266/Arduino
=> Don't crash when includeing LittleFS.h w/no FS

tools/platformio-build.py
Fixup https://github.com/esp8266/Arduino/pull/8165, as it only changed behaviour for .c files
Also adds some comments referencing SCons documentation (literally)
=> platformio: use CCFLAGS for -Werror

.github/workflows/tag-to-draft-release.yml
Fix release packager issue.  Seems when variable set in $GITHUB_ENV
quotation marks are not removed, resulting in URLs with
http://ddd.dd/blah/"3.0.1"/release and JSON entries with the same
quotation problem.
=> Release 3.0.1

.github/workflows/release-to-publish.yml, package/deploy_package_index.sh
Fixes #8180
The draft release generates a ZIP and JSON.  Instead of rebuilding the ZIP
on the publish step (which may result in a different SHA256 due to file time
differences in the new ZIP), just copy the one from the published release
directly.
Also clean up and remove unneeded environment variables and CI steps.
=> Copy released JSON to board URL, not new one

cores/esp8266/WString.cpp, tests/host/core/test_string.cpp
We use a few non-null terminated views and it seems String::concat(char*, size_t) breaks those because it always copies the null terminator, but since the function immediately overwrites it, it doesn't need to.
This change makes String::concat support non-null terminated char* without any side effect.
Fixes #8200
=> Avoid copying null in concat, unused + breaks views

libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h
Fixes failing https connections to HelloServerBearSSL when using the MMU option with 48K IRAM shared. This happened after build changes to the example that increased IRAM code size that caused free IRAM for Heap to fall below ~16K, then "new" would OOM out in WiFiClientSecureBearSSL. This was observed when used with https://github.com/esp8266/Arduino/pull/8196#issue-684769650
Added private function to try IRAM first then switch to DRAM on fail, to WiFiClientSecureBearSSL for iobuff allocations.
=> Fixes failing https connections to HelloServerBearSSL

tools/platformio-build.py
Fixes #8262.
Arduino IDE link order:
>-lhal -lphy -lpp -lnet80211 -llwip2-536-feat -lwpa -lcrypto -lmain -lwps -lbearssl -lespnow -lsmartconfig -lairkiss -lwpa2 -lstdc++ -lm -lc -lgcc
PlatformIO link order before this fix:
>-lhal -lphy -lpp -lnet80211 -lwpa -lcrypto -lmain -lwps -lbearssl -lespnow -lsmartconfig -lairkiss -lwpa2 -lm -lc -lgcc -llwip2-536-feat -lstdc++
(^ which causes the linking failure in regards to the math library in the referenced issue)
PlatformIO link order after this fix:
>-lhal -lphy -lpp -lnet80211 -llwip2-536-feat -lwpa -lcrypto -lmain -lwps -lbearssl -lespnow -lsmartconfig -lairkiss -lwpa2 -lstdc++ -lm -lc -lgcc 
Aka, now equivalent to the Arduino IDE linking order.
The code refactors setting `env["LIBS"]` further down the script where it knows the system …
=> Respect linking order of libraries

libraries/esp8266/examples/ConfigFile/ConfigFile.ino
Hi,
Thank you guys for maintaining this critical piece of software that is at the heart of so many projects 👍 
This PR simplifies the `ConfigFile.ino` example by removing the temporary buffer and passing the `File` directly to [`deserializeJson()`](https://arduinojson.org/v6/api/json/deserializejson/).
When reading from a `Stream`, using a temporary buffer is counterproductive because it complexifies the code and increases memory usage. It's also a source of confusion because it can create dangling pointers in the [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/).
The only benefit of using a buffer is the reading speed, but I don't think speed is the focus in this example; if it were, it would use a buffer in `saveConfig()` too.
By the way, this example has been the origin of …
=> Remove temporary buffer in ConfigFile.ino

cores/esp8266/coredecls.h
The define was in the feature development branch, now after merge into main it is redundant, and should not be part of the next release point.
=> Remove the HAVE_ESP_SUSPEND define.

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
Select the specific union member and struct fields, don't just alias the whole event\_info
fix #8341
=> Correctly access WIFI_EVENT_MODE_CHANGE event info

cores/esp8266/core_esp8266_si2c.cpp
Some devices require the data wire SDA to be held down at the moment while the clock wire is pulled down too to execute the start condition (e.g. devices using "TinyWires.h" library). This change follows a behaviour of Arduino Wire.h library, where the SCL signal is pulled down in half of period of start condition.
=> A clock phase correction in write_start(void) (I2C)

cores/esp8266/FS.h, libraries/LittleFS/examples/SpeedTest/SpeedTest.ino, libraries/LittleFS/src/LittleFS.h
fixes #8384 
`::availableForWrite()` could unconditionnally return a full sector as free space like proposed in #8384.
This proposal aims at returning a non-0 size fitting the current file block.
If the block is full and the filesystem is not full, it returns a full-FS-block size.
This way, the API allows users to take proper actions without losing data from the input stream when the filesystem is full, even if there is generally little to do in such case.
=> LittleFS: add overrides for Stream::send

libraries/Wire/Wire.h
New PR that expands on https://github.com/esp8266/Arduino/pull/8388.
Changed it so it's the same setting name (`I2C_BUFFER_LENGTH`) on both ESP8266 and ESP32 Wire library.
=> Adding custom buffer_length using I2C_BUFFER_LENGTH

platform.txt
This line is required to be compatible with the Arduino library specification
=> compiler.libraries.ldflags= was missing, generating an error when trying to link precompiled libraries

libraries/ArduinoOTA/ArduinoOTA.cpp, libraries/ArduinoOTA/ArduinoOTA.h
This adds the end() function for the ArduinoOTA class.
ESP32 has this implemented, however ESP8266 was lacking this.
=> adding esp32's ArduinoOTAClass::end function to esp8266

libraries/ESP8266mDNS/src/LEAmDNS.h, libraries/ESP8266mDNS/src/LEAmDNS_Structs.cpp
=> mDNS timeout: use real type

libraries/Wire/Wire.cpp, libraries/Wire/Wire.h
Based on
https://github.com/paclema/arduino-esp32/commit/375a89ed58f341a8aae26dab505713f3ef0edb3d
We should have been very careful when #defining things to not use a name
that could conflict with the user's own code, so this marks that old
define as deprecated.
If you opt-into the new behavior, you do not get the old BUFFER_LENGTH
constant.
I looked over the users of these variables and they should be fine with
no additional changes. The existing methods already have an option to
use size_t rather than uint8_t.
There's a few methods which return int instead of size_t, which isn't
great from a portability perspective but will be fine since this only is
designed to run on the ESP8266.'
Fixes https://github.com/esp8266/Arduino/issues/8391
------
Feel free to use this patchset in full or in …
=> Wire buffer length improvments.

cores/esp8266/umm_malloc/umm_malloc.cpp
Extracted fix from upstream for umm_blocks() - On allocations that were too
large, umm_blocks() could return an incorrectly truncated value when the result
is cast to uint16_t.
=> Fix umm_blocks()

cores/esp8266/umm_malloc/Notes.h, cores/esp8266/umm_malloc/dbglog/README.txt, cores/esp8266/umm_malloc/dbglog/dbglog.h, cores/esp8266/umm_malloc/umm_heap_select.h, cores/esp8266/umm_malloc/umm_info.c, cores/esp8266/umm_malloc/umm_integrity.c, cores/esp8266/umm_malloc/umm_local.c, cores/esp8266/umm_malloc/umm_local.h, cores/esp8266/umm_malloc/umm_malloc.cpp, cores/esp8266/umm_malloc/umm_malloc.h, cores/esp8266/umm_malloc/umm_malloc_cfg.h, cores/esp8266/umm_malloc/umm_poison.c
This PR is _only_ style changes.
Upstream `umm_malloc` at git hash id `4dac43c3be7a7470dd669323021ba238081da18e`
processed all project files with the style program `uncrustify`.
This PR updates our ported version of `umm_malloc` processed with `uncrustify`.
This should make subsequent merges of upstream into this port easier.
This also makes the style more consistent through this port..
=> Sync umm_malloc style with upstream

keywords.txt
PWMRANGE was defined up until v2.7.4:
```
$ cd ~/Library/Arduino15/packages/esp8266/hardware/esp8266
$ grep -R "PWMRANGE" 2.7.4
2.7.4/keywords.txt:PWMRANGE	LITERAL1
2.7.4/tests/host/common/Arduino.h:#define PWMRANGE 1023
2.7.4/cores/esp8266/core_esp8266_wiring_pwm.cpp:static int32_t analogScale = PWMRANGE;
2.7.4/cores/esp8266/Arduino.h:#define PWMRANGE 1023
```
The define was removed in favour of the Arduino standard value of 255
but the keyword coloring was left behind:
```
$ cd ~/Library/Arduino15/packages/esp8266/hardware/esp8266
$ grep -R "PWMRANGE" 3.0.2
3.0.2/keywords.txt:PWMRANGE	LITERAL1
```
In the Arduino IDE, the coloring makes it look like PWMRANGE still
exists, when it doesn't, which is confusing.
Signed-off-by: Phill Kelley <pmk.57t49@lgosys.com>
=> Obsolete PWMRANGE still defined as LITERAL1 in keywords.txt

boards.txt, cores/esp8266/Esp-frag.cpp, cores/esp8266/Esp.cpp, cores/esp8266/Esp.h, cores/esp8266/core_esp8266_vm.cpp, cores/esp8266/umm_malloc/umm_local.c, libraries/esp8266/examples/HeapMetric/HeapMetric.ino, libraries/esp8266/examples/irammem/irammem.ino, tests/host/common/MockEsp.cpp, tools/boards.txt.py
Adjust VM Address mask to allow up to 8M Byte parts.
Allow for free heap size values over 64K
`ESP.getHeapStats(, uint32_t,)`
`uint32_t getMaxFreeBlockSize();`
=> Fix VM Address mask

cores/esp8266/Stream.cpp
As shown in #8452, the default implementation for `int Stream::read (uint8_t* buffer, size_t maxLen)` only writes every second byte into the given buffer.
fixes #8452
=> fix Stream.read into buffer ignoring every second byte 

cores/esp8266/WString.cpp, cores/esp8266/WString.h
Fixes #8462 
This avoids the null termination requirement of both `String::substring` and `String::lastIndexOf` by using APIs that don't require it. So we can stop writing to the buffer inside of const functions.
There might be a off by one error there, I need to take a better look at the code and would love if someone could review.
=> Avoid writing to const storage

doc/installing.rst
Hey! I have done the changes in documentation. Please review this.
If any changes still needed please inform me. I will surely do that.
Thanks!
=> Updated documentation #8487

doc/faq/a02-my-esp-crashes.rst
per https://github.com/esp8266/Arduino/issues/8421 and https://github.com/esp8266/Arduino/issues/8475
after checking HW, suggest to check SW as well at least by enabling compiler warnings
(and also note of the IDE weirdest defaults causing issues we expected to stay solved)
=> Docs: add an entry about compiler warnings

libraries/SD/src/SD.h, libraries/SDFS/src/SDFS.h
Remove `using namespace fs;` from SDFS.h
Fix everything that depended on it
As noticed in the #8483
=> Correctly using fs:: namespace in SD & SDFS

libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
In testing, I had an HTTP server that would server a 200 OK header, then crash, killing the connection.
The result was an exception in HTTPUpdater, which turned out to be due to passing a null pointer to `WiFiClient::stopAllExcept`
In catching this, I've chosen to return `HTTPC_ERROR_CONNECTION_LOST`.  This is an HTTPClient definition, rather than an HTTPUpdate one, which makes me a little uneasy.  I've justified it to myself on the basis that:
1. There is no pre-existing HTTPUpdate value that seems appropriate, and
2. The ones that _are_ defined are preceded by the comment: `/// note we use HTTP client errors too [...]`
=> Catch a possible null-dereference

platform.txt
Fixes issue identified by @jjsuwa-sys3175 in
https://github.com/esp8266/Arduino/commit/46190b61f159bbaa614d046d8b229cd648e9dccc#r69649862
Tested by adding a space to my git repo's path:
````
"/home/earle/Arduino/hardware/esp8266com space/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE -DESP8266 "-I/home/earle/Arduino/hardware/esp8266com space/esp8266/tools/sdk/include" "-I/home/earle/Arduino/hardware/esp8266com space/esp8266/tools/sdk/lwip2/include" "-I/home/earle/Arduino/hardware/esp8266com space/esp8266/tools/sdk/libc/xtensa-lx106-elf/include" -I/tmp/arduino_build_295618/core -c "@/home/earle/Arduino/hardware/esp8266com space/esp8266/tools/warnings/none-g++" -Os -g -free -fipa-pta -Werror=return-type -mlongcalls …
```
=> Properly quote paths for GCC warnings files

libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
Fixes #8331
The problem is that `_canReuse` was not reset in begin, like in `HTTPClient::setURL`.
Ideally begin should not be called twice if the client hasn't changed, but it may happen, better safe than sorry.
=> Fix reuse for different URIs in HTTPClient::begin

cores/esp8266/heap.cpp
Some calls from the SDK to pvPortMalloc, use NULL for the file pointer argument.
=> Fix OOM print handling of NULL file pointer

libraries/ESP8266WebServer/src/ESP8266WebServer.h
There is no implementation for the variant of the `ESP8266WebServer::send` function that takes a reference to a `Stream`.
This fixes the error by calling the version that takes a pointer.
=> ESP8266 Web Server: Fix send stream by reference

libraries/ESP8266WiFi/src/BearSSLHelpers.h, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h
Fixes #8534
This brings two questions tho, should we break backwards compatibility with a usage that is literally broken, so nobody should be actually depending on this? As these changes technically make some broken code to stop compiling. I'm out of the loop on how the community decides on situations like this.
And what is with the fake `WiFiClientSecureCtx::clone`? With my changes it actually always fails to compile, so I moved to causing a runtime failure that will be more explicit. What do you all think? I am open to suggestions.
I see that there is a different PR tackling a similar issue (targeting the original issue), and it might expand the functionalities, but I see this as orthogonal, if we decide to support copy operations in some of those classes in the future we can remove the …
=> Delete operator=(Self&) when copy constructor is deleted

cores/esp8266/WString.cpp, cores/esp8266/WString.h, tests/host/Makefile, tests/host/common/ArduinoCatch.hpp, tests/host/common/noniso.c, tests/host/core/test_string.cpp
Update itoa to be the same as newlib, also fixing edgecase of abs(INT_MIN)
Update WString.cpp:toString() integer conversions to use noniso funcs
Update WString to use C++ limits lib
Remove legacy gcc versions from Makefile and allow overrides
Don't fallback to c11 and c++11, source cannot support that
Additionally, allow test binary to accept arguments
```
~/d/e/t/host> make TEST_ARGS=[core][String] test
Makefile:31: using g++
Makefile:46: Cannot compile in 32 bit mode (g++-multilib is missing?), switching to native mode
Makefile:57: compiling in native mode
/home/runner/dev/esp8266-Arduino/tests/host/bin/host_tests [core][String]
===============================================================================
All tests passed (288 assertions in 20 test cases)
```
As mentioned by @d-a-v in …
=> Test: fixing itoa implementation and clean-up of tests and test Makefile

.github/workflows/pull-request.yml
Removing the directory while gpg-agent and dirmngr are running is not always possible, causing random errors during CI runs.
=> ci: make sure to kill gpg related processes

tests/run_CI_locally.sh
`tests/ci/check_restyle.sh` does not exist; however, `tests/ci/style_check.sh` does.
Changed `run_CI_locally.sh` to run `style_check.sh` from `ci` directory.
=> Correction to run_CI_locall.sh

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
Avoid blowing up user code when `$user:$password` string is longer than
127 bytes. Use String to both manage the memory and handle concatenation.
Also clean-up historical quicks such as
- `if(StringObject)` that is always true since we implemented SSO
- `authReq = "";` / `authReq = String();`, which will happen anyway
- `(String)...` casts that happen anyway, implicitly
=> WebServer: use String when working with Basic authentication

tools/sizes.py
Re-format the file, hints and clean-up the resulting data dict
Also include maximum aka total for every segment key, so now we could also display it every time
```
(penv) ~\D\A\s\test> C:\\Users\\maxim\\Documents\\Arduino\\hardware\\esp8266com\\esp8266/tools/python3/python3 \
-I "C:\\Users\\maxim\\Documents\\Arduino\\hardware\\esp8266com\\esp8266/tools/sizes.py" \
--elf "C:\\Users\\maxim\\AppData\\Local\\Temp\\arduino-sketch-47C53BFFA994BDA8380BC89E427DA2CA/test.ino.elf" \
--path "C:\\Users\\maxim\\Documents\\Arduino\\hardware\\esp8266com\\esp8266/tools/xtensa-lx106-elf/bin" \
--mmu "-DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000"
```
```
SEGMENT  USED     TOTAL    PERCENT  DESCRIPTION
----------------------------------------------------
ICACHE   32768    32768    100%     flash …
```
=> Table output for segment size script

doc/esp8266wifi/bearssl-client-secure-class.rst
The old link to RFC 5246 has been moved to https://tools.ietf.org/search/rfc5246
=> Update RFC 5246 URL

platform.txt
see https://github.com/esp8266/Arduino/commit/da4a19fdacd7a859da395e014c9e0fded99aa985#commitcomment-73793209
=> platform.txt: Override python3 anon pipe encoding to utf-8 for 'tools/sizes.py'

cores/esp8266/WString.h
fixes https://gitter.im/esp8266/Arduino?at=627fee0ed30b6b44ebeaa803
@bwjohns4 @jandrassy ~~there will still be a warning, because `nullptr` should be used instead of `NULL`~~.
=> WString: remove operator==(const __FlashStringHelper*)

tools/sizes.py
Due to historical circumstances, some of light/heavy version of Unicode box-drawing chars may have twice width of others (aka. "Zen-Kaku" in Japanese, means full-square), eg. All of '─'(U+2500), '│'(U+2502), '└'(U+2514) and '├'(U+251C) correspond to that in Windows Japanese fonts and locale.
Double versions, '═'(U+2550), '║'(U+2551), '╚'(U+255A) and '╠'(U+2560) are not like that.
(See [Box Drawing, The Unicode Standard](https://www.unicode.org/charts/PDF/U2500.pdf))
=> tools/sizes.py: Change Unicode box-drawing chars to that of double version

tools/sizes.py
once `tools/sizes.py` outputted to `stderr` rather `stdout` before da4a19fdacd7a859da395e014c9e0fded99aa985
(Arduino IDE 1.8.19 for Windows doesn't capture `stdout`, 2.0.0-rc6 does)
=> tools/sizes.py: Restore to the prior behavior regarding output destination

tests/host/Makefile
-j option wasn't passed to recursive 'make' calls
=> emulation on host: allow parallel compilation units

tests/host/Makefile, tests/host/common/ArduinoMain.cpp, tests/host/common/MockWiFiServerSocket.cpp, tests/host/sys/pgmspace.h
also:
- less verbose during compilation
- better handling user directories
- missing `str{,n}case_P` declarations
=> emulation on host: avoid closing STDIN

libraries/ESP8266WebServer/src/Parsing-impl.h
=> stop incorrectingly increase number of arguments when setting up arg("plain")

cores/esp8266/WString.cpp
Some char* passed may be non-zero terminated slices, we could both endup with a non-zero terminated `String` and read past the end of the allocation, so on unmapped memory (or even possibly flash memory).
This fixes the issue.
=> Avoid reading past end of non-zero terminated char arrays

libraries/ArduinoOTA/ArduinoOTA.cpp, libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer-impl.h, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
=> do not call tcp/udp ::stopAll() when it is not required to do so

tests/device/Makefile, tests/device/libraries/BSTest/Makefile, tests/device/libraries/BSTest/runner.py
Update soon-to-be deprecated code in the runner.py
https://docs.python.org/3/library/imp.html is deprecated since 3.4, will be removed in 3.12
https://docs.python.org/3/library/configparser.html readfp is replaced with read_file since 3.2, will be removed in 3.12
Use venv instead of virtualenv. We don't really use any of the extended features, and might as well  simplify installation requirements.
virtualenv/bin/python can execute runner.py inside of venv, no need to activate beforehand.
=> Handle recent python versions in device tests

.github/dependabot.yml, .github/workflows/pull-request.yml, .github/workflows/release-to-publish.yml, .github/workflows/tag-to-draft-release.yml
- Update `uses: ...` versions (resolves #8620)
- Add dependabot.yml so for the next action major update it will create a pull request
- Set token permissions for the workflow, in case ${{ github.token }} is used at some point
https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/security-guides/automatic-token-authentication
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
ref. apps documentation to understand what API endpoints need enabled
https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
=> Github actions updates and setup dependabot

tests/host/common/MocklwIP.cpp, tests/host/common/user_interface.cpp
- fix mismatched header of lwIP's `dns_getserver()` implementation
- correctly initialize emulated netif0
- make ipv6 example unfail (even if emulation on host is ipv4 only)
=> emulation on host: fix incorrect lwIP DNS implementation

libraries/ESP8266WiFi/examples/WiFiScan/WiFiScan.ino, libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiScan.h
The NONOS SDK's `struct bss_info` in `user_interface.h` has grown since the beginning of this project. The additional elements are not accessible. Add a method for R/O access to full `struct bss_info`.
```cpp
const bss_info *ESP8266WiFiScanClass::getScanInfoByIndex(int i);
```
Update example WiFiScan.ino
Requested here https://github.com/esp8266/Arduino/issues/7965#issuecomment-1266744892. I have also needed this feature.
=> Expand access to SDK's struct bss_info

doc/faq/a06-global-build-options.rst, doc/faq/readme.rst
* `doc/faq/a06-global-build-options.rst: WARNING: document isn't included in any toctree`
ref. https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#special-metadata-fields
same as other a#-... .rst pages
* `doc/faq/readme.rst:190: WARNING: Inline literal start-string without end-string.`
just a typo
=> Fix Sphinx build warnings

doc/esp8266wifi/scan-class.rst, doc/esp8266wifi/scan-examples.rst
=> Update WiFi scan docs

cores/esp8266/Arduino.h, cores/esp8266/Esp-frag.cpp, cores/esp8266/Esp.cpp, cores/esp8266/Esp.h, cores/esp8266/heap.cpp, cores/esp8266/heap_api_debug.h, cores/esp8266/mmu_iram.h, cores/esp8266/umm_malloc/Notes.h, cores/esp8266/umm_malloc/umm_info.c, cores/esp8266/umm_malloc/umm_local.c, cores/esp8266/umm_malloc/umm_malloc.h, cores/esp8266/umm_malloc/umm_malloc_cfg.h, cores/esp8266/umm_malloc/umm_malloc_cfgport.h, cores/esp8266/umm_malloc/umm_poison.c
Create dedicated function for `xPortGetFreeHeapSize()` that only reports on DRAM.
NONOS SDK API `system_get_free_heap_size()` relies on `xPortGetFreeHeapSize()` for the free Heap size.
Possible breaking change for multiple Heap Sketches calling `system_get_free_heap_size()`; it will now always report free DRAM Heap size. 
Update and export `umm_free_heap_size_lw()` to report the free Heap size of the current Heap. 
Updated ESP.getFreeHeap() to use `umm_free_heap_size_lw()`.
Updated build options to supply exported `umm_free_heap_size_lw()` via either UMM_STATS or UMM_INFO.
Improved build option support via the `SketchName.ino.globals.h` method for Heap options: UMM_INFO, UMM_INLINE_METRICS, UMM_STATS, UMM_STATS_FULL, UMM_BEST_FIT, and UMM_FIRST_FIT. While uncommon to change from the …
=> Ensure xPortGetFreeHeapSize reports DRAM

libraries/ESP8266WiFi/src/WiFiClient.h, libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h
Fixes the https://github.com/esp8266/Arduino/issues/8692
Fixes the incorrect behavior of WiFiClientSecure.remoteIP(), .remotePort(), .localIP(), .localPort().
=> Fix WiFiClientSecure remoteIP(), remotePort(), localIP(), localPort() functions

cores/esp8266/StackThunk.cpp, cores/esp8266/StackThunk.h, cores/esp8266/cont.h, cores/esp8266/cont_util.cpp, cores/esp8266/core_esp8266_main.cpp, cores/esp8266/core_esp8266_postmortem.cpp, cores/esp8266/debug.h
Wire everything that relies on stack smashing detection to call `__stack_chk_fail()` (aka what libssp / ssp / stack-protector uses) Expose it in our debugging header
Rename overflow -> smashing, as these are different things we are trying to detect (meaning, that we check for things writing there, not some kind of `alloca` issue or the way `-fstack-check` would have worked) ref. #8666
`-fstack-protector` continues to work as it always did CONT replaces `abort()`, also moves its check to the loop wrapper to avoid dumping otherwise useless SYS context memory StackThunk replaces a similar `abort()` call
=> Nice stack smashing postmortem message

cores/esp8266/LwipIntf.h, cores/esp8266/LwipIntfCB.cpp, libraries/ESP8266mDNS/src/LEAmDNS.cpp, libraries/ESP8266mDNS/src/LEAmDNS.h, libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp, libraries/ESP8266mDNS/src/LEAmDNS_Transfer.cpp
follow up #8676 
* sprinkle IPAddress(...).isSet() across our loops to avoid polling on a stopped interface. status callback and netif_is_up **does not guarantee and we could use the interface**!
* register *one* status callback per instance, e.g. when begin() is called multiple times (also notice a subtle issue with schedule function when instance is delete'ed)
* consistent LwipIntf callback signature. no need for rvalue, just pass stdfunc as-is and let the compiler figure it out
=> Generic netif status callback and mDNS

doc/reference.rst
The call path for "new" implemented in `abi.cpp` is not in IRAM and should not be called from an ISR.
=> Correction on Heap API available from ISR

libraries/ESP8266WiFi/src/BearSSLHelpers.cpp
This fixes the error in #8707 but needs a professional review, since I am no C programmer.
The signature check fails, if the `hash->len()` is only 32 bytes instead of the assumed 64 bytes.
Since the variable `HashLengthMax` has a max in its name, I assume that it is allowed to have shorter hash lengths.
I assume that `memcmp` did an buffer over read here and read stuff after the 32 bytes of hash. But that's my narrow understanding of the internals of C as a non-C developer.
=> Only check the actual used lenght of the hash.

tools/sdk/ld/eagle.app.v6.common.ld.h
For GCC LD scripts, using commas in a section expression sometimes cause problems.
With this change,  `.text.gdbstub*` moved from IROM to IRAM where it was intended to be. 
@earlephilhower please correct me or confirm. Thanks!
Resolves issue #8716
I could not find an explanation of how a "," was to be interpreted. It looks like a simple `*(.somthing*, .something2*)` worked; however, a more complex `*(.text.something*, .text.something2*)` did not - _most of the time_.
I don't have much experience with LD scripts. Anyone with more insight please help.
=> Fix typo in section list

doc/esp8266wifi/client-class.rst, libraries/ESP8266WiFi/src/WiFiClient.cpp, libraries/ESP8266WiFi/src/WiFiClient.h
Api for saving heap when Client class is used by a Server (WiFiServer class): Client = Server.available(). 
Suppose the local end is the server and the remote end is the client, we will deal with heap memory at the local end.
When the local application (server) decides to close an active connection with a remote end it issues an Client.stop.
The stop() function calls the close() function of ClientContext class which in turn calls tcp_close.
The connexion is closed by tcp_close and the protocol control block (pcb) can be put in the following states depending on the requests sent by the remote: CLOSING, FIN_WAIT_1 and FIN_WAIT_2. In theses states pcbs are not freed, then consume some memory heap.  
If an acknowledgment from the remote end is received, the pcb enter in TIME_WAIT state for …
=> Api in WiFiClient class for saving heap memory

libraries/ESP8266httpUpdate/examples/httpUpdate/httpUpdate.ino, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp, libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
Shortening up the default hard-coded 8000 ms timeout, will save energy when module can't reach its update server, especially on battery powered projects, and otherwise provide adaptability to the local wlan. The ESPhttpUpdate object is auto-created by #including ESP8266HTTPUpdate. ESP8266HTTPUpdate also provides a constructor with param httpClientTimeout, but to use it required destroying the auto ESPhttpUpdate object, or creating a secondESPhttpUpdate(timeout) object.
=> Add setClientTimeout() to ESP8266HTTPUpdate

cores/esp8266/FS.cpp
Previously, File::readString used a C-style string as an intermediate buffer via the String += operator. This treats a NUL byte as a terminator, making this function work incorrectly if the File contains binary data.
This commit switches the function to use String::concat, which doesn't treat NUL bytes any differently (and is a bit faster, because it doesn't need to use strlen).
=> Fix File::readString to work with binary data

doc/ota_updates/readme.rst
Text referred to an object name ESPHTTPUpdate, but context called for class name ESP8266HTTPUpdate
=> Correct class name in readme.rst

libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
While my first implementation of an HTTP server update it was useful to see the output of the [PHP script](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#id5) to see what went wrong.
=> add DEBUG payload output

libraries/Servo/src/Servo.cpp, libraries/Servo/src/Servo.h
The current implementation of the Servo lib always resets the position when `detaching`.
In AVR Servo, this isn't the case, instead, it doesn't move the servo but leaves it as it was before getting detached.
Fixes #8752.
Should obviate #8723
=> Servo: re-attach to same value (position)

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h
The problem is that WiFi.disconnect function always set SSID and Password to NULL. On ESP32's version of Arduino, user can define if the config should be ever touched or not. When manually implementing reconnection, current state requires to store credentials externally between disconnect and connect method calls.
This PR aims to fix this problem by introducing second variable (eraseap), which defaults to false to maintain compatibility.
=> Add eraseap option to WiFi disconnect method.

cores/esp8266/heap.cpp
to pvPortCallocIram, pvPortZallocIram, and pvPortMalloc(,,,true) case. Improved comments.
=> For SDK v3.0, add missing DRAM fallback 

cores/esp8266/Stream.cpp, cores/esp8266/Stream.h
cherry-pick updates for `Stream::peekNextDigit()` from AVR implementation: decimal dot is optionally allowed
fixes #8782
=> fix Stream's parseFloat()

cores/esp8266/LwipIntfDev.h, libraries/lwIP_Ethernet/examples/EthClient/EthClient.ino, libraries/lwIP_Ethernet/src/EthernetCompat.h, libraries/lwIP_enc28j60/src/utility/enc28j60.cpp, libraries/lwIP_enc28j60/src/utility/enc28j60.h, libraries/lwIP_w5100/src/utility/w5100.h, libraries/lwIP_w5500/src/utility/w5500.h
Implementation of `::isLinked()` for ethernet drivers:
This function returns true when the ethernet chip is physically connected.
(*edited*) It currently works and has been tested with W5500 and ENC28J60, and it seems it is not implementable with W5100.
An additional `::isLinkDetectable()` tells when `::isLinked()` is not trivially implemented.
(*edited*)`::connected()` ~is software only and is left unmodified for backward compatibility~ is updated to check link status to [solve compatibility with WiFi API](https://github.com/esp8266/Arduino/pull/6680#pullrequestreview-558672527).
Closes #8099
=> PHY status API for ethernet drivers

cores/esp8266/IPAddress.cpp, cores/esp8266/IPAddress.h, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h, tests/host/common/ClientContextTools.cpp
Make a single hostByNameImpl() instead of two implementations
Do not share 'pending' flag between requests, allocate memory per invocation
Translate error message (no string in non-debug lwip) and add TIMEOUT when we exit esp_delay on timeout
Clean-up DNS type case switch and enum, it is already strong enough (and cast is undefined behaviour)
as noticed in #8780
=> hostByName timeout fixes

package/README.md
Honorary mentions of HedgeDoc and Github release notes generator
Remove `staged-for-release` from step 12., it did not get much use (doubt it will)
Translate deploy key ssh-keygen into one-liner, markdown `console` format and remove all extra ticks from code blocks #8790
=> Amend packaging instructions

libraries/ESP8266WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino
The AdvancedWebServer.ino example allocated a 400 byte char array on the stack which, in the case of the example, will work but in general is a dangerous thing to show new users to try.
Instead, use a StreamString to generate the string on the heap.
=> Remove 400b stack allocation from AdvWeb example

cores/esp8266/esp_priv.h
Gcc is more lenient with this, Clang is not
=> Pointer<->Int casts are not constexpr

cores/esp8266/wpa2_eap_patch.cpp
The build problem only shows when selected through board Generic.
=> Typo in EAP patch

.github/workflows/build-ide.yml, cores/esp8266/Esp.cpp, cores/esp8266/core_esp8266_eboot_command.cpp, cores/esp8266/core_esp8266_features.h, cores/esp8266/coredecls.h, cores/esp8266/crc32.cpp, tests/sanity_check.sh
Missing stdbool.h for 'bool' in features .h, at least one user is [arduinoWebSockets](https://github.com/Links2004/arduinoWebSockets/blob/323592f622e0ec8f9ce1f995c5777d9bbaaae1ec/src/libb64/cencode.c#L8-L10)
Also noticed and removed default argument from crc32() in internal .h that *may* be used in .c
(not sure how it worked at all, but at least in our .cpp Gcc somehow figured out it is a no overload solution)
fix #8794
=> Fix C builds

platform.txt, tools/mkbuildoptglobals.py
=> Portable python fix for mkbuildopts

cores/esp8266/Schedule.cpp, cores/esp8266/Schedule.h, cores/esp8266/core_esp8266_main.cpp, cores/esp8266/core_esp8266_wiring.cpp, cores/esp8266/coredecls.h, libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp, libraries/ESP8266WiFi/src/include/ClientContext.h
Recurrent scheduled functions will always be running in background.
`esp_delay()`'s interval (`intvl_ms`) is internally kept to its highest  value allowing to honor recurrent scheduled functions requirements.
This allows examples like [`EthClient`](https://github.com/esp8266/Arduino/blob/840ef782371d2c0310aa9cbde8a311fd8b80bf28/libraries/lwIP_Ethernet/examples/EthClient/EthClient.ino#L90) to keep answering to `ping` while "trapped" in a `delay()`.
More generally it transparently allows to keep with the arduino and nonos-sdk trivial programming way and still use background services or drivers running regularly.
=> delay / esp_delay: transparently manage recurrent scheduled functions

tools/elf2bin.py
Properly handle Popen object, it takes care of everything we need to do like .communicate() and handle timeouts. Introduce a small timeout to run so we also know when that happens
Clean-up with pythonic path join and formatting through f"" strings
see #8727
=> Use subprocess.run in elf2bin

tools/upload.py
Currently some exceptions cause the script to exit with code 2, but without any relevant error message.
As an example, I had an issue with my USB drivers. But the only message I saw using the Arduino IDE was: `uploading error: exit status 2`. With this code change I could see a more specific `Resource busy` error message, which helped me identify the actual problem.
=> Log all exceptions in upload.py

tools/mkbuildoptglobals.py
Works on Windows 10. I don't have an 11 platform to test on. Uses the preferred method for finding a path to `AppData\Local`
* May resolve https://github.com/esp8266/Arduino/issues/8811#issue-1535509475
Remove bad return value fqfn2. Reproduced and fixes the issue a commenter left at
* https://github.com/esp8266/Arduino/issues/8811#issuecomment-1384628605
=> Fix for Windows 11 preferences.txt not found - maybe

tools/mkbuildoptglobals.py
Changes:
* Only rely on `perferences.txt ` when requested.
* Always assume shared `core.a` caching is in use,
* Ignore the passed-in IDE version. Too often, the value is not correct
Status: ready
=> New handling of missing perferences.txt

libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp, tests/host/common/UdpContextSocket.cpp, tests/host/common/include/UdpContext.h, tests/host/common/mock.h
This allow working with mDNS on host.
=> emulation on host: fix UDP seek&peek

libraries/SD/src/SD.cpp, libraries/SD/src/SD.h
* re-use SdFat access mode through static const, no need to hard-code our own value w/ cast in the macro
* separate access-modes from flags
* simple compile-time tests in .cpp
resolve #8831
=> SdFat -> FS HAL mode fixes & test

libraries/esp8266/examples/LowPowerDemo/LowPowerDemo.ino
Fix for: CRC checking of data read from RTC was always true in setup() function, due to typo in expression.
=> Fix typo in LowPowerDemo.ino

cores/esp8266/core_esp8266_postmortem.cpp
Improve divide by 0 reporting to point back at the divide function caller
Improve stack offset adjustments to be independent of `__wrap_system_restart_local()`'s  stack frame size.
=> Postmortem improvements

tools/mkbuildoptglobals.py, tools/sizes.py
Moved up `os.makedirs` for `./core/` directory.
Strange problem creating files with file paths with spaces. 
Strange that "create file" would work when the path did not contain spaces and the last folder of the path hadn't been created.
Added try/except on main to commit print buffer on traceback for context.
Additional issues with diacritics and locale character encoding for shell vs source code.
`build.opt` is written with the same encoding as the shell; however, the data read from the `Sketch.ino.global.h` is `UTF-8`.
should resolve https://github.com/esp8266/Arduino/issues/8856#issue-1582158038
=> Resolve Windows path problems

cores/esp8266/core_esp8266_phy.cpp
The `rts_reg` addresses referenced are not valid for SDK v2.0.0 and up. For `rts_reg[30] = 0;` on SDK v1.1.0, it cleared a checksum. On SDL v2.0.0, it zeros `TestStaFreqCalValInput`.
I don't think this is needed; however, if you have a need to recreate the old behavior for comparison, use `RF_PRE_INIT()` as shown:
```cpp
#include <Esp.h>
RF_PRE_INIT() {
#if 1 && (NONOSDK < (0x30000))
// Old legacy SDK v1.1 and earlier patch
// Clear RTC RAM backup area checksum
volatile uint32_t* rtc_reg = (volatile uint32_t*) 0x60001000;
rtc_reg[30] = 0;
// Hide checksum error message
system_set_os_print(0);
#endif
#if 0 && (NONOSDK >= (0x20000))
// I don't expect this to be useful; however, this should do what was
// intended to have been done before.
//
// For SDKs 2.0.0 through 3.0.5
// Clear RTC RAM …
```
=> Remove stale patch for SDK v1.1 and earlier

cores/esp8266/flash_hal.h
The assignment done in FLASH_MAP_SETUP_CONFIG_ATTR did not apply the attribute to __flashdesc, and made it impossible to override it with FLASH_MAP_SETUP_CONFIG.
=> Bad weak assignment in flash_hal

libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino, libraries/esp8266/examples/SerialStress/SerialStress.ino, libraries/lwIP_PPP/examples/PPPServer/PPPServer.ino
Fixed onReceive IRAM cache issues.
Example for power-saving with wakeup from suspend by SW serial RX event.
=> EspSoftwareSerial 8.0.1: onReceive bug fix and new namespace

doc/installing.rst, tools/mkbuildoptglobals.py
resolve #8877
also fix spurious warning when getdefaultencoding() is used with versions ≥3.11
=> mkbuildoptglobals.py: assert python version

cores/esp8266/core_esp8266_features.cpp
No need to issue a MEMW instrunction per load from each cache line. Only once after the last load is sufficient.
>MEMW ensures that all previous load, store, acquire, release, prefetch,
>and cache instructions perform before performing any subsequent load,
>store, acquire, release, prefetch, or cache instructions.
>  -- MEMW (Memory Wait), 6. Instruction Descriptions, Xtensa ISA Reference Manual (p.409)
=> cores/esp8266/core_esp8266_features.cpp: Make precache() cleaner and more efficient

libraries/ESP8266WiFi/examples/BearSSL_CertStore/certs-from-mozilla.py
pems has no headers. That operation removes a certificate.
=> Fix removing first certificate in certs-from-mozilla.py

cores/esp8266/core_esp8266_postmortem.cpp
A popular method of handling an unrecoverable state is to reboot. The SDK does this in many places by printing a cryptic debug message followed by something equivalent to `while(true){}`, which compiles down to `loop: j loop`, creating a Soft WDT reset. 
This change calls attention to these deliberate WDT resets at Postmortem. In the one case that I examined closer, the SDK responded this way after an OOM event.
For SDK 3.0.5, I found this many "deliberate infinite loops":
| Libary | count |
| ---- | ----:|
| libpp.a |81
| libmain.a |8
| libespnow.a | 6
=> Soft WDT: detect deliberate infinite loop at Postmortem

cores/esp8266/core_esp8266_postmortem.cpp
Fixes to recent changes to Postmortem.
Fix for `dangerous relocation: j: cannot encode`
To cover large jump offsets, use relaxed jump (`J.L`)  in `__wrap_system_restart_local`.
Add check that epc1 is a valid code address before reading.
Should resolve:
* https://github.com/esp8266/Arduino/issues/8923#issue-1708519374
=> Fixes to recent changes to Postmortem.

cores/esp8266/umm_malloc/umm_malloc.cpp, cores/esp8266/umm_malloc/umm_malloc_cfg.h
Bug introduced with PR fix #8914.
When a reallocated pointer could not grow in place, a replacement allocation was created. Then UMM_POISON was written to the wrong block.
This should resolve:
- https://github.com/esp8266/Arduino/issues/8952#issue-1792056809
=> Fixes occasional UMM_POISON failure

libraries/ESP8266WiFi/examples/BearSSL_MaxFragmentLength/BearSSL_MaxFragmentLength.ino
https://tls.mbed.org/ host does not support MFLN and Also Redirects the Client.
https://api.my-ip.io/ip is a better alternative, supporting MFLN and allowing the user to get a simple text with a useful information.
=> Change host from tls.mbed.org to api.my-ip.io

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiAP.h
Adding broadcast address retrieval in Access Point mode, example IPAddress broadcast = WiFi.softAPbroadcastIP();
=> Add softAPbroadcastIP

cores/esp8266/Udp.h, doc/esp8266wifi/udp-class.rst, libraries/ESP8266WiFi/src/WiFiUdp.cpp, libraries/ESP8266WiFi/src/WiFiUdp.h
Hi,
It seems that (at least) the Arduino core and the ESP32 core both has the base `beginMulticast` virtual definition in the base `UDP` class:
```cpp
virtual uint8_t beginMulticast(IPAddress, uint16_t) { return 0; }  // initialize, start listening on specified multicast IP address and port. Returns 1 if successful, 0 on failure
``` 
In order to be compatible with libraries like [arduino-libraries/ArduinoMDNS](https://github.com/arduino-libraries/ArduinoMDNS), I've added the same base virtual function at `UDP` level here too.
With these changes, the above library works on a ESP8266 like a charm.
I'm not sure if the different already existing signature of the `WiFiUDP::beginMulticast` should be left here or not. To be backward compatible, I've added both signatures, but not sure if the one …
=> Add virtual beginMulticast(...) stub to UDP class

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h, libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp, libraries/ESP8266WiFi/src/ESP8266WiFiScan.h
https://www.arduino.cc/reference/en/libraries/wifi/wifi.bssid/
=> WiFi.BSSID and scan result BSSID with parameter as in WiFi libraries by Arduino

libraries/ESP8266WiFi/src/WiFiServer.cpp, libraries/ESP8266WiFi/src/WiFiServer.h
I did a research how different Arduino networking libraries implement the Arduino networking API.
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#server-class
For most libraries it is simpler to implement operator bool() than the method status() with its return value constants. So this PR adds bool operator for WiFiServer in the ESP8266Wifi library.
In the research I find out that end() is the most popular name for the function to stop the server and Arduino now used it too in the new WiFiS3 library.
=> WiFiServer - operator bool() and method end()

cores/esp8266/Stream.cpp, cores/esp8266/Stream.h
currently there is a
```c++
String readStringUntil(char terminator)
```
function, but there is no equivalent of it that uses string terminator. this pr implements
```c++
String readStringUntil(const char* terminator, uint32_t count = 1)
```
i found this useful for small html parsing or truncating.
=> add Stream::readStringUntil function that uses string terminator

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
reset `_useStaticIp` to false in `WiFi.disconnect()`
=> WiFiSTA - allow using DHCP again after disconnecting static IP

libraries/lwIP_Ethernet/src/EthernetCompat.h
The parameters of `begin` in EthernetCompat.h are optional but automatic values for gw IP, mask and DNS IP were not calculated.
In the `begin(mac, local_ip, arg1)`, arg1 is assumed to be the DNS IP, because it can be an address outside of the local network. Automatic gw IP based on local_ip with .1 at the end is more likely to be a right auto value than DNS IP. Basically this is the reason for the Arduino ordering of begin parameters.
=> EthernetCompat - static IP auto gw,mask,dns as in Arduino libraries

cores/esp8266/core_esp8266_vm.cpp
With the newer GCC compiler (after tag 3.0.2), example virtualmem was crashing with an HWDT reset. Reordered some SPI register set lines in `spi_init()`. New ordering was based on `SPIClass::begin` in `SPI.cpp`.
Someone with a deeper understanding of these SPI registers should review my changes.
This change may resolve issues described in
* https://github.com/esp8266/Arduino/discussions/9010
Addendum:
I have only tested with the `8M w/256K Heap External 64 MBit PSRAM` build option.
=> Resolve HWDT Reset with core_esp8266_vm

cores/esp8266/LwipIntfDev.h
While it is not a common use, I think it should be possible to do Ethernet.end() and then Ethernet.begin() with a different static IP or return to DHCP after using a static IP.
I tested it with [LegacyEthernetTest](https://github.com/JAndrassy/NetApiHelpers/blob/master/examples/LegacyEthernetTest/LegacyEthernetTest.ino) with hardwareStatus and linkStatus commented out (they don't work before begin here) and with hostByName commented out and with the getters/setters PR.
=> LwipIntfDev - method end() to enable repeated begin

tools/elf2bin.py
Remove warning when building with Python >=3.11:
```
/Users/juherr/.platformio/packages/framework-arduinoespressif8266/tools/elf2bin.py:54: SyntaxWarning: invalid escape sequence '\s'
words = re.split('\s+', line)
/Users/juherr/.platformio/packages/framework-arduinoespressif8266/tools/elf2bin.py:73: SyntaxWarning: invalid escape sequence '\s'
words = re.split('\s+', line)
```
See https://adamj.eu/tech/2022/11/04/why-does-python-deprecationwarning-invalid-escape-sequence/ for more details about the warning.
=> elf2bin.py - Fix syntax warning

cores/esp8266/LwipIntfDev.h, libraries/lwIP_Ethernet/src/EthernetCompat.h
so one more, This one is for 'modern' Ethernet libraries W5100lwIP, W5500lwIP and ENC28J60lwIP used without EthernetCompat.
I wrote [a test](https://github.com/JAndrassy/NetApiHelpers/blob/master/examples/ModernEthernetTest/ModernEthernetTest.ino) for what I consider a modern Ethernet library (one with config for static IP as in WiFi libraries) and to my surprise these libraries matched my idea. Only the automatic dns, gw, subnet values were not supported here again.
So here is the third PR for auto gw,mask,dns as in Arduino libraries. First was in 'begin' for EthernetCompat, second was `config` with two parameters in WiFiSTA.
I had to move the clearing of localIP to `EthernetCompat.end`, because in library with `config`, `disconnect`/`end` should not clear static IP settings. …
=> LwipIntfDev - config static IP auto gw,mask,dns as in Arduino libraries

doc/esp8266wifi/station-class.rst
reference: https://github.com/esp8266/Arduino/pull/9040#issuecomment-1835753590
@JAndrassy @mcspr
=> doc: config(0,0,0) to restore dhcp + mention portable network API

cores/esp8266/LwipIntfDev.h, doc/esp8266wifi/station-class.rst, libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h
reference: https://github.com/esp8266/Arduino/pull/9031#issuecomment-1839256347
@TD-er 
@JAndrassy 
reference: https://github.com/esp8266/Arduino/pull/9045#discussion_r1420859947
@mcspr
=> WiFi config(): warning for legacy idioms

libraries/ArduinoOTA/ArduinoOTA.cpp
Avoid a null pointer exception when ArduinoOTA.end() is called more than once and thus the UDP socket is already freed.
Also avoid unnecessary teardown if the class is not initialized yet (for example, begin() wasn't called yet, or end() is called multiple times).
=> Avoid NPE and "multi-deinitialization" of ArduinoOTA

libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h, libraries/ESP8266WebServer/src/ESP8266WebServer.h, libraries/ESP8266WebServer/src/Parsing-impl.h
* fix possible leak of _postArgs array in case of returning early from _parseForm().
* don't use _postArgs member, but instead use a new local variable postArgs instead.
* same for _postArgsLen member vs.local postArgsLen.
* remove useless NULL pointer check before delete().
fix #9075
=> ESP8266WebServer - fix possible memory leak in request argument handling

cores/esp8266/Updater.cpp, cores/esp8266/Updater.h
This PR adds the two missing error states when beginning an Update. There were debugging logs for this but the error state was not set which would lead to confusion
=> Add missing update error codes

doc/esp8266wifi/generic-examples.rst
=> Fix semantic typo in generic-examples.rst

cores/esp8266/Updater.cpp
This pull request introduces a fix to the signature verification, ensuring that the hash for compressed signed binaries is correctly calculated.
Previously, Arduino Core attempted to read from flash memory without proper consideration for the 4-byte alignment requirement when calculating the hash for the signature verification. This did not present an issue when uncompressed binaries are checked as all compiled binaries are 4-aligned _(unconfirmed, just an educated guess)_, and signature verification appears to work well in these cases.
When uploading a compressed binary (based on [this](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#compression)) the gzip algorithm makes no attempt to produce a 4-aligned file. The rest of the signing results in a valid signed …
=> Updater - fixed signature verification for compressed binaries

tools/decoder.py
Changes:
- avoid ctx repetition
- hide "DECODE IT"
- immediately print stack at closing marker
- check for executable decoder at startup
live command line example:
```
pyserial-miniterm /dev/ttyUSB0 115200 | \
path/to/esp8266/Arduino/tools/decoder.py \
--tool addr2line \
--toolchain-path path/to/esp8266/Arduino/tools/xtensa-lx106-elf/bin
path/to/build.elf
```
=> decoder.py: allowing to use it live

libraries/ESP8266WebServer/README.rst, libraries/ESP8266WebServer/examples/Filters/Filters.ino, libraries/ESP8266WebServer/examples/WebServer/WebServer.ino, libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h, libraries/ESP8266WebServer/src/ESP8266WebServer.h, libraries/ESP8266WebServer/src/Parsing-impl.h, libraries/ESP8266WebServer/src/detail/RequestHandler.h, libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
This PR implements filters and removable routes in ESP8266 arduino core, making it API compatible with recent changes to ESP32 WebServer API.
Reference (Recent additions to ESP32 WebServer API): 
- https://github.com/espressif/arduino-esp32/pull/9832
- https://github.com/espressif/arduino-esp32/pull/9842
- https://github.com/espressif/arduino-esp32/pull/9851
__Noteable Changes:__
1. Request Filters (`setFilter`)
2. Removable Routes (`removeRoute`, `removeHandler`, `_removeRequestHandler`)
=> Implemented support for filters and removable routes in ESP8266WebServer

libraries/ESP8266WebServer/examples/WebServer/README.md, libraries/ESP8266WebServer/examples/WebServer/WebServer.ino
* In handleRedirect() function, The redirect URL is be changed from "/$update.htm" to "/$upload.htm" to serve the built-in upload helping page.
* Readme documentation adjusted.
See Issue #9141
=> Example WebServer WebServer.ino does not redirect when index.htm does not exist

cores/esp8266/LwipIntfDev.h, libraries/lwIP_Ethernet/src/EthernetCompat.h
this PR moves to EthernetCompat the legacy Ethernet API methods added together with other methods to LwipIntfDev in my PR https://github.com/esp8266/Arduino/pull/9022 in November 2023.
I think it is better this way.
the moved methods are MACAddress, dnsServerIP and setDnsServerIP.
=> Move recently added legacy Ethernet API methods from LwipIntfDev to EthernetCompat

libraries/LittleFS/src/LittleFS.h
Partial fix #9120.  This is simple enough to include and does not increase the amount of flash writes on file updates significantly (which a modified-time 't' attribute would).
=> Add creation timestamp to LittleFS directories

cores/esp8266/core_esp8266_flash_quirks.cpp, cores/esp8266/core_esp8266_spi_utils.cpp, cores/esp8266/esp8266_undocumented.h, cores/esp8266/spi_utils.h
Resolves exceptions occurring when using `experimental::SPI0Command` for flash write operations such as: Write Status Register-1, Sector Eraser, etc.
* https://github.com/esp8266/Arduino/issues/9139#issue-2299471911
Moved PRECACHE_END to ensure `Wait_SPI_Idlep` and `xt_wsr_ps` are included in the iCache.
Added SPIUCSSETUP to give more settling time for #CS.
=> Fixes exceptions resulting from using SPI0Command

cores/esp8266/core_esp8266_noniso.cpp, cores/esp8266/stdlib_noniso.cpp, cores/esp8266/stdlib_noniso.h, tests/host/Makefile, tests/host/common/mock.h, tests/host/common/noniso.c, tests/host/common/strl.cpp, tools/sdk/include/ets_sys.h
```
/usr/include/stdlib.h:102:15: error: declaration of ‘double atof(const char*) noexcept’ has a different exception specifier
...etc...
```
```
/usr/include/string.h:506:15: error: declaration of ‘size_t strlcpy(char*, const char*, size_t) noexcept’ has a different exception specifier
...etc...
```
```console
> rpm -q -f /usr/include/string.h /usr/include/stdlib.h
glibc-headers-x86-2.38-17.fc39.noarch
glibc-headers-x86-2.38-17.fc39.noarch
```
=> Mock - update func signatures for latest glibc

.github/workflows/style-check.yml, tests/host/common/ArduinoCatch.hpp, tests/restyle.py, tests/restyle.sh, tests/test_restyle.py
similar to .ino builder, prepare a short 'diff' summary of all the requried changes https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
provide inline annotations, so it is apparent clang-format job is the cause of the PR actions check failure
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-notice-message
---
in theory, cpp-linter-action might work, see
https://github.com/cpp-linter/cpp-linter
https://github.com/cpp-linter/cpp-linter-action
fairly annoying part there would be configuring possible paths...
=> CI - restyle script summary and annotations in PRs

libraries/ESP8266WebServer/src/uri/UriRegex.h
move init outside of the body, preseve retval in case we'd want to format some kind of nice error message either through DEBUG_PORT or something else ([regerror](https://linux.die.net/man/3/regerror)?)
=> ESP8266WebServer - UriRegex runtime logic within assert()

.github/workflows/style-check.yml, libraries/ESP8266WebServer/examples/WebServer/WebServer.ino, libraries/ESP8266mDNS/src/LEAmDNS.h, libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp, libraries/ESP8266mDNS/src/LEAmDNS_Structs.cpp, libraries/I2S/examples/InputSerialPlotter/InputSerialPlotter.ino, libraries/I2S/examples/SimpleTone/SimpleTone.ino, libraries/TFT_Touch_Shield_V2/examples/tftbmp/tftbmp.ino, libraries/TFT_Touch_Shield_V2/examples/tftbmp2/tftbmp2.ino, libraries/esp8266/examples/CallBackList/CallBackGeneric.ino, libraries/esp8266/examples/SerialStress/SerialStress.ino, tests/clang-format-core.yaml, tests/device/libraries/BSTest/src/BSTest.h, tests/host/common/queue.h, tests/restyle.sh
Bump to the version used in current ubuntu-latest / ubuntu-24.04
https://github.com/actions/runner-images/issues/10636
=> CI - clang-format-18

.github/workflows/documentation.yml, doc/Makefile, doc/conf.py, doc/requirements.txt, tests/ci/build_docs.sh
abnormal version selection w/ nbsphinx causing us to fall down to 5.x.x
venv install specific versions, fix arguments provided to the sphinx-build
=> Docs - fix sphinx v8 builds

doc/conf.py
unconditional html\_theme = sphinx\_rtd\_theme
following examples and conf.py from sphinx_rtd_theme itself
=> Docs - default to sphinx_rtd_theme

.github/workflows/build-ide.yml, libraries/esp8266/examples/ConfigFile/ConfigFile.ino, tests/build.sh, tests/common.sh, tests/dep-arduino-cli.sh, tests/dep-libraries.sh, tests/lib-skip-ino.sh
Sync with GCC14 branch test scripts. macOS & Linux runners expected to work, going to check Windows rn
Remove explicit IDE, HARDWARE & LIBRARIES envirnoment in workflows in favour of script defaults
Remove explicit dependency on IDE & HARDWARE path, assume arduino-cli default paths
Remove dependency on tools/build.py in favour of directly calling arduino-cli
Bump ConfigFile dependencies, set ArduinoJson to v7 & update blob install script
=> CI - build with arduino-cli

tools/boards.txt.py, tools/get.py
py3.13 - https://docs.python.org/3/library/re.html#re.sub
> Deprecated since version 3.13: Passing count and flags as positional arguments is deprecated. In future Python versions they will be keyword-only parameters.
py3.12 - https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extraction_filter
> If extraction_filter is None (the default), calling an extraction method without a filter argument will raise a DeprecationWarning, and fall back to the fully_trusted filter, whose dangerous behavior matches previous versions of Python.
=> CI - Python deprecations

libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h, libraries/ESP8266WebServer/src/detail/etag.cpp, libraries/ESP8266WiFiMesh/src/ESP8266WiFiMesh.cpp, libraries/ESP8266WiFiMesh/src/EspnowMeshBackend.cpp, libraries/ESP8266WiFiMesh/src/TcpIpMeshBackend.cpp, libraries/ESP8266mDNS/src/LEAmDNS_Structs.cpp
ESP8266WebServer - unused static function / function inside of namespace { ... } would always trigger '-Wunused-function'
```
../../libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h:14:15: warning: ‘String esp8266webserver::calcETag(fs::FS&, const String&)’ defined but not used [-Wunused-function]
14 | static String calcETag(FS &fs, const String &path) {
|               ^~~~~~~~
```
ESP8266WiFiMesh - class constructors used instead of aggregates. gcc10.3 allows this for some reason, but not later versions
> error: designated initializers cannot be used with a non-aggregate type '...'
LEAmDNS - consistent const <-> non-const accessors for `findIP4Address()` and `answerAtIndex()`
> error: infinite recursion detected [-Werror=infinite-recursion]
=> Libraries - fix some warnings with gcc ≥12

tools/get.py
Using argparse for arguments, expose previously uncustomizable bits.
Using pathlib for paths, assume relative paths from __file__.parent as PWD
Reading tarfile with transparent compression.
Drop incorrect test for .t{...} (forgot to strip ".t"), just supply mode="r:*" and fail when read fails
Remove hard-coded dependency on 'platform' and allow to specify sys_name, sys_platform and bits.
Stub for DarwinARM, allow to fetch x86_64 packages in the meantime.
=> Tools - get.py updates

package/build_boards_manager_package.sh, tests/common.sh, tests/sanity_check.sh, tools/makecorever.py
amend #9248 
rewrite ci build pattern to only rewrite core_version.h once per job
restore behaviour from #6414 for other cases
update packaging script w/ new arguments
=> Tools - makecorever.py fixed packaging & avoid needless overwrites

cores/esp8266/StackThunk.cpp, cores/esp8266/StackThunk.h
Post #9224, allow to call 'stack_thunk_yield()' outside of bssl context
Reset 'stack_thunk_save' before returning from 'thunk_...'ed function
=> Stack Thunk - check saved a1 before using and zero after using

tools/upload.py
don't check exc_info() in `finally`, after `except Exception as e:` block sys module stops tracking it
https://docs.python.org/3/reference/compound_stmts.html#try
https://docs.python.org/3/library/sys.html#sys.exception
#8603 caused error to appear in the log, but build itself was never stopped properly
---
*edit:*
[formatting, strict write_flash opts order, atexit & traceback (fe72928)](https://github.com/esp8266/Arduino/pull/9186/commits/fe729285393716b1b219e64e6ce623efbf277f6d) 
simplify ordering of `write_flash` & `erase_region` arguments
since we always end up in `write_flash`, prefer to think of it as argument pairs 'addr' + 'path'. actual binaries go first, erase temporaries go last. construct write args beforehand and apply when finishing with the command line.
note that this also …
=> Tools - upload.py exception handling fixes

.gitignore
- boards.txt.py & mkbuildoptglobals.py temporaries / backups
- clangd cache & .json
- all .local.txt
=> Tools - ignore more cache / temporary files in git

.github/workflows/build-platformio.yml, tests/common.sh
pio-run vs. pio-ci configuration differences
`[platformio]` section is simply ignored
*[(since forever, apparently)](https://github.com/platformio/platformio-core/commit/b165c3f543533094d65544f3bc59d4f4642abc83)*
fixed sketch list for github ci builder
amend #9241 changes
=> CI - fix pio-ci library dir override

cores/esp8266/core_esp8266_spi_utils.cpp
getting rid of volatile arg(s) is must-have for -std=c++20 and later
provide helper macros to init & load vars at specific points in code
modify existing macros to use c++-style casts & less volatile
change locals to plain non-volatile variables, avoid extra memw
also fixes odd const mask load in (pre_cmd) branch added in #9140
(does not always happen, though. noticed while modifying preamble)
=> SpiUtils - explicit asm instead of volatile

libraries/ESP8266WiFi/examples/BearSSL_CertStore/certs-from-mozilla.py
site that provides CCADB is now at URL "ccadb.my.salesforce-sites.com"
=> Update Mozilla CCADB URL in certs-from-mozilla.py

tests/sanity_check.sh
Check GCC building C++ in addition to C code
Check that compiler can build and link .elf using default build flags & defines
Check for known issue w/ newlib-4.5.0 when expecting wide characters support by attempting to link `<iostream>` and `<regex>`
(fixed script from #9259 plus CI summaries)
=> Test - linkage sanity check
